### PR TITLE
fix: correct flow for creating a contributor insight from list of contributors

### LINKED ISSUE #2886: Bug: Cannot create a new list from a workspace
### Describe the bug

While exploring my repository insight, I wanted to add contributors to a list. When I select contributors and click "new user" it sends me to the workspace home. 

Screen Shot 2024-03-06 at 8 29 35 AM

Adding them to an existing list works.

### Steps to reproduce

1. View a repository insight
2. Create a new list from contributors.  

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by brandonroberts**
## Description

- Updates the navigation for creating a new contributor insight from a list of contributors
- Sets the selected contributors to the ones provided upon navigation

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2886 

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/app/assets/42211/570acebe-fd24-4171-b3a9-47d14ebf6f5a

## Steps to QA

1. Login
2. Navigate to a workspace
3. Go to a repository insight
4. Go to the contributors tab
5. Select some contributors using the checkboxes
6. Click on the Add to list button
7. Click on New list
8. Note the navigation to the new contributor insight page with the contributors selected

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by isabensusan** [comment]
thanks for this! 
Adding to an existing list works perfectly, but can we change the "new list" flow to the updated flow?

This UI is leftover from the old creation flow
image


The current UI is this one:
image


Could we change the flow so that:
1. User selects contributors on a table
2. User clicks on  "Add to contributor Insight" --> (current copy on PR is "Add to list")
3. User clicks on "New Insight" --> (current copy on PR is "New list")
4. User is taken to the "New contributor insight" page. The contributors they selected  should be pre-loaded in the table, and the insight name should be pre-populated with <Original repo insight name> + "Contributors" (but still let users change it if they want).

image

**Review by isabensusan — CHANGES_REQUESTED** [review]
(see comment ☝️  )

**Comment by brandonroberts** [comment]
@isabensusan updated to use the requested flow.

**Review by jpmcb — APPROVED** [review]
QA'd - looks solid 👍🏼

**Review by isabensusan — APPROVED** [review]
tested the new flow -- lgtm! thanks @brandonroberts  :)

**Pull request merged**
