### PR TITLE
fix: Remove the unused components - `CommandEmpty` and `CommandLis`t from the codebase

### LINKED ISSUE #2089: Bug: Refactor tailwind anti-pattern in Command component
## Current behavior

The **Command** component - `components/atoms/Cmd/Command.tsx` is having the hardcoded pixels - a tailwind anti-pattern. It will be great to refactor it with suitable Tailwind classes instead. To find the anti-pattern we can use this regex `^.*?-\[[^\d]*(\d+)[^\d]*\].*$`

This issue is related with #1522 and #2053.

## Proposed Solution
Refactor the code with suitable Tailwind classes.

### Steps to reproduce

1. Go to `components/atoms/Cmd/Command.tsx`.
2. Perform a find using  regex `^.*?-\[[^\d]*(\d+)[^\d]*\].*$`.

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### LINKED ISSUE #2129: Refactor: Remove unused components -`CommandEmpty` and `CommandList` from the codebase
### Describe the bug

The components - `CommandEmpty` and `CommandList` are not being used anywhere in the codebase right now, so, it'll be great to remove them. If we need it in the future, we can revert the removal.

### Steps to reproduce

1. Go to `components/atoms/Cmd/command.tsx`
2. You'll find the components - `CommandEmpty` and `CommandList`.
3. Search for these components in the codebase.

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by 5hraddha**
## Description

This PR replaces removes the unused components - `CommandEmpty` and `CommandList` from the codebase - `components/atoms/Cmd/command.tsx` as they are not used anywhere and have no plans to use them anytime soon.

**Suggestion**
If we need it in the future, we can revert the removal.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
Closes #2129

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by a0m0rajab** [comment]
Thanks for the PR. Could you share screenshots of the components before and after? for both mobile and desktop?

**Comment by 5hraddha** [comment]
Hi @a0m0rajab ,
The hard-coded px value was present in the`CommandList` sub component, that is not being used anywhere in the codebase as of now. That's why I mentioned that in the PR and wasn't sure what screenshot to provide..

**Review by OgDev-01 — APPROVED** [review]
👏👏

**Comment by nickytonline** [comment]
@OgDev-01, are there plans to use this component? What was it supposed to be for? Just asking, because if it's not used, we can remove it from the codebase for now. If we need it in the future, we can revert the removal.

**Comment by OgDev-01** [comment]
> @OgDev-01, are there plans to use this component? What was it supposed to be for? Just asking, because if it's not used, we can remove it from the codebase for now. If we need it in the future, we can revert the removal.

We can remove it since it's not used yet. I copied the full command pack from shadcn ui 😊. We can also remove the `CommandEmpty` parts as well since it is not used too.

**Comment by a0m0rajab** [comment]
Thank you for the information. Should we remove the component in this PR or in a new PR?

**Comment by nickytonline** [comment]
@5hraddha, you can remove the component in this PR and just rename the PR title to reflect that. Feel free to create an issue, or someone on the team can.

**Comment by 5hraddha** [comment]
Sure, @nickytonline . I'll remove the `CommandList` and `CommandEmpty` components then and will create an issue for it. Thank you!

**Comment by nickytonline** [comment]
Just link the issue to the PR and then I'll assign the issue to you. Thanks @5hraddha!

**Review by nickytonline — APPROVED** [review]
Thanks for the cleanup @5hraddha! 🧹

**Pull request merged**
