### PR TITLE
feat: add support for blogpost from other (generic) platforms 

### LINKED ISSUE #1656: Feature: Allow users to post blogs from (RSS) multiple platforms
### Type of feature

🍕 Feature

### Current behavior

I tried posting my Hashnode blog post as a highlight but I received this message:
A screenshot of the result after I tried to post my article from Hashnode
This can be a turn-off for people who either don't use Dev.to or use other platforms alongside with it. 

### Suggested solution

Create some sort of code to allow blog posts from all platforms to be shared as highlights.

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by babblebey**
## Description

This Pull Request adds support for blogpost from other platforms in highlights. Leverages the `open-graph` node library, fetches the open graph data from the given blogpost `url` provided as `highlightLink` and uses the `image` property on the data as the `blogspot` highlight type social image when posting new highlights.

### Implementation Caveat 🤔 

- **No Support for Auto-Summarize**
 
This is specifically because in order to consume the auto-summarize function, the `generateDevToBlogHighlightSummary` (which is an auto-summary function for the `DevTo` blogpost) takes two(2) arguments namely the `blogTitle` and `blogMarkdown` (which is the blog post content). This implementation uses the `open-graph` to fetch meta data which satisfies only the `blogTitle`. There isn't a straight-forward or consistent or lightweight implementation (aside scrapping 🤫) to access the body content of this generic blog post. 

In the absence of the body content of this blog post, I hence settled for implementing a notice of `no-support for auto-summarize` for the `auto-summarize` feature on the generic blog post for now.

### Changes Made

- Refactored all `DevTo` related components and functions, to reflect `DevTo***` in its naming to make them more specific to `dev.to` blog post type
- Added a `fetchOGData` endpoint in the `/api` route which fetches `open-graph` data for specified url
```js
const og = require("open-graph");

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  const url = req.query.url;
  if (req.method === "GET") {
    og(url, (error: any, meta: {}) => {
      if (!error) {
        res.status(200).json({ response: meta });
      } else {
        res.status(200).json({ response: {} });
      }
    });
  }
}

```
- Added `GenericBlogOpenGraphImage` component which consumes the `fetchOGData` endpoint, builds and sends response image as returned component node.
- Added a `isValidURL` helper function to validate url input in the `highlightLink` field on highlight input form.
- Integrated the the `GenericBlogOpenGraphImage` component and `isValidURL` function in appropriate base components.
- Fixed edge case where repository are automatically tagged to blogposts without intentionally tagged repos, resulting in repositories url that do not exist.
- Implemented a `toast` in attempt to add notification for `auto-summarize` not being supported for blogpost from these generic platform because we do not currently have any means of accessing the exact blog post body content which is one of the required parameter/content for auto-summarize.

```js
const handleGenerateHighlightSummary = async () => {
  ....

  // 🍕🍕🍕 NOTICE HERE 🍕🍕🍕 
  if (highlightLink && (!highlightLink.includes("github.com") || !highlightLink.includes("dev.to"))) {
    toast({
      description: "Auto-Summarize not supported for current link!",
      title: "Oops!",
      variant: "warning",
    });
    return;
  }

  ....
};
```

🍕

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1656 

## Mobile & Desktop Screenshots/Recordings

**Writing a (Generic) Blogpost highlight type**

[screencast-localhost_3000-2023.10.15-04_00_37.webm](https://github.com/open-sauced/app/assets/25631971/94e8879f-3f88-427d-93a7-c08c9fe2765d)

**Blogpost (without tagged repos)**

image

**Blogpost (with tagged repos)**

image

**Demo: Toast for `Not Supported Message for Auto-Summarize`**

screencast-localhost_3000-2023 10 15-02_54_52

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

This PR adds a new package `open-graph`

## [optional] What gif best describes this PR or how it makes you feel?

giphy (1)

### CODE REVIEW

**Comment by OgDev-01** [comment]
Hey @babblebey, would you mind fixing up the merge conflict before we proceed to reviewing this pr?

**Comment by babblebey** [comment]
All set @jpmcb 

Cc @OgDev-01 

🍕

**Comment by babblebey** [comment]
All set @jpmcb 

Cc @OgDev-01 

🍕

**Comment by BekahHW** [comment]
@babblebey would you mind resolving the merge conflicts on this?

**Comment by BekahHW** [comment]
Hey @babblebey I'm going to move this to draft mode until you have time to work on it.

**Comment by babblebey** [comment]
Hey apologies @BekahHW, this proved super weird of a conflict to resolve, after many attempts at resolving, It kept coming back asking that I resolve over and over again.

I ended up moving for rebasing and that brought in all the 390 changes 😞 

PR still works as it should for sure. I don't know exactly what impact the 390 changes would make on merge whenever it gets there, but I do recognize how uneasy it's become to review this PR now.... So kindly guide me here, will you say I keep this PR as is or would you prefer that I repatch this feature in another new PR that can remove the burden of the out-of-context 300+ file changes!?

Cc @OgDev-01 @jpmcb

**Comment by bdougie** [comment]
At this point this is not reviewable and the PR is getting stale.

My recommendation is create a new PR from a new branch from beta and cherry picking the commits you actually need.

Going to close this PR since this will require git surgery or some serious fixing to get back to unity.

**Comment by babblebey** [comment]
`git surgery` 😂🤣

I should patch this in less than 24h now, and I just mistakenly clicked "Delete Branch" 🤦🏾

**Pull request closed without merging**
