### PR TITLE
fix: Change announcement card on highlight feed to starsearch

### LINKED ISSUE #3312: Change ad card on highlights feed to starSearch waitlist
## Currently on [the feed](https://app.opensauced.pizza/feed)

image

## Suggested Changes

Let's have an image of the StarSearch Logo and the text:

Star Search: Copilot for git history

Sign up for StarSearch, our AI-powered feature that provides in-depth insights into contributor history and activities, bringing  a new depth of knowledge about open source projects.

button text: Join the Waitlist!

link: https://app.opensauced.pizza/star-search/waitlist

### PR DESCRIPTION
**Pull request by BekahHW**
## Description
- Changes the announcement card on the feed page to the waitlist for starSearch

## Related Tickets & Documents

closes #3312

## Mobile & Desktop Screenshots/Recordings

image

## Steps to QA

If you have it running locally go to http://localhost:3000/feed

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

**Comment by brandonroberts** [comment]
This E2E test needs updating for the title of that section.

https://github.com/open-sauced/app/blob/beta/e2e/homepage.spec.ts#L16

**Review by nickytonline — COMMENTED** [review]
I'll update the test.

**Review by nickytonline — CHANGES_REQUESTED** [review]
The image looks grainy, probably because it's the actual OG image. Can we get a better one for the size here @isabensusan?

CleanShot 2024-05-03 at 11 39 48

**Comment by isabensusan** [comment]
banner

**Comment by nickytonline** [comment]
Now the announcment card is less grainy.

CleanShot 2024-05-03 at 23 55 08

**Review by nickytonline — APPROVED** [review]
:shipit:

**Review by isabensusan — APPROVED** [review]

**Pull request merged**
