### PR TITLE
feat: add timezone filters for list contributors

### PR DESCRIPTION
**Pull request by OgDev-01**
## Description
This PR:
- adds timezone filter to the create list page for contributors
- creates a single-select component

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/app/assets/62995161/c8b8c098-b219-43fa-947b-472879a76649

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by brandonroberts — APPROVED** [review]
Works! 🍕

**Comment by bdougie** [comment]
Curious if we should only show times zones that returns results. Is that possible?

**Comment by brandonroberts** [comment]
> Curious if we should only show times zones that returns results. Is that possible?

Its possible. We would need to add an API endpoint to source timezones from our database.

**Review by jpmcb — COMMENTED** [review]
Looks like a merge conflict:

```
components/organisms/ContributorsTable/contributors-table.tsx
```

---

Is this blocked on this getting merged? https://github.com/open-sauced/api/pull/340

**Comment by OgDev-01** [comment]
> Is this blocked on this getting merged? https://github.com/open-sauced/api/pull/340

Not really, this can ship as is... follow-up prs will be made to update once we land https://github.com/open-sauced/api/pull/340

**Review by jpmcb — APPROVED** [review]

**Pull request merged**
