### PR TITLE
fix: adjust style for newsletter form so that it adjusts for smaller screens

### LINKED ISSUE #1729: Bug: "Subscribe" spills out of div
### Describe the bug

Screenshot 2023-09-20 at 9 10 26 PM

Notice how the "Subscribe" button on the highlights page spills over out of the div on Firefox. This looks fine on Chrome:

Screenshot 2023-09-20 at 9 12 38 PM

But, again, is busted on Firefox

### Steps to reproduce

1. Use firefox
2. Go to https://insights.opensauced.pizza/feed
3. Notice the "Subscribe" button is spilling over to the right

### Browsers

Firefox

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by RitaDee**
## Description
Update the NewsletterForm component to make the email input field fit well.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1729

## Mobile & Desktop Screenshots/Recordings

On Safari:
https://github.com/open-sauced/app/assets/106407013/acf6e254-4bd1-423c-b814-84ae526ddd4d

image

On Chrome:
https://github.com/open-sauced/app/assets/106407013/11c4b371-3423-4def-9a41-53100a964eb2

image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by OgDev-01** [comment]
Judging from the screenshots... This fixes the overflow, but i think a better approach is to wrap the container so the button drops to the bottom when the viewport becomes smaller. cc: @RitaDee

**Comment by OgDev-01** [comment]
Just like the screenshot below, but the button should be aligned to the right
image

**Comment by RitaDee** [comment]
> Just like the screenshot below, but the button should be aligned to the right image

Done.

**Review by jpmcb — CHANGES_REQUESTED** [review]
Looks like the button is always dropped down below the actual form field, regardless of sizing of the window:

Screenshot 2023-10-04 at 7 46 05 AM

I don't think we want to completely refactor this design: we should keep the original view when possible.

**Comment by RitaDee** [comment]
> Looks like the button is always dropped down below the actual form field, regardless of sizing of the window:
> 
> Screenshot 2023-10-04 at 7 46 05 AM
> 
> I don't think we want to completely refactor this design: we should keep the original view when possible.

Noted.

**Review by OgDev-01 — APPROVED** [review]
LG now ✅

**Comment by RitaDee** [comment]
> LG now ✅

On Firefox, it is not silk yet. I am still working on it. Thanks for the review.

**Comment by nickytonline** [comment]
It works on Chromium browsers and FireFox, but I noticed a weird behviour where it goes from side by side to button below as expected as your screen is smaller, but if I keep shrinking, it goes side by side again.

**Chromium**

CleanShot 2023-10-06 at 09 44 23

**Firefox**

CleanShot 2023-10-06 at 09 47 40

**Comment by RitaDee** [comment]
> It works on Chromium browsers and FireFox, but I noticed a weird behviour where it goes from side by side to button below as expected as your screen is smaller, but if I keep shrinking, it goes side by side again.
> 
> **Chromium**
> 
> CleanShot 2023-10-06 at 09 44 23 [ CleanShot 2023-10-06 at 09 44 23 ](https://user-images.githubusercontent.com/833231/273227185-5d52ee0d-4e07-4a3d-9bf2-8832fa7837f0.gif) [ ](https://user-images.githubusercontent.com/833231/273227185-5d52ee0d-4e07-4a3d-9bf2-8832fa7837f0.gif)
> 
> **Firefox**
> 
> CleanShot 2023-10-06 at 09 47 40 [ CleanShot 2023-10-06 at 09 47 40 ](https://user-images.githubusercontent.com/833231/273227381-815a9e37-53d2-40de-8e3f-b77351590b34.gif) [ ](https://user-images.githubusercontent.com/833231/273227381-815a9e37-53d2-40de-8e3f-b77351590b34.gif)

The behaviour is because I am using a container query, not a media query. So, when the container can flex the two children it displays flex and when it cannot it displays a flex-wrap.

**Comment by babblebey** [comment]
That looks like the intended behaviour of @RitaDee implementation yes. 😃 

She's looks to have implemented [container-queries](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_container_queries), over `media-queries`

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
