### PR TITLE
fix: added dropdown icon instead of hash icon

### PR DESCRIPTION
**Pull request by Gourav2609**
## Description

Earlier:

image

Now:
image

this is reference to the Issue #1812 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [1 ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [1 ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

No this is not required since i just  replaced a icon

### CODE REVIEW

**Comment by OgDev-01** [comment]
Thanks @Gourav2609 for turning this around 😊

**Comment by Gourav2609** [comment]
> Thanks @Gourav2609 for turning this around 😊

My pleasure @OgDev-01 😇😇

**Review by BekahHW — CHANGES_REQUESTED** [review]
I don't think we want to change the icon. The hash svg, should contain the hash symbol. If there isn't currently an icon  for the inverted triangle, it should be added and then the line of code that currently uses the hash svg should be updated to the inverted triangle. 

Does that make sense?

**Comment by nickytonline** [comment]
> I don't think we want to change the icon. The hash svg, should contain the hash symbol. If there isn't currently an icon for the inverted triangle, it should be added and then the line of code that currently uses the hash svg should be updated to the inverted triangle.
> 
> Does that make sense?

Just reiterating what @BekahHW mentioned. We have the other icon.

**Pull request closed without merging**
