### PR TITLE
feat: add repo filtering to contributions tables on contributor profile

### LINKED ISSUE #2024: feature: Filter contributions on the user profile
I really like this quality of life improvement. We need more of this in the app. While exploring this through QA, I noticed a familiar face in the contribution list for twitter/the-algorithm.

On the profile it is hard to know which contribution is for the algorithm without clicking each link. It would be nice to filter per repo or highlight on hover or similar. 

Screen Shot 2023-10-31 at 11 21 52 AM

_Originally posted by @bdougie in https://github.com/open-sauced/app/pull/2023#pullrequestreview-1706630364_

### PR DESCRIPTION
**Pull request by brandonroberts**
## Description

- Adds repo filtering to contribution sections on the contributor profile
- Clicking on a repository filters the pull requests and issue comments below. Clicking again toggles the filter.

## Related Tickets & Documents

Closes #2024 

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/app/assets/42211/c38b14ef-5935-4c20-b001-24f6766de852

https://github.com/open-sauced/app/assets/42211/18e3d6e7-32cc-4a48-ab47-a479aedfd63f

## Steps to QA

1. Go to deploy preview
2. Go to contributor profile
3. Click on repository under chart
4. Note the PRs list filters down to that repository
5. Click on repository again, or another repository
6. Note the filter changes

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

**Review by bdougie — APPROVED** [review]
Noticed something unrelated. Comments don't respect the width of the page due to long titles.

We should truncate those 

image

image

**Comment by brandonroberts** [comment]
Fixed the truncating with the issue comments on mobile

**Comment by bdougie** [comment]
> Fixed the truncating with the issue comments on mobile

It works on desktop, but not mobile. Fine to punt this work to a new PR to not distract from the original goal of this feature.

Screenshot 2024-06-24 at 11 09 00 AM
Screenshot 2024-06-24 at 11 08 48 AM

**Comment by brandonroberts** [comment]
Added some feedback when selected a repository, and tested the truncating issues on mobile on an Android phone in portrait and landscape. Will follow-up any additional changes in another PR.

image

**Review by nickytonline — COMMENTED** [review]
A quick test and things are working, but the first time I filter, I have to press a repo button twice. The video doesn't really show it well.

CleanShot 2024-07-03 at 16 54 09

**Review by nickytonline — APPROVED** [review]
This is good to go. Left one suggestion.

🚢

**Comment by brandonroberts** [comment]
Thanks! The CSS and repo selection issue is resolved

**Pull request merged**
