### PR TITLE
feat: added the StarSearch OG image

### LINKED ISSUE #3209: Feature: OG image for star search
### Current behavior

N/A

### Suggested solution

We want to create an OG image for StarSearch, to display when shared in social media / chat platforms

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Adds the OG image for the StarSearch page.

## Related Tickets & Documents

Closes #3209

## Mobile & Desktop Screenshots/Recordings

CleanShot 2024-04-18 at 10 32 22@2x

## Steps to QA

1. Ensure you're logged in and a part of the StarSearch feature flag cohort.
2. Go to `/star-search`
3. Inspect in the devtools and notice the appropriate meta tags.

CleanShot 2024-04-18 at 10 34 47@2x

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [x] Tier 3
- [ ] Tier 4

### CODE REVIEW

**Comment by isabensusan** [comment]
before approving, I'd love to get @bdougie 's eyes on this!

**Review by isabensusan — APPROVED** [review]
LGTM!

**Comment by bdougie** [comment]
> before approving, I'd love to get @bdougie 's eyes on this!

Card looks good, not sure if its meant to work in a preview but curious if that is because of the current 404 redirect.

Screen Shot 2024-04-18 at 11 00 44 AM

**Comment by nickytonline** [comment]
> > before approving, I'd love to get @bdougie 's eyes on this!
> 
> 
> 
> Card looks good, not sure if its meant to work in a preview but curious if that is because of the current 404 redirect.
> 
> 
> 
> Screen Shot 2024-04-18 at 11 00 44 AM
> 
> 
> 
> 

Yeah, it's because of the feature flag.

**Review by bdougie — APPROVED** [review]
🚀🚀🚀

**Pull request merged**
