### PR TITLE
fix: contributors not found message in contributors table no longer displays &apos;

### PR DESCRIPTION
**Pull request by Arol15**
## Description

This PR replaces HTML entity `&apos;` with the raw apostrophe character (').
Closes: https://github.com/open-sauced/app/issues/2426

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [X] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Mobile & Desktop Screenshots/Recordings

Screenshot of the message stating that there are no contributors

## Steps to QA

1. Go to `Insights` in the Navbar; 
2. Create a new Insight; 
3. Give it a name and add a repo (I used one of my repos)
4. Go to `Contributors` tab.

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

gif

### CODE REVIEW

**Comment by nickytonline** [comment]
The fix looks good @Arol15! Please don't hesitate to set it to ready for review!

CleanShot 2024-01-07 at 21 40 47

**Review by nickytonline — APPROVED** [review]
Thanks for the fix @Arol15! :shipit:

**Comment by Arol15** [comment]
Even though I've always used the raw apostrophe character in HTML, I was expecting that at least HTML entity  number`$#39;` would work but it didn't. Can't find a good explanation anywhere.

**Comment by Arol15** [comment]
> Thanks for the fix @Arol15! :shipit:

Thanks so much for the opportunity, @nickytonline!

**Comment by nickytonline** [comment]
> Even though I've always used the raw apostrophe character in HTML, I was expecting that at least HTML entity number`$#39;` would work but it didn't. Can't find a good explanation anywhere.

It's because you can only insert HTML entities in literal text in JSX. See https://shripadk.github.io/react/docs/jsx-gotchas.html#html-entities

**Pull request merged**
