### PR TITLE
fix: now the Dev Card share buttons appear on all screen sizes

### LINKED ISSUE #3923: Bug:  Profile card are  not displayed correctly on all resolution
### Describe the bug

Social  buttons  on MBA firefox  are hidden   resolution of :1470 x 755  
image

### Steps to reproduce

go to  https://app.opensauced.pizza/u/<name>/card 
 test with different screen high / width 
 on the screeshot  ex: 1470 x 755

### PR DESCRIPTION
**Pull request by zeucapua**
## Description

CSS changes to the `/u/<username>/card` page to ensure users are able to see the socials buttons and create their own dev card buttons.

## Related Tickets & Documents

Closes #3923 

## Mobile & Desktop Screenshots/Recordings
**BEFORE**

https://github.com/user-attachments/assets/c0c26468-d8a2-413d-a0cf-30aa0a58e8cd

**AFTER**

https://github.com/user-attachments/assets/38a0d203-c4a0-4369-8686-197551965688

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

**Review by nickytonline — COMMENTED** [review]
Thanks for this @zeucapua! They're visible on all the screen sizes I had open in Polypane.

The only thing I'm unsure of is the X button looks smaller, but I think it might be an optical illusion because my guides appear to line up.

CleanShot 2024-08-13 at 15 03 50

Maybe the thin light border you have on the LinkedIn button would fix that. Thoughts @isabensusan?

**Review by isabensusan — CHANGES_REQUESTED** [review]
like @nickytonline mentioned, the buttons look like they are different sizes. In theory they are both 40x40, but the border makes the X one look smaller. The inner social icons are also different sizes so it looks a bit wonky 

Played around with it for a sec, these two changes make it look better:
- make the border on the icons  `rgba(255,255,255, .3)` (instead of .2) it makes it look more leveled
- change the X icon size to 14x14 to match linkedin's size 

image

**Review by nickytonline — CHANGES_REQUESTED** [review]
I tested on Safari and the social buttons don't appear. Firefox and Chromium are fine though.

CleanShot 2024-08-13 at 15 43 29

Also, on my iPhone, the social buttons don't appear either.

image

**Comment by nickytonline** [comment]
Look like it works on Safari now on Mac.

 
CleanShot 2024-08-14 at 13 24 18@2x

It works on Safari iOS now as well, but it'd be good to add a bit of spacing above the social share icons.

IMG_6BED90216B0D-1

**Comment by zeucapua** [comment]
It should be better now @nickytonline 

image

**Review by nickytonline — APPROVED** [review]
Looks good on Safari iOS now! 🚢

**Review by brandonroberts — APPROVED** [review]

**Review by isabensusan — APPROVED** [review]
looks good!

**Pull request merged**
