### PR TITLE
fix: styling repo pages layout

### LINKED ISSUE #3387: Bug: Fix chart bleeding on repository page
I'd say it's good to merge, but it'd be great to get a follow up PR to fix the chart bleeding
image

_Originally posted by @isabensusan in https://github.com/open-sauced/app/pull/3373#pullrequestreview-2057996834_

### LINKED ISSUE #3388: Bug: Sizing issues with AvatarHoverCard avatar image
I've sorted the avatar resizing issue @bdougie with a temporary fix. It appears to be an issue with the avatar hover card component.

CleanShot 2024-05-15 at 09 05 06

_Originally posted by @nickytonline in https://github.com/open-sauced/app/issues/3373#issuecomment-2112467775_

The hovercard in the DevProfile component resizes oddly, at least in the context of the LotteryFactorChart component.

https://github.com/open-sauced/app/blob/ccc230d6d51189ad5ca31fe86432bc79063d740f/components/molecules/DevProfile/dev-profile.tsx#L29

### LINKED ISSUE #3397: Bug: workspace sidebar disappears for repo pages' contributors tab
### Describe the bug

Repo pages have two tabs: the Overview, and the Contributors tabs. The former has the sidebar and padding that the latter doesn't. They should both have the sidebar to make sure the page is consistent.

Overview
image

Contributors tab
image

### Steps to reproduce

1. Go to any repo page
2. Check that the overview has the workspace sidebar
3. See that going to the contributors tab does NOT have it

### PR DESCRIPTION
**Pull request by zeucapua**
## Description

Fixes and styling changes throughout the repo pages. In collaboration with @isabensusan, the changes include:
- [x] Making the `AvatarHoverCard` images for the `LotteryFactorChart` smaller
- [x] Implements `WorkspaceLayout` to the 'contributors' tab for padding consistency and sidebar
- [x] Make `ContributorsChart` height fixed 
- [x] New designs for chart tooltips
- [x] Text sizing changes throughout the cards
- [x] Padding changes throughout the cards
- [x] Color changes throughout the cards

## Related Tickets & Documents

Closes #3397 
Closes #3388 
Closes #3387 

## Mobile & Desktop Screenshots/Recordings
**`LotteryFactorChart` with smaller avatars**
image

**Contributors tab now has `WorkspaceLayout`**
image

**Issues & PR Charts (with `Open` and `Closed/Merged` colors)**
Screenshot 2024-05-15 at 8 50 06 PM
Screenshot 2024-05-15 at 8 49 30 PM

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [x] Tier 3
- [ ] Tier 4

## [optional] What gif best describes this PR or how it makes you feel?
steal-my-style-gucci-mane-gif

### CODE REVIEW

**Review by bdougie — CHANGES_REQUESTED** [review]
Weird height for the first card on mobile.

image

**Review by bdougie — APPROVED** [review]
🚀🚀🚀

**Review by brandonroberts — APPROVED** [review]
🗂️

**Review by nickytonline — APPROVED** [review]
Tested on a bunch of screens and looks great! 🚢 


https://github.com/open-sauced/app/assets/833231/6f2943d6-07ae-481e-955d-bfc49c68ad10

**Pull request merged**
