### PR TITLE
feat: replace dashboard scatterplot chart with repositories table

### LINKED ISSUE #1813: Feature: Insights Page - Dashboard Tab swap Contributor Distribution chart with repo table
### Type of feature

🍕 Feature

### Current behavior

The Dashboard page on our Insights Pages isn't adding as much value as we want. The Dashboard tab is the first thing users see, but it can be a confusing experience, specially around the Contributor Chart.

image

### Suggested solution

In the medium term, we want to do a deeper revamp of this page, but in the meantime we want to introduce quick changes to  improve the value add for the page.

### Goal
- On the Dashboard Tab:  change the Contributor Chart and replace it with the Repositories table on the Repositories Tab
- Remove the repositories Tab

If there's a chance to get this swap in next week for launch, that'd be amazing.

### Mockup
this is a quick and dirty concept, so if you see any issues with it, pls drop a comment

image

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by OgDev-01**
## Description
This PR replaces the dashboard scatterplot chart in the tools page to repo table and removes the repositories tab from the tab list

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
closes #1813 

### Before 
image

### After
image

image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by isabensusan** [comment]
@OgDev-01  @bdougie 100% for this PR let's add an Activity tab and move the contribution chart there so we start adding more insights to this new tab in future releases.

I'll open a new Issue for this, but we can port some of the charts from the list feature, like the most active contributors chart, and integrate some of the info we get on the pizza-cli.

**Comment by OgDev-01** [comment]
> @OgDev-01 @bdougie 100% for this PR let's add an Activity tab and move the contribution chart there so we start adding more insights to this new tab in future releases.

Ok... i'll make a new `activity` tab to house the chart and add other charts in a seperate PR

**Comment by OgDev-01** [comment]
@bdougie  and @isabensusan, here we have it ✨ 
image

**Review by bdougie — APPROVED** [review]
This works. For future design @isabensusan it would be nice to have some summaries or a tool tip about what the user is looking at for each chart in the activity tab.

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
