### PR TITLE
feat: Add an underline to Repos text in a button

### LINKED ISSUE #2202: Bug: Cannot go back to previous repos graphs after clicking one graph in the Activity tab in the Lists
### Describe the bug

After clicking a repo's graph in the "Activity" tab in the Lists, I can't go back to the previous graphs. I need to refresh the page to do so.

### Screen Recording

OpenSauced Lists Refresh

### Suggestion

I found out through @nickytonline stream that we can go back by clicking the "Repos" word.
But I think this would be confusing for users as there is no indication.

Perhaps having a button with the text "back" or something like that would help.

### Steps to reproduce

1. Go to the Lists page.
2. Click any list.
3. Click "Activity" tab.
4. Click one of the repo stats on the right.
5. How to get back to the previous stats with all the repo? 

### Browsers

Chrome

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by adiati98**
## Description

This PR adds an underline to the "Repos" text in the button inside "Activity" tab on the Lists Page. The underline serves as an indicator that "Repos" text is clickable for user to go back to previous repos stats.
The `orange-500` is used as the default color of the underline and `light-slate-8` for the hover state.

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Closes #2202 

### Before

repos before

### After

underlined repos

### Screen Recording

underlined repos

## Steps to QA

In the local environment:

1. Go to http://localhost:3000/hub/lists
2. Click the "Activity" tab.
3. On the right card, the text "Repos" has an orange underline.
4. When hover over the text, the underline color changes to gray.

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

bambi holds breath GIF

### CODE REVIEW

**Comment by nickytonline** [comment]
Thanks for the pull request @adiati98! Underlining does bring attention to the Repos text (actually a button).

I think we need to get @open-sauced/design involved here as I imagine they'd like the headings to remain as is, so we could potentially have some sort of back button that makes it very clear there is a call to action (CTA) to return to the previous state.

**Comment by adiati98** [comment]
> Thanks for the pull request @adiati98! Underlining does bring attention to the Repos text (actually a button).
> 
> I think we need to get @open-sauced/design involved here as I imagine they'd like the headings to remain as is, so we could potentially have some sort of back button that makes it very clear there is a call to action (CTA) to return to the previous state.
> 
> 

Thanks for the info, @nickytonline ! I'll wait. 😊

I went for the underline as per conversation in the comment of issue #2202.

**Comment by isabensusan** [comment]
hey @adiati98 ! Again, thanks for your work and initiative :) Because this component is changing it's navigation behaviour, I came up with a few alternative designs for how to solve the issue this PR addresses (#2202). I'd love to hear your thoughts on it, thanks!

**Comment by isabensusan** [comment]
hey @adiati98 ! Again, thanks for your work and initiative :) Because this component is changing it's navigation behavior, this PR is unfortunately no longer needed. I posted a few alternative designs for how to solve this in the issue (#2202) and I'd love to hear your thoughts on them. I'll go ahead and close this PR for the time being, but thank you very much for your contribution nonetheless!

**Pull request closed without merging**
