### PR TITLE
feat: Added explanation of what users are seeing on list activity graph

### LINKED ISSUE #2270: Feature: add explanation of what users are seeing on list activity graph
### Type of feature

🍕 Feature

### Current behavior

It's not clear what the chart is representing. 

current activity chart

### Suggested solution

1. Add subtext below like we do for the Most Active Contributors chart

added subtext

You should be able to just add this below the heading:

```
<div class="text-sm text-slate-400 mb-4">Based on the number of PRs
</div>
```

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by devharsh2k4**
## Description

- Added  subtext below like we do for the Most Active Contributors chart

## Related Tickets & Documents
Fixes #2270 

## Mobile & Desktop Screenshots/Recordings

Screenshot from 2024-05-07 23-31-09

## Steps to QA
1.Go to Contributors TreeMap

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

**Comment by BekahHW** [comment]
Hey @devharsh2k4, looks like you need to fix some things. Take a look at [this ](https://github.com/open-sauced/app/pull/3328#pullrequestreview-2042505150) for more info.

**Comment by devharsh2k4** [comment]
Hey am unable to fix the workflow errors

**Comment by jpmcb** [comment]
cc @open-sauced/engineering let's have a look at this and clean up long standing PRs 🙏🏼

**Review by nickytonline — APPROVED** [review]
Thanks for the PR @devharsh2k4! 🚢

**Review by jpmcb — APPROVED** [review]

**Pull request merged**
