### PR TITLE
fix: repo filter query not filtering on page refresh (1610)

### LINKED ISSUE #1610: Bug: Highlights - Repo filter query params not filtering after page refresh
### Describe the bug

Repository filter should be working after a page refresh as well since the query params are still there.

[highlights-query-params-not-working.webm](https://github.com/open-sauced/app/assets/27003616/ddf13341-97d4-488d-8777-8b3b3cc9dfbc)

### Steps to reproduce

1. Go to /feed.
1. Select a repository filter. You will see the filtered posts now.
1. Refresh the page. Query param exists but the filtered posts and the filter highlight do not.

### Browsers

Chrome

### Additional context (Is this in dev or production?)

dev and production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by ThePiyushAggarwal**
## Description

Highlights - Repo filter query params not filtering on page refresh. The query params was not affecting the filters on page. Now, on page reload, it will select the repo present in the query param.

Fixes #1610 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1610 

## Mobile & Desktop Screenshots/Recordings

| Before | After |
| ---- | ---- |
| <video src="https://github.com/open-sauced/app/assets/27003616/ddf13341-97d4-488d-8777-8b3b3cc9dfbc" /> | <video src="https://github.com/open-sauced/app/assets/27003616/b179d8b0-d323-45ab-a44a-a6452826bd81" /> |

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by OgDev-01** [comment]
Hey @ThePiyushAggarwal, can you check to see what is causing a build error?

**Comment by ThePiyushAggarwal** [comment]
It is breaking because I haven't changed the storybook component related to the changes happened here. I have started work on it. Can you please let me know what is the use of `TooltipProvider` wrapper. It has been used in a lot of story components.

**Comment by ThePiyushAggarwal** [comment]
I have updated the component story. `ComponentStory` was deprecated so I have removed that and updated the story according to the [storybook docs] (https://storybook.js.org/docs/react/writing-stories/introduction#working-with-react-hooks)

[highlights-filters-card-story.webm](https://github.com/open-sauced/app/assets/27003616/8623d86d-2b4a-4429-8795-823fb0150dc2)

**Comment by OgDev-01** [comment]
>  Can you please let me know what is the use of TooltipProvider wrapper.

It is a wrapper around [radix-tooltip](https://www.radix-ui.com/themes/docs/components/tooltip#api-reference) (Tooltip.Root) which is currently used across the application

**Review by OgDev-01 — APPROVED** [review]
LGTM 🍕

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
