### PR TITLE
fix: removed connection tab on user profile page

### LINKED ISSUE #3141: Remove connections from profile
- Since we have no plans for the development of connections right now, I think we should remove the tab. 

image

### PR DESCRIPTION
**Pull request by beckyrich**
fix: #3141

## Description
This PR removes the "Connections" Tab from the user's profile page (Was unsure if this is considered a refactor or fix)

## Mobile & Desktop Screenshots/Recordings

I do not have a pro account with OpenSauced, so I was unable to view the "Connections" Tab on my profile page. See below:
Screenshot 2024-04-25 at 10 42 37 AM

I followed the directions of the file to edit and the file to remove. Once the changes were made, I ensured the profile page was still populating and here is the screenshot:
LocallyRunningAfterChanges

## Steps to QA

1. From OpenSauced homepage -> click on profile picture on top right corner -> from the dropdown menu, select {username}
2. Once on Profile Page, check the tabs on the right. They should read "Highlights", "Contributions", "Recommendations"
3. "Connections" tab should be gone on the Pro Accounts. Free tiers will not see this tab populated. (I found this in the docs, but now am unable to find where I read this. I can keep searching if needed. Especially if documentation needs to be edited)
4. I did notice in the repo that lines 114-117 were showing an error. I did not touch these lines since it was not in the instructions provided. But this error does not break the page. (https://github.com/open-sauced/app/blob/18d3b15f12a993d5bc8ce0061cd4a5520b72e846/components/organisms/ContributorProfileTab/contributor-profile-tab.tsx)

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

## [optional] What gif best describes this PR or how it makes you feel?

* Hoping I followed the directions correctly

### CODE REVIEW

**Comment by nickytonline** [comment]
@beckyrich, looks like there is one more spot that needsto be udpated as well.

```
10:33:37 AM: ./components/organisms/ContributorProfileTab/contributor-profile-tab.tsx:114:38
10:33:37 AM: Type error: This comparison appears to be unintentional because the types 'TabKey' and '"connections"' have no overlap.
10:33:37 AM:   112 |         "font-bold text-transparent bg-clip-text bg-gradient-to-r from-[#EA4600] to-[#EB9B00]",
10:33:37 AM:   113 |       user && user_name !== login && tab === "recommendations" && "hidden",
10:33:37 AM: > 114 |       user && user_name !== login && tab === "connections" && "hidden",
10:33:37 AM:       |                                      ^
10:33:37 AM:   115 |       !user && tab === "recommendations" && "hidden",
10:33:37 AM:   116 |       !user && tab === "connections" && "hidden",
10:33:37 AM:   117 |       !receive_collaboration && tab === "connections" && "hidden"
```
You just need to remove these lines

```diff
  const getTabTriggerClassName = (tab: TabKey): string => {
    return clsx(
      "data-[state=active]:border-sauced-orange shrink-0 data-[state=active]:border-b-2 text-lg",
      tab === "recommendations" &&
        "font-bold text-transparent bg-clip-text bg-gradient-to-r from-[#EA4600] to-[#EB9B00]",
      user && user_name !== login && tab === "recommendations" && "hidden",
-      user && user_name !== login && tab === "connections" && "hidden",
      !user && tab === "recommendations" && "hidden",
-      !user && tab === "connections" && "hidden",
-      !receive_collaboration && tab === "connections" && "hidden"
    );
  };
```

You can check once you've made those additional changes by running `npm run build`. It should build without any errors.

**Review by nickytonline — CHANGES_REQUESTED** [review]
@beckyrich, looks like there is one more spot that needs to be updated as well.

```
10:33:37 AM: ./components/organisms/ContributorProfileTab/contributor-profile-tab.tsx:114:38
10:33:37 AM: Type error: This comparison appears to be unintentional because the types 'TabKey' and '"connections"' have no overlap.
10:33:37 AM:   112 |         "font-bold text-transparent bg-clip-text bg-gradient-to-r from-[#EA4600] to-[#EB9B00]",
10:33:37 AM:   113 |       user && user_name !== login && tab === "recommendations" && "hidden",
10:33:37 AM: > 114 |       user && user_name !== login && tab === "connections" && "hidden",
10:33:37 AM:       |                                      ^
10:33:37 AM:   115 |       !user && tab === "recommendations" && "hidden",
10:33:37 AM:   116 |       !user && tab === "connections" && "hidden",
10:33:37 AM:   117 |       !receive_collaboration && tab === "connections" && "hidden"
```
You just need to remove these lines

```diff
  const getTabTriggerClassName = (tab: TabKey): string => {
    return clsx(
      "data-[state=active]:border-sauced-orange shrink-0 data-[state=active]:border-b-2 text-lg",
      tab === "recommendations" &&
        "font-bold text-transparent bg-clip-text bg-gradient-to-r from-[#EA4600] to-[#EB9B00]",
      user && user_name !== login && tab === "recommendations" && "hidden",
-      user && user_name !== login && tab === "connections" && "hidden",
      !user && tab === "recommendations" && "hidden",
-      !user && tab === "connections" && "hidden",
-      !receive_collaboration && tab === "connections" && "hidden"
    );
  };
```

You can check once you've made those additional changes by running `npm run build`. It should build without any errors.

**Comment by beckyrich** [comment]
Thank you @nickytonline. I just made the changes locally. Do I need to use `npm run push` again for the commit message before I push up the requested changes?

**Comment by nickytonline** [comment]
> Thank you @nickytonline. I just made the changes locally. Do I need to use `npm run push` again for the commit message before I push up the requested changes?

Yeah, you need to do `git push` once you've committed those changes, but I see you've got it pushed. 😎

**Review by nickytonline — APPROVED** [review]
Tested the deploy preview and it works great! Thanks @beckyrich!

:shipit: 

CleanShot 2024-04-29 at 11 07 38

**Review by brandonroberts — APPROVED** [review]
Nice work!

**Pull request merged**
