### PR TITLE
fix: made card view for lists contributors list uniform with rest of app

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

A small UI tweak to bring the lists Contributors List feature card view in line with the rest of the app.

**Before**

CleanShot 2023-09-29 at 16 23 48

**After**

CleanShot 2023-09-29 at 17 08 19

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Related to #1710 

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by isabensusan** [comment]
looking better already! can we:
-  make it 3 columns on the grid view
- get rid of table header on the grid view

I think that would make it match 100%


image

**Comment by nickytonline** [comment]
> looking better already! can we:
> 
> * make it 3 columns on the grid view
> * get rid of table header on the grid view
> 
> I think that would make it match 100% to what we have in the insights page:

Weird, I copied the same CSS for that view for the container of the cards. I'll see what's up for why it's not doing 3 per row.

On the insights grid view, the table headers are there, at least on the beta site. Or did I misunderstand your comment?

CleanShot 2023-09-29 at 16 43 23

**Comment by nickytonline** [comment]
> looking better already! can we:
> 
> * make it 3 columns on the grid view
> * get rid of table header on the grid view
> 
> I think that would make it match 100% to what we have in the insights page:
> 

Made the changes so should be all good now. I've updated the after pic in the description.

**Review by OgDev-01 — APPROVED** [review]
🍕

**Review by brandonroberts — APPROVED** [review]
🎓

**Pull request merged**
