### PR TITLE
fix: add support for blog highlight update

### LINKED ISSUE #1614: Feature: Cannot edit a blog post highlight
### Type of feature

🍕 Feature

### Current behavior

Error presented when trying to edit an existing Blog post highlight. 

Screen Shot 2023-08-25 at 4 59 53 PM

### Suggested solution

Allow type: blog-post to edit. 

updates this error message

https://github.com/open-sauced/app/blob/d289cb2792aa2093d38e10ca7274e25a38334689/components/molecules/ContributorHighlight/contributor-highlight-card.tsx#L241

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by OgDev-01**
## Description
This PR includes the following changes:
- Added support for updating blog highlights
- Added support for updating tagged repositories
- Updated the request payload.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
fixes #1614 

## Mobile & Desktop Screenshots/Recordings

image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by OgDev-01** [comment]
Updating highlights with tagged repos throws a `500` error from the API. cc: @brandonroberts

**Comment by OgDev-01** [comment]
Tried debugging using local instance of the API and got this message when i send a request to update the highlight
image

**Comment by OgDev-01** [comment]
While working on this PR, I've identified instances of duplicate code that can be removed and refactored for better code organization and maintainability. To keep the current PR focused and manageable, I have intentionally left these changes out for now.  

 I'll be opening a new pull request in the coming days specifically dedicated to addressing these duplicate code issues and performing the necessary refactoring.

**Review by jpmcb — APPROVED** [review]
Very nice!! I was able to update my blog post highlight:

Screenshot 2023-08-28 at 2 20 07 PM

**Review by brandonroberts — CHANGES_REQUESTED** [review]

**Review by bdougie — APPROVED** [review]

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
