### PR TITLE
fix: list header misalignment now properly aligned

### LINKED ISSUE #1940: Bug: List header is misaligned
### Describe the bug

The range filter overflow out of the layout

list-header

### Steps to reproduce

Goto https://app.opensauced.pizza/lists/5002552c-6116-4d60-91c4-7892988d8c61/activity

### Browsers

Chrome

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by OgDev-01**
## Description
This PR is a fix for the list header range filter overflow issue

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
fixes #1940

### Before
list-header

### After
image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by nickytonline** [comment]
There's still some scenarios as you drag that they do not stay aligned.

CleanShot 2023-10-18 at 11 20 52

CleanShot 2023-10-18 at 11 21 56

@isabensusan, as the screen gets smaller, are you OK with certain sizes not being aligned or would you always like the ends aligned? I'm guessing the latter?

**Comment by OgDev-01** [comment]
>  I'm guessing the latter?

Me too... I'll push a change that reflects the latter shortly 👍

**Comment by OgDev-01** [comment]
Looks much better now...
image

**Review by brandonroberts — APPROVED** [review]
📐

**Review by nickytonline — APPROVED** [review]
📐

**Pull request merged**
