### PR TITLE
feat: created the custom 500 page

### LINKED ISSUE #2819: Feature: Custom 500 error page
As a user of the OpenSauced application, I want to see a friendly general error page instead of a generic that isn't branded as it gives the impression the whole application is broken.

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Adds a custom 500 page to the project. I removed the DEV cards that the custom 404 page has because if there are issues with the site, we don't want the error page to crash.

I went with this copy. Feel free to slice and dice.

`uh oh! looks like there's an issue with the pizza oven`

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Closes #2819

## Mobile & Desktop Screenshots/Recordings

CleanShot 2024-03-18 at 18 55 50

## Steps to QA

1.  Go to this page which contains an invalid workspace ID in the URL, https://deploy-preview-2969--oss-insights.netlify.app/workspaces/332aaf7-55db-4c2b-9fde-f61604471e21
2. You get the custom 500 error page,

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by jpmcb — APPROVED** [review]
💯💯💯💯💯

**Comment by bdougie** [comment]
@nickytonline can we center the text since we won't have dev cards?

**Comment by nickytonline** [comment]
> @nickytonline can we center the text since we won't have dev cards?

Any preference for which one @open-sauced/engineering @isabensusan?

CleanShot 2024-03-18 at 18 56 02

CleanShot 2024-03-18 at 18 55 50

I'm kind of partial to the second one, but not a hill I need to die on. 😅

**Comment by bdougie** [comment]
> I'm kind of partial to the second one, but not a hill I need to die on. 😅

The second makes it clearer there is a 500 and the message stands out. Having it centered makes me automatically not pay attention to the "uh oh"

**Comment by nickytonline** [comment]
I pushed the second option for now. If we're good with that, I can go ahead and merge after approval.

**Pull request merged**
