### PR TITLE
feat: add Treemap chart prototype

### PR DESCRIPTION
**Pull request by foxyblocks**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by jpmcb** [comment]
@foxyblocks - are there other API endpoints needed for this? Or does https://github.com/open-sauced/api/pull/320 also work for this?

**Comment by foxyblocks** [comment]
> @foxyblocks - are there other API endpoints needed for this? Or does [open-sauced/api#320](https://github.com/open-sauced/api/pull/320) also work for this?

@jpmcb 

I need the API sketched out here https://github.com/open-sauced/app/issues/1701 under the **Contributions by Project section**

**Comment by jpmcb** [comment]
Cool beans, that's been implemented in my API pr 👏

**Comment by brandonroberts** [comment]
@foxyblocks is this ready to merge so it can be added to a page?

**Review by brandonroberts — APPROVED** [review]
Noting to merge this and fix forward any issues

**Comment by foxyblocks** [comment]
Alright, it needs some color work and some changes to support the 4 levels of the data structure

**Pull request merged**
