### PR TITLE
refactor: move [pageId] pages to dedicated /explore/topic route

### LINKED ISSUE #2600: Chore: Fix convoluted file routes
Currently we have some bizarre file routes in the application:

- pages/[userOrg]/[pageId]/[toolName].tsx
- [pageId]/[toolName].tsx

This causes several problems:
- it's confusing that there is a `pages` folder in the pages router folder
- the structure of these file base routes allow you to go to a page that should 404, but instead it results in an empty page with the title of a page that doesn't exist
- it's a source of confusion for anyone looking to work on pages that hit those confusing file-bsed routes

### PR DESCRIPTION
**Pull request by zeucapua**
## Description

Previously, when users go to the explore page, they are routed to `/[pageId]` where pageId is the topic given (eg 'javascript'). This meant we have a catchall at the top level that was causing issues in rendering error pages, as well as being organizationally confusing.

This PR will move routes under a *new* `/explore/topic` route, that way we can pave way for a catchall route for the repo pages since they are going to be under `/[org]/[repo]`, as outlined in #2961.

Implement additional changes to the `Navbar` and other components to link correctly to the new routes.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Closes #2600 

## Steps to QA

1. Go to explore page and note the new route
2. Check the navigation bar leads to the new route
3. Go through filters and topics to ensure they don't lead outside new route

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?
dechart-games-amelia-rose-blaire-gif

### CODE REVIEW

**Comment by bdougie** [comment]
@nickytonline can you make sure we have redirects for this change.

Not sure if we want to start adding a Netlify.toml or redirects file

**Review by nickytonline — COMMENTED** [review]
Took this for a test drive and all works well. I'm just wondering if there's any other spots in the app where we need to prefix these with `/explore/topic/`. I don't think there are.

**Comment by nickytonline** [comment]
> @nickytonline can you make sure we have redirects for this change.
> 
> Not sure if we want to start adding a Netlify.toml or redirects file

We can add redirects in the Next.js configuration or a Netlify redirects TOML.

We can't use a netlify.toml at the moment because of the way the deployments for Storybook and the app are configured. They're configured in the UI as we're not a true monorepo at the moment. I added a netlify.toml previously and the app deployed to the storybook site as well as the app site. I'll create an issue for that as there's a bit of cleanup there.

**Comment by nickytonline** [comment]
You can try this @zeucapua for the redirects in the next.config.js by exporting interests in

https://github.com/open-sauced/app/blob/009947eba290adbd8c6da180e6a9f4695b9e501d/lib/utils/getInterestOptions.ts#L1-L23

and then map over them to generate the redirects. It should work locally, but the real test is to see if it works in the deploy preview. I can look at this some more tomorrow my morning if not.

```typescript
  async redirects() {
    return [
      {
        source: "/user/:username/highlights",
        destination: "/user/:username?tab=highlights",
        permanent: true,
      },
      // more redirects
      {
        source: "/hub/insights",
        destination: "/",
        permanent: true,
      },
      // the secret sauce for redirects
      ...[interests].map((interest) => {
        return {
          source: `/${interest}/:path*`,
          destination: `/topic/explore/${interest}/:path*`,
          permanent: true,
        };
      }),
    ];
  },
};
```

**Review by nickytonline — APPROVED** [review]
🚢

**Review by jpmcb — APPROVED** [review]
🚢 :shipit:

**Pull request merged**
