### PR TITLE
feat: add contributor confidence to repository table

### LINKED ISSUE #4008: Feature: add contributor confidence to the repository table
### Suggested solution

We want to update the repository tables to include the Contributor Confidence score for each repository in a workspace or repository insight 
image

### PR DESCRIPTION
**Pull request by zeucapua**
## Description

Update the repository table shown on the workspace and explore pages with a new 'Contributor Confidence' column.

## Related Tickets & Documents

Closes #4008 

## Mobile & Desktop Screenshots/Recordings
image

## Steps to QA
1. Go to explore page or workspace
2. See the Contributor Confidence column
3. Ensure the row percentage is the same as the Contributor Confidence chart in the repository page

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [x] Tier 3
- [ ] Tier 4

### CODE REVIEW

**Review by nickytonline — COMMENTED** [review]
We should round contributor confidence. 

image

**Review by jpmcb — APPROVED** [review]

**Comment by zeucapua** [comment]
It's now rounded on mobile as well! 
image

**Review by nickytonline — APPROVED** [review]
:shipit:

**Comment by isabensusan** [comment]
Can we add the info icon like we do on for the OSCR with an explainer tooltip?
 
image

**Pull request merged**
