### PR TITLE
feat: implement 'Add to workspace' in repo pages

### LINKED ISSUE #3251: Feature: add CTA on repo pages to add to workspace / repo insight
### Current behavior

Right now the only action a user can do in a repo page is share a repo page.
image

### Suggested solution

We'd want to let users add repositories to a new workspace directly from a repo page

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by zeucapua**
## Description

Implements a button to allow a user from a repo page to add the current repo to one of their workspaces, or create one from scratch. Users who are not logged in are given a copy of the `WorkspaceWelcomeModal` and a CTA to connect with GitHub. Desktop users are shown a modal with a single select and a confirm button; mobile users are shown the same as a drawer.

## Related Tickets & Documents

Closes #3251 

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/app/assets/20603494/b283684e-d576-4d53-b1c2-fb23ad4677a8

## Steps to QA

1. Go to a repo page while NOT logged in
2. Check that you get a CTA to log in
3. Go to a repo page while logged in
4. Check that you can select between making a new workspace or an existing one
5. Either go through the creation process or go to the workspace you have selected and confirmed
6. Ensure that the repository added is indeed in the workspace.

## Tier (staff will fill in)

- [ ] Tier 1
- [x] Tier 2
- [ ] Tier 3
- [ ] Tier 4

## [optional] What gif best describes this PR or how it makes you feel?
reysync-roblox-gif

### CODE REVIEW

**Comment by bdougie** [comment]
This is beautiful on mobile. Love the use of the drawer image

I do question why the use is taken to /start onboarding screen and not a direct GitHub with. Going through the onboarding path did not take me to workspaces/new.

Could we instead use the workspace new path instead of taking folks through /start onboarding 

cc @brandonroberts since you worked on that and have more context.

**Comment by brandonroberts** [comment]
Yes,  you can go directly to `/workspaces/new` and pass `repo=[repoFullName]` as a query parameter. Then in the component, you can grab the repo and set the repos to that repo. We're doing something similar on that page already.

**Comment by nickytonline** [comment]
> Yes, you can go directly to `/workspaces/new` and pass `repo=[repoFullName]` as a query parameter. Then in the component, you can grab the repo and set the repos to that repo. We're doing something similar on that page already.

Yeah was just coming to say something similar or we can add a redirect for the login button on the modal. That's what I did for the waitlist.

**Comment by nickytonline** [comment]
This looks and works great @zeucapua. One suggestion and would love @isabensusan's feedback here too, but I think a full width confirm button would look nicer.

**Before**

CleanShot 2024-05-01 at 09 33 28

**After**

CleanShot 2024-05-01 at 09 32 12

**Comment by zeucapua** [comment]
It should now redirect to `/workspaces/new` with the repo when a user logs in with the "Connect with GitHub" CTA on the modal/drawer!

**Review by bdougie — APPROVED** [review]

**Review by jpmcb — COMMENTED** [review]
Really solid work: well done!

---

I notice when mousing over some of my workspaces, the highlighting gets sort of "stuck" and a few of the workspaces don't remove the focus state:

Screenshot 2024-05-01 at 11 35 01 AM

I also notice that my "really long" workspace name (notice towards the bottom) doesn't fill up much of the box. Neither here are blocking, but should be noted/fixed forward.

---

I was abit confused after hitting the "add" button ... since it didn't seem to do anything. And then a few seconds latter, the modal closed and I saw the "confirmed" popup. I wonder if we should show a loading state?

**Review by nickytonline — APPROVED** [review]
Thanks for making the changes! :shipit:

**Review by nickytonline — APPROVED** [review]
Thanks for making the changes! :shipit:

**Pull request merged**
