### PR TITLE
chore: replace collaborate with connect

### LINKED ISSUE #1970: fix: change collaborate to connect
We've rename collaboration to connections. 

Let's make sure the text is updated throughout the app. 

Currently, if you click the three-dot dropdown in your profile, it shows share and collaborate.

Let's make sure that gets updated and search for any other references to collaborate or collaborations and make the update.

image

### PR DESCRIPTION
**Pull request by itskish0re**
## Description
Changed the word "collaborate" to "connect" from all revelent places in the code.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [X] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
Fixes #1970

#### Before
image

#### After
image

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [X] 🙅 no documentation needed

### CODE REVIEW

**Review by RitaDee — COMMENTED** [review]
@itskish0re, you need to fix the title for the workflow to pass.

chore: replace collaborate with connect.

**Review by nickytonline — APPROVED** [review]
Thanks @RitaDee!

**Comment by RitaDee** [comment]
LGTM 🍕

**Comment by RitaDee** [comment]
> Thanks @RitaDee!

You’re welcome.

**Review by OgDev-01 — APPROVED** [review]
Thanks for the quick fix @itskish0re 🍕🍕

**Pull request merged**
