### PR TITLE
fix: long names

### LINKED ISSUE #1518: bug: Long names in top contributors mess up spacing on small screens.
bug: Long names in top contributors mess up spacing on small screens.

I noticed a weird side effect. I did see this get reported elsewhere. OK to have it addressed on another PR

My suggestion is to add truncation when the width is adjusted.

Screen Shot 2023-08-07 at 4 46 56 PM

_Originally posted by @bdougie in https://github.com/open-sauced/insights/issues/1516#issuecomment-1668759551_

### PR DESCRIPTION
**Pull request by RitaDee**
## Description

On smaller screens, a formatting issue arises within the "Top Contributors" section where long names disrupt the intended spacing, leading to an unsightly visual presentation. This bug undermines the overall user experience and aesthetic appeal of the application. This PR implements a responsive fix that ensures the proper alignment and spacing of contributor names, even when they are exceptionally long. 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1518 
## Mobile & Desktop Screenshots/Recordings

Before:

image

After:

https://github.com/open-sauced/insights/assets/106407013/22ca0961-4760-43c7-9ae6-abf7e027dc4b

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by RitaDee** [comment]
@bdougie, thanks a lot for today. 

@brandonroberts, it is ready for review.

Thank you all for today.

**Review by bdougie — APPROVED** [review]
Amazing!

**Review by NsdHSO — APPROVED** [review]
LGTM

**Review by brandonroberts — APPROVED** [review]
🍕

**Pull request merged**
