### PR TITLE
feat: add support for blogpost from generic platforms 

### LINKED ISSUE #1656: Feature: Allow users to post blogs from (RSS) multiple platforms
### Type of feature

🍕 Feature

### Current behavior

I tried posting my Hashnode blog post as a highlight but I received this message:
A screenshot of the result after I tried to post my article from Hashnode
This can be a turn-off for people who either don't use Dev.to or use other platforms alongside with it. 

### Suggested solution

Create some sort of code to allow blog posts from all platforms to be shared as highlights.

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by babblebey**
## Description

This Pull Request adds support for blogpost from other platforms in highlights. Leverages the `open-graph` node library, fetches the open graph data from the given blogpost `url` provided as `highlightLink` and uses the `image` property on the data as the `blogspot` highlight type social image when posting new highlights.

### Implementation Caveat 🤔 

- **No Support for Auto-Summarize**
 
This is specifically because in order to consume the auto-summarize function, the `generateDevToBlogHighlightSummary` (which is an auto-summary function for the `DevTo` blogpost) takes two(2) arguments namely the `blogTitle` and `blogMarkdown` (which is the blog post content). This implementation uses the `open-graph` to fetch meta data which satisfies only the `blogTitle`. There isn't a straight-forward or consistent or lightweight implementation (aside scrapping 🤫) to access the body content of this generic blog post. 

In the absence of the body content of this blog post, I hence settled for implementing a notice of `no-support for auto-summarize` for the `auto-summarize` feature on the generic blog post for now.

### Changes Made

- Refactored all `DevTo` related components and functions, to reflect `DevTo***` in its naming to make them more specific to `dev.to` blog post type
- Added a `fetchOGData` endpoint in the `/api` route which fetches `open-graph` data for specified url
```js
const og = require("open-graph");

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  const url = req.query.url;
  if (req.method === "GET") {
    og(url, (error: any, meta: {}) => {
      if (!error) {
        res.status(200).json({ response: meta });
      } else {
        res.status(200).json({ response: {} });
      }
    });
  }
}

```
- Added `GenericBlogOpenGraphImage` component which consumes the `fetchOGData` endpoint, builds and sends response image as returned component node.
- Added a `isValidURL` helper function to validate url input in the `highlightLink` field on highlight input form.
- Integrated the the `GenericBlogOpenGraphImage` component and `isValidURL` function in appropriate base components.
- Fixed edge case where repository are automatically tagged to blogposts without intentionally tagged repos, resulting in repositories url that do not exist.
- Implemented a `toast` in attempt to add notification for `auto-summarize` not being supported for blogpost from these generic platform because we do not currently have any means of accessing the exact blog post body content which is one of the required parameter/content for auto-summarize.

```js
const handleGenerateHighlightSummary = async () => {
  ....

  // 🍕🍕🍕 NOTICE HERE 🍕🍕🍕 
  if (highlightLink && (!highlightLink.includes("github.com") || !highlightLink.includes("dev.to"))) {
    toast({
      description: "Auto-Summarize not supported for current link!",
      title: "Oops!",
      variant: "warning",
    });
    return;
  }

  ....
};
```

🍕

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1656 

## Mobile & Desktop Screenshots/Recordings

**Writing a (Generic) Blogpost highlight type**

[screencast-localhost_3000-2023.10.15-04_00_37.webm](https://github.com/open-sauced/app/assets/25631971/94e8879f-3f88-427d-93a7-c08c9fe2765d)

**Blogpost (without tagged repos)**

image

**Blogpost (with tagged repos)**

image

**Demo: Toast for `Not Supported Message for Auto-Summarize`**

screencast-localhost_3000-2023 10 15-02_54_52

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

This PR adds a new package `open-graph`

## [optional] What gif best describes this PR or how it makes you feel?

giphy (1)

### CODE REVIEW

**Comment by BekahHW** [comment]
Hey @babblebey I think once you get those conflicts resolved we should be ready to get this merged in! Let us know if you have any questions.

**Comment by nickytonline** [comment]
> Done @BekahHW 😁
> 
> I experienced a blocker which I addressed, and I feel obliged to state though 🤔
> 
> After pulling the beta branch and resolving conflicts in `npm-shrinkwrap`, I attempted to commit the changes but encountered an error in the `pre-commit`'s `eslint --cache --fix` script related to `netlify/edge-functions/workspaces-card.tsx` not being included in the `tsconfig.json` file.
> 
> The error message I found in the command out's `git-error-*****` file was:
> 
> ```
> ✖ eslint --cache --fix:
> 
> C:\Users\User\Documents\Projects\open-source\insights\netlify\edge-functions\workspaces-card.tsx
>   0:0  error  Parsing error: ESLint was configured to run on `<tsconfigRootDir>/netlify\edge-functions\workspaces-card.tsx` using `parserOptions.project`: <tsconfigRootDir>/tsconfig.json
> However, that TSConfig does not include this file. Either:
> - Change ESLint's list of included files to not include this file
> - Change that TSConfig to include this file
> - Create a new TSConfig that includes this file and include it in your parserOptions.project
> See the typescript-eslint docs for more info: https://typescript-eslint.io/linting/troubleshooting#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file
> ```
> 
> As a workaround, I added `"netlify/edge-functions/workspaces-card.tsx"` to the `tsconfig.include` array and removed `"netlify/edge-functions"` from the `tsconfig.exclude` array. See below...
> 
> ```json
> {
>   "compilerOptions": {
>     [.......]
>   },
>   "include": [
>     "next-env.d.ts",
>     "next-types.d.ts",
>     "**/*.ts",
>     "**/*.tsx",
>     "components/molecules/DevToSocialImage",
>     "next.config.js",
>     "netlify/edge-functions/workspaces-card.tsx" // 👈 ADDED This 
>   ],
>   "exclude": ["node_modules"] // 👈 MODIFIED This: ["node_modules", "netlify/edge-functions"]
> }
> ```
> 
> This allowed me to successfully commit the changes. However, I have intentionally not committed the change to the `tsconfig.json` file as it is only a workaround and I'd want to understand reasoning behind the original setup before making any permanent changes.

I'm not sure why the original setup was like that aside from Edge functions run in Deno and Deno has it's own formatter. Feel free to open a separate issue about this. I think it's probably fine to do what you did, but best to track it in an issue.

**Comment by bdougie** [comment]
> I had a thought about this PR some days ago... Understanding the concerns of potential spam with links posted in Highlights (reason we've taken this long to merge this feature 😉)
> 

This is valid, but we have a check in place for anything inappropriate to flags us internally. We shipped that while waiting on this PR. We also have not really seen the wide spread adoption of highlights, so any further optimization for spam would be premature. Let's see if people actually link a blog post other than DEV. 

Also point out the last DEV posting highlight was 22 days ago and it was @BekahHW.

Valid concerns, but we kind need to ship to learn here. 

> I thought that maybe we can make up a list of supported blogs with their URL tracked in a constant value (like `supportedBlog` constant of type `array` or map or anything that's not gonna be time complex at search).... We can always look to check within this list of supported blogs to validate a link posted in highlights.
> 

This sounds like maintenance that is not needed yet, see below. Start small by checking the users personal website on their profile. 

> In regard Blog post from my custom website, I heard @bdougie suggest adding support for `website` on user profile one-time, and that we can surely check against this `url` too as supported blogs. 🤔
> 
> I don't know what the resolution is to merge this now, I just thought to put this one out haha.

I am fine with either, merge now and follow up to limit to profile websites next, while building up a list of blog platforms folks want to use. But the goal is showing contributions and we have an education issue to solve first. 

Can we get users to use this feature and submit blog posts?

**Comment by brandonroberts** [comment]
@babblebey works pretty well! One issue I ran into is when I paste the URL from dev.to, it still gives a validation error. If I update the input, the validation error goes away.

image

**Comment by babblebey** [comment]
> works pretty well! One issue I ran into is when I paste the URL from dev.to, it still gives a validation error. If I update the input, the validation error goes away.

Ha @brandonroberts, this is in fact the case for any link (including PR link, Issue link etc..) posted as highlights link... 

I found this to be the issue....

```jsx
<TextInput
  id="highlight-link-input"
  state={isHighlightURLValid ? "valid" : "invalid"}
  className={clsx("text-sm shadow-none h-10 flex-none", errorMsg ? "border-red-500" : "")}
  value={highlightLink}
  handleChange={(value) => {
    setHighlightLink(value);
    checkIfHighlightLinkIsValid(value); // 👈👈👈👈👈 The Culprit
  }}
  placeholder="Paste the URL to your PR, Issue, or Dev.to blog post."
/>
```

That isn't letting the validation run on reactivity (if i've said that well haha 😆), its not letting the validation occur when a value is perceived as changed in the `highlightLink` state... so, I'll address this by moving the `checkIfHighlightLinkIsValid(value)` function execution to a `useEffect` that runs with `highlightLink` as it deps i.e. only when its value changes.

😉

**Comment by brandonroberts** [comment]
@babblebey ok cool. I didn't get the same issue with pasting a PR link. This is from beta

image

**Comment by babblebey** [comment]
Haha, I wonder why though 🤔, It went on invalidated initially in localhost and validate when  you update input

image

But, works as expected now though.

[screencast-localhost_3000-2024.04.17-18_44_33.webm](https://github.com/open-sauced/app/assets/25631971/b72bca8a-195f-468b-adcc-2ae87b5d5f94)

🍕

**Review by BekahHW — APPROVED** [review]

**Review by brandonroberts — APPROVED** [review]
Thanks! You can resolve the merge conflicts and we'll get it merged

**Comment by brandonroberts** [comment]
@babblebey good to resolve those and we'll merge it

**Comment by babblebey** [comment]
🍕

**Comment by brandonroberts** [comment]
Thanks @babblebey!

**Pull request merged**
