### PR TITLE
feat: uniform styling for Repo page charts

### LINKED ISSUE #3303: Feature: uniform styling for Repo page charts
### Current behavior

Change the styling for the stars and forks to be in line with the new contributors chart.

Current charts:
image

Target styling:
image

### Suggested solution

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by zeucapua**
## Description

Implements styling changes for repo pages charts
- move Stars and Forks number stats from `RepositoryStatCards` to the charts
- move `StarsChart` and `ForksChart` side by side 
- `ContributorChart` above Stars and Forks

## Related Tickets & Documents

Closes #3303 

## Mobile & Desktop Screenshots/Recordings
image

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [x] Tier 3
- [ ] Tier 4

## [optional] What gif best describes this PR or how it makes you feel?
family-guy-dancing-gif

### CODE REVIEW

**Comment by isabensusan** [comment]
Chatted with @zeucapua this morning, here's the recap:
- Move metrics from the stars metric card to the star chart like so: 
image
- Make container width wider (same as the explore page)
- Make stars and forks chart 50% width and put them in the same row + move the contributor chart above them
image

**Comment by isabensusan** [comment]
It should look something like this:
image

**Review by nickytonline — APPROVED** [review]
Tested on multiple screens and works great!

CleanShot 2024-05-06 at 16 05 41

CleanShot 2024-05-06 at 16 04 53

**Review by jpmcb — APPROVED** [review]
🥇

**Pull request merged**
