### PR TITLE
feat: make user avatar on feed link to user profile

### LINKED ISSUE #1981: Feature: Make user avatar on feed link to user profile
### Type of feature

🍕 Feature

### Current behavior

On the Highlights feed (app.opensauced.pizza/feed) on the user card only the user handle (ie @isabensusan) links to the user profile, but the expected interaction would be for the user photo to link to the profile too.

image

### Suggested solution

Make both the handle and  the  user photo link to the user's profile.

image

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by itskish0re**
## Description

Added link to the avatar. Now user profile can be accesed by either clicking on the profile photo or userid.

## What type of PR is this? (check all applicable)

- [X] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
Fixes #1981

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/app/assets/59221338/1afc335b-432b-4a87-9ecc-493537882fe4

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [X] 🙅 no documentation needed

### CODE REVIEW

**Comment by RitaDee** [comment]
@itskish0re, kindly read through the [contributing guide](https://docs.opensauced.pizza/contributing/introduction-to-contributing/). I noticed you opened a PR to an issue not assigned to you.

**Comment by itskish0re** [comment]
@RitaDee, How to assign the ticket to myself?

**Comment by RitaDee** [comment]
> @RitaDee, How to assign the ticket to myself?

You are doing it correctly, but someone already assigned the ticket to himself before you.

image

**Comment by nickytonline** [comment]
I'm going to go ahead and close this as [someone is already assigned to this issue](https://github.com/open-sauced/app/issues/1981#issuecomment-1773788936).

As @RitaDee and others have mentioned, please read the [contributing guide](https://github.com/open-sauced/.github/blob/HEAD/CONTRIBUTING.md) before beginning any work on an issue.

**Pull request closed without merging**
