### PR TITLE
fix: Contributor Confidence styling

### LINKED ISSUE #3558: Update gauge text styling in contributor confidence
@zeucapua  styling wise, I'd love to see the number inside the gauge be bigger and placed higher. Could be a follow up PR too :)

image

_Originally posted by @isabensusan in https://github.com/open-sauced/app/issues/3545#issuecomment-2161368933_

### LINKED ISSUE #3564: Bug: Contributor Confidence should be a half circle, not a full one
Looknig at a project with high contributor confidence, notice the chart is a full circle. It should be a half circle.

CleanShot 2024-06-13 at 16 32 01

### LINKED ISSUE #3571: Bug: Contributor Confidence description spill on mobile
### Describe the bug

Text is too large for mobile view, making it spill over the card on the page.
Screenshot 2024-06-17 at 12 50 47

### Steps to reproduce

1. Go to any repo page
2. See the Contributor Confidence chart on mobile view

### PR DESCRIPTION
**Pull request by zeucapua**
## Description

Various styling fixes and changes to the `ContributorConfidenceChart` component
- Force half circle for confidence percentages above 50%
- Gauge percentage label styling changes
- Description text sizing for mobile
- Change the `Learn More` link to the Contributor Confidence docs

## Related Tickets & Documents

Closes #3564 
Closes #3558 
Closes #3571

## Mobile & Desktop Screenshots/Recordings

Various sizes (large, medium, small screens respectively)
image
image
image

## Steps to QA

1. Go to any repo page
2. Check the Contributor Confidence chart in various screen sizes

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

## [optional] What gif best describes this PR or how it makes you feel?

season-4-swag-gif-by-rick-and-morty

### CODE REVIEW

**Comment by nickytonline** [comment]
This renders well, but given it's a half circle, I think we'd need to have the percentages visually halved (not the percentage text).

CleanShot 2024-06-17 at 16 23 04

**Comment by bdougie** [comment]
> I think we'd need to have the percentages visually halved

I think I understand I don't @nickytonline. Can you clarify

**Comment by nickytonline** [comment]
> > I think we'd need to have the percentages visually halved
> 
> I think I understand I don't @nickytonline. Can you clarify?

For example, looking at 40% in this screenshot, it looks like it's 80% of the half gauge instead of 40%

CleanShot 2024-06-17 at 16 39 30

**Comment by zeucapua** [comment]
I thought we decided this in the original contributor confidence PR, see @jpmcb's comment here: https://github.com/open-sauced/app/pull/3545#discussion_r1633987143

**Comment by nickytonline** [comment]
> > looking at 40% in this screenshot, it looks like it's 80% of the half gauge instead of 40%
> 
> This is an explicit design decision we made: i.e., 40% is about as high as you'd ever see. Just like with a speed gauge, or a RPM gauge on an engine, the "sweet" range is really only like 30-50% of the actual range of the gauge. You'd never want your RPM gauge on an engine to go all the way to 100%, that would be a problem.
> 
> 40% in this context is "green" and would be a desired range.

OK, all good. Didn't realize that was decided @zeucapua and @jpmcb. I'll go ahead and approve.

**Review by nickytonline — APPROVED** [review]

**Review by jpmcb — APPROVED** [review]
🚀 🍇 🚀 🍇 🚀 🍇 🚀 🍇

**Review by brandonroberts — APPROVED** [review]

**Comment by bdougie** [comment]
I am on BART and missed a lot of this conversation.

What is missing in this context is 40% of the people who engage with the repo make contributions.

That is what confidence identifies and this will make more sense when we ship more of the story. But for now let's ship to learn.

**Review by bdougie — APPROVED** [review]

**Pull request merged**
