### PR TITLE
feat: added hacktoberfest icon in user settings

### PR DESCRIPTION
**Pull request by heysagnik**
## Description
 
This PR just enhanced the visuals by adding an icon. 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
#1770 

## Mobile & Desktop Screenshots/Recordings

image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by takanome-dev** [comment]
Hey @heysagnik, can you add a before and after screenshots?
Also, the following linting erros failed the build

**Comment by heysagnik** [comment]
@takanome-dev I have done the changes asked for

**Review by OgDev-01 — APPROVED** [review]
Thanks for taking this on @heysagnik 👏👏👏

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
Thanks @heysagnik!

**Pull request merged**
