### PR TITLE
feat: implement 'no interest' state to `/explore` Recommendation Section

### LINKED ISSUE #4124: Feature: Add State for No Interests Selected on the Explore page
## Current

If a user has not selected any interests, their recommended section currently looks like this.

image

## Proposed Solution

Let's create a state for no interests selected that gives the user an opportunity to select their interests. We have this on the user settings and the user profile also offers options to choose from. We could have something like, "Choose your interests, so we can recommend projects you'd like."

image

### PR DESCRIPTION
**Pull request by zeucapua**
## Description

If a user has no interests set, they will not get recommendations. The `/explore` "Recommended For You" section will instead show the list of interests for the user to pick from. On update/refresh, the page should start showing recommendations.

## Related Tickets & Documents

Closes #4124 

## Mobile & Desktop Screenshots/Recordings
image

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

## [optional] What gif best describes this PR or how it makes you feel?
larry-david-curb-your-enthusiasm-gif

### CODE REVIEW

**Review by jpmcb — COMMENTED** [review]
After I log in, I get the "Connect with GitHub" view:

Screenshot 2024-10-01 at 11 36 45 AM

and then a few seconds latter, it flips to the recommended view: can we have a loading state instead?

**Comment by nickytonline** [comment]
I get the login screen as well, but also no workspaces are loaded or trending repos.

CleanShot 2024-10-01 at 13 14 35@2x

Discover Workspaces seems off as well. The heading is all scrunched on larger screens whereas the other headings are not when the windows is fully maximized on my 14" MBP.

CleanShot 2024-10-01 at 13 17 19

**Comment by zeucapua** [comment]
> After I log in, I get the "Connect with GitHub" view:
> 
> Screenshot 2024-10-01 at 11 36 45 AM
>
> and then a few seconds latter, it flips to the recommended view: can we have a loading state instead?

There should be a loading state, but it's weird it's not showing up. I assume it's cause the `useSession` hook takes a minute so it thinks that a user isn't logged in. Let me change things around to fix.

**Comment by zeucapua** [comment]
> I get the login screen as well, but also no workspaces are loaded or trending repos.
> 
> CleanShot 2024-10-01 at 13 14 35@2x
> 
> Discover Workspaces seems off as well. The heading is all scrunched on larger screens whereas the other headings are not when the windows is fully maximized on my 14" MBP.
> 
> CleanShot 2024-10-01 at 13 17 19 [ CleanShot 2024-10-01 at 13 17 19 ](https://private-user-images.githubusercontent.com/833231/372637291-32420844-de2d-468f-abc2-27cdf8262f30.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MjA3NjYsIm5iZiI6MTcyNzgyMDQ2NiwicGF0aCI6Ii84MzMyMzEvMzcyNjM3MjkxLTMyNDIwODQ0LWRlMmQtNDY4Zi1hYmMyLTI3Y2RmODI2MmYzMC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQyMjA3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2MwMGJjODM4MmM2ZDI0MjFjOTA5YjQyOGIxNmM0MDc0NTJhYzhmMzZhYTE1OWRmNWY1ODFhM2YyYjgyNjE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tWrUfFkhXbsGuWZG2UHwPeCYameJ0Ag7BN8K_LV327k) [ ](https://private-user-images.githubusercontent.com/833231/372637291-32420844-de2d-468f-abc2-27cdf8262f30.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MjA3NjYsIm5iZiI6MTcyNzgyMDQ2NiwicGF0aCI6Ii84MzMyMzEvMzcyNjM3MjkxLTMyNDIwODQ0LWRlMmQtNDY4Zi1hYmMyLTI3Y2RmODI2MmYzMC5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQyMjA3NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2MwMGJjODM4MmM2ZDI0MjFjOTA5YjQyOGIxNmM0MDc0NTJhYzhmMzZhYTE1OWRmNWY1ODFhM2YyYjgyNjE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tWrUfFkhXbsGuWZG2UHwPeCYameJ0Ag7BN8K_LV327k)

Your comment seems to be inline with the DNS errors when migrating the beta API on the backend. Trending should be loading, and the Discover Workspaces section will error since they are hardcoded for production workspaces. There's an issue to change it based on the environment here: https://github.com/open-sauced/app/issues/4107

**Review by jpmcb — COMMENTED** [review]
I still briefly see the "Login" button and chunk.

And then it never loads actual recommendations:

Screenshot 2024-10-04 at 12 09 59 PM

Also notice that the workspaces aren't loading.

Hitting hard refresh a few times seems to have corrected the issue ... maybe I was getting a cached version of the page?

**Comment by nickytonline** [comment]
I'm still getting errors for trending repositories, and like @jpmcb, no workspaces are loading. I'm guessing workspaces aren't loading because they are production workspace IDs. We don't have an administration page for stuff like this, so consider adding FEATURED_WORKSPACES as an environment variable for now. I show you how to set this up in Netlify so we have beta and prod worskpace IDs.

https://github.com/open-sauced/app/blob/1de38c71c00f100733368f386252abb90f0d599a/pages/explore/index.tsx#L23-L30

CleanShot 2024-10-06 at 10 45 36

Also, if I'm logged out, I get a hydration error.

CleanShot 2024-10-06 at 10 46 01

**Comment by BekahHW** [comment]
Can we change the copy to be more general for maintainer or contributor? Also, bc it takes the user to the repo page as well:

**Current**
Here are some repositories we think would be great for you. Click on one to start contributing!

**Suggestion**

Discover repositories tailored to your interests. Click any to learn more!

**Additional Change**
Below the "Recommended for You" heading, remove the copy (Here are some repositories we think would be great for you. Click on one to start contributing!) if there are no projects displayed.

**Comment by zeucapua** [comment]
Closed - not priority, will not merge anytime soon.

**Pull request closed without merging**
