### PR TITLE
feat: connect most active contributors graph to API v2 endpoint

### PR DESCRIPTION
**Pull request by brandonroberts**
## Description

- Connects the Most Active Contributors graph to the V2 API endpoint
- Adds Reviewed PRs, Issues Created, and Comments to the chart data

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Mobile & Desktop Screenshots/Recordings

image

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by jpmcb — APPROVED** [review]
👏🏼 👏🏼

**Comment by jpmcb** [comment]
Let's hold off merging this till: https://github.com/open-sauced/app/pull/2469 is ironed out (don't want to accidentally overwrite your changes with a force push)

**Comment by jpmcb** [comment]
> don't want to accidentally overwrite your changes with a force push

> Disregard, we can merge this: there are some merge conflicts that will manually need to be fixed from `alpha` --> `beta`. So, when the time comes, we'll merge this the `alpha` branch to `beta` with a side branch based off `alpha` that has those conflicts resolved 👍🏼

So we can continue getting stuff onto `alpha` as long as we don't mind getting the latest and hottest from `beta` there as well

**Comment by brandonroberts** [comment]
That's fine with me. We've merged in from `main` after a release in the past also to keep things relatively up to date, but I think that has to be done manually.

**Review by nickytonline — APPROVED** [review]
:shipit:

**Review by NsdHSO — APPROVED** [review]
LGTM

**Comment by bdougie** [comment]
I haven't been able to check this out because of auth. I also see this screen first when clicking the deploy preview.

image

Curious if anyone else is seeing these errors

**Comment by brandonroberts** [comment]
Probably due to issue mentioned here by @jpmcb https://github.com/open-sauced/app/pull/2470#issuecomment-1889747698

**Comment by bdougie** [comment]
Ah. Did realize the target was alpha.

**Comment by jpmcb** [comment]
Yeah, I'm not sure if there's a better approach vs. pulling the PR locally and setting the API endpoint to `alpha.api.opensauced.pizza` - wish there was a more granular way to let deploy previews targeting a certain branch use certain env vars

**Comment by bdougie** [comment]
> Yeah, I'm not sure if there's a better approach vs. pulling the PR locally and setting the API endpoint to `alpha.api.opensauced.pizza` - wish there was a more granular way to let deploy previews targeting a certain branch use certain env vars

Working on setting this up now and see the alpha endpoint already there - https://github.com/open-sauced/app/blob/feat-most-active-contributors-api-v2/.env#L3

I don't have any lists on alpha, and getting a 401 unauthorized when trying to create one to test this feature. With two other approvals, we should move this forward and I can figure out my environment later though. 


Screen Shot 2024-01-16 at 8 29 29 PM

**Pull request merged**
