### PR TITLE
feat: added a link to OSCR tooltips pointing to the OSCR docs

### LINKED ISSUE #3920: Feature: Add a link to the OSCR docs in OSCR info tooltips
Add a link to the OSCR docs in OSCR info tooltips. Something like this.

CleanShot 2024-08-12 at 15 59 32

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Adds a link to the OSCR docs in OSCR info tooltips.

## Related Tickets & Documents

Closes #3920

## Mobile & Desktop Screenshots/Recordings

**Before**

CleanShot 2024-08-12 at 16 01 14

**After**

image

Note that the after screenshot is using our standard tooltip making it uniform with our other tootips.

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

**Review by brandonroberts — APPROVED** [review]

**Review by BekahHW — APPROVED** [review]

**Review by jpmcb — CHANGES_REQUESTED** [review]
The text looks much more "squished" to my eyes and less appealing. Is there anything we can do to make it appear uniform to how it was before? The box also doesn't look rounded anymore. This seems to be a regression.

---

Before:

Screenshot 2024-08-12 at 2 07 26 PM

After:

Screenshot 2024-08-12 at 2 07 59 PM

**Comment by nickytonline** [comment]
> Note that the after screenshot is using our standard tooltip making it uniform with our other tootips.

Note that the after screenshot is using our standard tooltip making it uniform with our other tooltips. I can put it back to the same sizing.

**Comment by nickytonline** [comment]
@jpmcb 

CleanShot 2024-08-12 at 16 11 39

**Comment by jpmcb** [comment]
> Note that the after screenshot is using our standard tooltip making it uniform with our other tooltips. I can put it back to the same sizing.

Gotcha - I had assumed the original had some special design, but it seems not: https://github.com/open-sauced/app/pull/3857

Dealers choice!! 🃏

**Review by jpmcb — APPROVED** [review]

**Pull request merged**
