### PR TITLE
feat: search for repositories

### LINKED ISSUE #3122: Feature: Add ability to search for repositories on the searchbar
### Type of feature

🍕 Feature

### Current behavior

The searchbar today only allows to search for contributors / developers
image

### Suggested solution

We want to allow users to also search for repositories.

Functional requirements:
- When the user searches, show a max of 3 results for users and a max of 3 results for repositories, but throw results for both at the same time
- Require a minimum of 3 characters to star searching, the same way we do with users

image

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by zeucapua**
## Description

Implements searching for repositories in the search bar (omnibar) which leads the user to its repo page.

## Related Tickets & Documents

Closes #3122 

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/app/assets/20603494/6001d0be-98ed-4175-985e-edc473aae80c

## Steps to QA
1. Use `⌘K` or `Ctrl+K` or the search input in the `TopNav` to open omnibar
2. Search for any repo/user
3. When going to a user, ensure it goes to their profile page
4. When going to a repository, ensure it goes to its repo page

## Tier (staff will fill in)

- [ ] Tier 1
- [x] Tier 2
- [ ] Tier 3
- [ ] Tier 4

## [optional] What gif best describes this PR or how it makes you feel?
search-shanique-drummond-gif

### CODE REVIEW

**Comment by zeucapua** [comment]
The `searchUsers` function doesn't use SWR for fetching and caching, which is what's probably causing the rate limits. 

I can make a new file and hook similar to what we've been doing for other GitHub related searches. I'd remove/write over the existing function and file, but it's being used by `/lists` and `/hub/lists` (although I don't know how much that is being used since they were rolled over to workspace contributor insights),

What should I do? @brandonroberts @nickytonline

**Comment by jpmcb** [comment]
>  I also did 5 searches back to back not logged in and got rate limited by GitHub immediately. Note the "could not find repos with that name" error is my rate limit hit.

My suggestion would be twofold:
- Wait for the user to stop typing (or some acceptable amount of time)
  - hit _our_ API with a request to search for that repo (since our stuff has most of the metadata anyways. Not sure how this would work for the little avatars and if those are behind GitHub's API limits) - if this means we need some sort of fuzzy search in the API, we can definitely add that
- Return our API results: if we're missing results, go fetch them from GitHub

**Review by bdougie — APPROVED** [review]
Thanks @jpmcb and @zeucapua for polishing this one a little more. Works well now.

**Review by brandonroberts — APPROVED** [review]
Works great. Also checked workspace search for repos/users

**Pull request merged**
