### PR TITLE
fix: fixed several UI/UX issues for StarSearch

### LINKED ISSUE #3693: Bug: Several UI/UX Issues in StarSearch
From @isabensusan

## Polish
- Remove scrolling
- Improve height, make share/clear history not sticky and just stay at bottom of scrolled area
- Add some animations and shadowing

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

These are all UI/UX improvements from a pairing session I had with @isabensusan today.

- some CSS Tweaks for StarSearch
- added logos to left of repo page URLs
- removed autoscroll after render
- conversation bottom menu scrolls with conversation
- improved scrolling DX
- now bottom fades in
- set fixed sizes for chatboxes
- made input orange border uniform
- added hover effects to suggested prompt cards
- tweaked prompt input styles
- now top gradient in StarSearch is in the background

## Related Tickets & Documents

Fixes #3693

## Mobile & Desktop Screenshots/Recordings

Before and after side by side

https://github.com/user-attachments/assets/5415e231-52c1-4689-bd37-01b69eeeb98a

## Steps to QA

Very general, but use StarSearch on the StarSearch page and in Workspaces. Note that StarSearch for workspaces only works for workspaces where you're an owner. Future work will let you know if you aren't the owner.

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [x] Tier 3
- [ ] Tier 4

### CODE REVIEW

**Comment by nickytonline** [comment]
This is almost ready @isabensusan. I just need to make a couple tweaks so it works well in workspaces.

**Comment by nickytonline** [comment]
I'm still sorting out one issue with the embedded StarSearch for smaller screens where I can't scroll, but aside from that (will get it sorted), it'd be good to have people take this for a test drive.

**Comment by bdougie** [comment]
Perhaps this is related to that last item you are trying to figure out, but I am on mobile only right now and can't close the embedded star search. Both the sidebar and the embedded starsearch started open when I logged in and redirected to the workspace.

**Review by bdougie — CHANGES_REQUESTED** [review]
Let's hold off on merging this until @nickytonline is back or we 
can address this issue on mobile.

I can't close the starsearch menu and this makes all of workspaces unusable for me.

https://github.com/user-attachments/assets/415477fc-b410-4e91-a1a1-4aa0acdd0da3

**Comment by nickytonline** [comment]
> Let's hold off on merging this until @nickytonline is back or we can address this issue on mobile.
> 
> I can't close the starsearch menu and this makes all of workspaces unusable for me.
> 
>  trim.DEE7A130-D3EE-44B4-9323-C6F06A907591.MOV

Ahh, I know what that is. It's our top nav getting a bit chonky on smaller screens, but yeah, all good with holding off until next week. I'll take a peek at the above when I'm back on Monday.

**Comment by nickytonline** [comment]
> > Let's hold off on merging this until @nickytonline is back or we can address this issue on mobile.
> > I can't close the starsearch menu and this makes all of workspaces unusable for me.
> > trim.DEE7A130-D3EE-44B4-9323-C6F06A907591.MOV
> 
> Ahh, I know what that is. It's our top nav getting a bit chonky on smaller screens, but yeah, all good with holding off until next week.

Sorted this out. Now you can open and close StarSearch on smaller screens.

**Comment by nickytonline** [comment]
We got rid of the auto-scrolling @isabensusan as it was annoying while you were trying to read what was coming in, but I think it makes sense to scroll to the end once the streamed response is complete. We can chat about it tomorrow.

**Review by bdougie — APPROVED** [review]

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
