### PR TITLE
feat: add Angular as a topic

### PR DESCRIPTION
**Pull request by monacodelisa**
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

I feel good about it :) I hope I added everything needed

### CODE REVIEW

**Comment by bdougie** [comment]
need to run `npm run format` locally. There are lint errors failing the build.

**Comment by monacodelisa** [comment]
I was looking into it but I haven't run a React app locally in few years... I am afraid that my environment might mess things up...

**Comment by brandonroberts** [comment]
@monacodelisa the order of imports just needs adjusting

image

**Review by bdougie — APPROVED** [review]
Thanks for the contribution @monacodelisa

**Review by nickytonline — APPROVED** [review]
Thanks for this @monacodelisa! This is good to go aside from what @brandonroberts mentioned.

**Comment by brandonroberts** [comment]
@monacodelisa one more change. Need to add the logo from this PR https://github.com/open-sauced/app/pull/2680

**Comment by monacodelisa** [comment]
ok I'm on it

**Comment by brandonroberts** [comment]
Thanks @monacodelisa!

**Comment by monacodelisa** [comment]
thank you, and sorry it took so many commits

**Pull request merged**
