### PR TITLE
refactor: use api timezone options for contributors filter

### LINKED ISSUE #1820: Refactor: update list creation timezone filter to use api timezone for timezone options
### Type of feature

🧑‍💻 Refactor

### Current behavior

Currently we use stub timzeone data from [timezone.ts](https://github.com/open-sauced/insights/blob/beta/lib/utils/timezones.ts) for the timezone filter select options. 

### Suggested solution

With https://github.com/open-sauced/api/pull/340 merged, we need to fetch the timezones options from `/v1/lists/timzones` endpoint

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by OgDev-01**
## Description

This pull request includes a refactoring of the code to utilize the getServersideProps approach, which improves performance and ensures data is fetched on the server side. 

Contributors data are now fetched serverside and available on initial load with timezones

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [x] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
closes #1820

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/app/assets/62995161/66546e48-8329-4a7b-83f5-9281ed885a8d

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
I made this comment on the previous PR, but the timezone feature is not useable. We should be grouping by offset and not by timezone name. If I filter WAT, I should also see individuals in London (both are UTC+1 or offset:1). 

The timezone filter needs to be useable.

**Review by bdougie — CHANGES_REQUESTED** [review]
We need the UTC translation to stay in the time zone name or group by offset. Also noticed I can't deselect a time zone from the filter. Or at least it is not obvious. 

I know that is unrelated to that change, but this feature is getting less useable with this change and not more.

**Comment by OgDev-01** [comment]
Hey @bdougie, I Just made an update to the timezones options... We now have a similar shape to your suggestions on the time zones.

**Review by bdougie — APPROVED** [review]
This is much better.

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
