### PR TITLE
fix: overflows in insights page on md screen size

### LINKED ISSUE #1574: Bug: overflows in insights page on md screen size
### Describe the bug

insights-page-responsive

### Steps to reproduce

1. Visit your insights page
2. Switch to tablet view (768px)

### Browsers

Chrome

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by RitaDee**
## Description

Update the padding on the main content container in the HubLayout component. The previous padding was too large on smaller screens, so it has been reduced from md:px-16 to md:px-2. This change ensures a better user experience by providing more space for the content on smaller devices.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1574

## Mobile & Desktop Screenshots/Recordings

Before: 

Screenshot 2023-08-22 at 15 25 21

After:
Screenshot 2023-08-22 at 15 24 03

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by OgDev-01** [comment]
This Looks good visually, Just curious if the fix in the layout doesn’t affect other pages that uses the layout 🤔 .
I'll test to confirm.

**Comment by RitaDee** [comment]
> This Looks good visually, Just curious if the fix in the layout doesn’t affect other pages that uses the layout 🤔 .
> I'll test to confirm.

I did check other pages nothing was affected. It will be nice to confirm from your end too.

**Review by OgDev-01 — APPROVED** [review]
All Good 👍. Great job! 🍕

**Review by bdougie — APPROVED** [review]
I was confused at first what the fix and change was. I figured it out and it looks good. 

I'd love to do a follow up pr that adds and `...` for names that don't fit similar to the top contributors fix.
Screen Shot 2023-08-22 at 4 29 16 PM

## example

Screen Shot 2023-08-22 at 4 35 05 PM

**Pull request merged**
