### PR TITLE
feat: introduce application side nav

### PR DESCRIPTION
**Pull request by brandonroberts**
## Description

- Introduces the side nav into the application with repository and contributor insights
- Hidden on small screens/mobile (May need to be refactored to behave like an overlay)
- Only shows on pages with `/hub` in the URL (authed pages)

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Mobile & Desktop Screenshots/Recordings

image

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by jpmcb — COMMENTED** [review]
👏🏼 !!!! Nice! Looking amazing

---

Looks like this:
1. Pushes everything (on a slightly smaller screen) to the right - notice the right side view is flowing off the screen
2. For a non-logged in user, this just spins: may want to think of a better onboarding for unauthenticated users in the future

Screenshot 2024-01-03 at 6 17 04 PM

---

Looks like the list scrolls with the page scroll: my assumption is this would be locked / it's own scroll

**Comment by bdougie** [comment]
> Looks like this:

>1. Pushes everything (on a slightly smaller screen) to the right - notice the right side view is flowing off the screen
> 2. For a non-logged in user, this just spins: may want to think of a better onboarding for unauthenticated users in the future

Think we may want to hide non-logged in users for now. 

I also would expect the support section to be sticky and not scroll. 

Screen Shot 2024-01-03 at 9 12 40 PM
Screen Shot 2024-01-03 at 9 12 43 PM

**Comment by OgDev-01** [comment]
This is already starting to look great! 👍 

Some Ui tweaks will see this through:

- The sidenav should be fixed with a height of `100vh`
- The previous layout structure will also need updating for the feeds page
image
- We also talked about truncating the list to a certain limit with a `view all` button to prevent the list from growing too long.(This can come in a a follow up PR)

Overall, this is looking good👍

**Comment by brandonroberts** [comment]
Will wait for more feedback, but updated with some of the suggestions

- Only shows when authenticated
- Only shows on pages with `/hub` in the URL (insights, lists, create, edit)
- Bottom of sidenav is sticky

**Comment by OgDev-01** [comment]
From the screen record, i believe we want the side nav to be fixed and not scroll with the entire page. This behaviour can be achieved by setting the side nav to position fixed (`fixed` for the tailwind class equivalent)
https://github.com/open-sauced/app/assets/62995161/162c6274-3d56-4afb-b660-845b39d4b70e

**Comment by isabensusan** [comment]
This is looking great!

Can we extend the top nav to take up more horizontal space and match up with the sidebar text?
image

I can work on a mobile view of the sidebar as well.

@brandonroberts mind if I jump in with some style touches when you are done with the functional side?

**Comment by isabensusan** [comment]
Also, can we add the option to collapse the sidebar?

If we add a collapse Icon on the top right corner of the sidebar, we can let users toggle it on/off to let them get more space back when looking at complex pages like insight pages.
image


For the collapsed view we can show a "menu" icon at the top for users to show the sidebar agan, and show only the support and setting icons at the bottom.
image


These are friday 8pm mockups lol, so we can touch on it monday for more clarity

**Comment by nickytonline** [comment]
> Also, can we add the option to collapse the sidebar?
> 
> If we add a collapse Icon on the top right corner of the sidebar, we can let users toggle it on/off to let them get more space back when looking at complex pages like insight pages. image
> 
> For the collapsed view we can show a "menu" icon at the top for users to show the sidebar agan, and show only the support and setting icons at the bottom. image
> 
> These are friday 8pm mockups lol, so we can touch on it monday for more clarity

+1 to the collapse like in GMail where you get more real estate.

CleanShot 2024-01-08 at 16 31 46

**Comment by nickytonline** [comment]
I'm going to wrap the component in a feature flag as discussed @brandonroberts.

**Review by nickytonline — APPROVED** [review]
This has been feature flagged now, and I'll probably be taking over the polish for this so I'm going to go ahead and approve.

**Review by OgDev-01 — APPROVED** [review]
Approving on the basis of @nickytonline comments

**Review by OgDev-01 — APPROVED** [review]
Approving on the basis of @nickytonline comments

**Comment by bdougie** [comment]
The feature flag is causing me to not see it and its breaking the layout.

Screen Shot 2024-01-10 at 10 19 59 AM

**Comment by jpmcb** [comment]
+1 ^

Also seems to break the explore page even when logged in

Screenshot 2024-01-10 at 12 11 48 PM

**Comment by nickytonline** [comment]
> The feature flag is causing me to not see it and its breaking the layout.
> 
> Screen Shot 2024-01-10 at 10 19 59 AM

I'll use the feature flag still but just tweak how I'm using it so it doesn't break existing layout @bdougie @jpmcb.

**Comment by nickytonline** [comment]
Fix in .

https://github.com/open-sauced/app/assets/833231/fc978c3c-08d3-4e4d-a1e7-8df7413fdf9e

**Review by bdougie — APPROVED** [review]
Thanks for taking this on @brandonroberts and @nickytonline

**Review by jpmcb — APPROVED** [review]
👏🏼

**Pull request merged**
