### PR TITLE
feat: implement TanStack `ContributorsTable` to explore page

### LINKED ISSUE #3859: Feature: Replace contributor table in explore page with new table component

### PR DESCRIPTION
**Pull request by zeucapua**
## Description

Implements the new TanStack `ContributorsTable` to the explore's contributor tab page.

## Related Tickets & Documents

Closes #3859 

## Mobile & Desktop Screenshots/Recordings
image

## Steps to QA

1. Go to the explore page and click the 'Contributors' tab
2. See the new table

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [x] Tier 3
- [ ] Tier 4

### CODE REVIEW

**Comment by BekahHW** [comment]
In a future version will you be able to sort by OSCR?

**Comment by BekahHW** [comment]
I'm testing on mobile, and currently, I'm not able to click to the next page after 1.

**Comment by jpmcb** [comment]
> In a future version will you be able to sort by OSCR?

@BekahHW - There's a large API refactor that's been iceboxed for that: sorting on may hundreds (if not thousands) of these contributors in the explore page via the `contributors/search` endpoint would be pretty heavy.

FYI - https://github.com/open-sauced/api/issues/984

**Comment by brandonroberts** [comment]
The `Add to Insight` button is not displayed when selecting contributors

image

**Comment by brandonroberts** [comment]
Contributors table on the explore page is being removed here https://github.com/open-sauced/app/pull/4019

**Comment by zeucapua** [comment]
Closed; removed on #4019

**Pull request closed without merging**
