### PR TITLE
feat: add `ListCard` component to design system

### LINKED ISSUE #1669: Feature: new List Card component
### Type of feature

🍕 Feature

### Current behavior

N/A

### [Figma File](https://www.figma.com/file/OpVX6WT7dmWqnwRuEvADMF/Design-Lab?type=design&node-id=10472-25560&mode=design&t=rel3TgaKShihQBzJ-4)

This component is meant to replicate the Inisghts Card component, but to represent a list.

**Components to reuse:**
- [Stacked avatar](https://design-insights.netlify.app/?path=/docs/design-system-molecules-stacked-avatar--docs)
- Insights component (couldn't find a storybook link)

image

### In Context
image

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by OgDev-01**
## Description
This PR adds a new component called `ListCard` which is a molecule component. It displays a card with information about a list. The card includes the list name, whether it is public or private, the number of contributors, and avatars of the contributors. The component also includes buttons to delete the list and navigate to the list's overview page. The `StackedAvatar` component is also updated to include a `classNames` prop for custom styling.

_Generated using [OpenSauced](https://opensauced.ai/)._

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
closes #1669 

## Mobile & Desktop Screenshots/Recordings
image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [x] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by brandonroberts** [comment]
The alignment seems a bit off in the screenshot with `Contributors` and the images

image

**Comment by OgDev-01** [comment]
> The horizontal alignment seems a bit off in the screenshot with `Contributors` and the images
> 
> image

Its as a result of the white background on the storybook layout. when used on the insights page, it looks aligned

**Review by jpmcb — APPROVED** [review]
Nice work!

Screenshot 2023-09-07 at 3 36 25 PM

This is a screenshot from the storybook: seems the buttons on the right side are bit elevated? Abit hard to tell, but I think I agree with Brandon, seems abit off 🤔

**Review by brandonroberts — APPROVED** [review]
We can get more eyes on it after its on a page

**Pull request merged**
