### PR TITLE
fix: don't recommend discordapp as url & use user's full id

### PR DESCRIPTION
**Pull request by Lulalaby**
## Description

The open-sauced profile field for discord has the placeholder of discordapp.com which is deprecated since ages.
Additionally for the profile view, the id was taken and shortened to the last 4 digits, which can be mistaken for the old discriminator system (which is also deprecated).
While a full integration of discord oauth should be the goal in future, this acts as a temporary fix.

I might add the implementation if I feel like it soon.

Upon reading the repositories README, I stumbled across "We can only take unsolicited contributions from OpenSauced Triage, Committers, and Maintainers for now". Is that a problem for this pr?

If it is a problem, feel free to use the patch file I've attached 💕

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Not applicable

## Mobile & Desktop Screenshots/Recordings

image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

Not applicable

## [optional] What gif best describes this PR or how it makes you feel?

this

[0001-fix-don-t-recommend-discordapp-use-user-s-full-id.patch](https://github.com/open-sauced/app/files/13190290/0001-fix-don-t-recommend-discordapp-use-user-s-full-id.patch)

### CODE REVIEW

**Comment by bdougie** [comment]
Contributions need to start as issues. This helps us filtered out duplicate contributions.

You shared a lot of great context in this PR though. Feel free to reopen so we can explore more.

**Comment by Lulalaby** [comment]
> Contributions need to start as issues. This helps us filtered out duplicate contributions.
> 
> You shared a lot of great context in this PR though. Feel free to reopen so we can explore more.

Yeah totally missed that since the docs domain doesn't load for me at all

**Review by bdougie — APPROVED** [review]
For our benefit, could you link the deprecation announcement here as well?

Tested in the preview and works as expecred.

**Comment by Lulalaby** [comment]
Discord Developers Server: https://discord.gg/discord-developers

https://discord.com/channels/613425648685547541/697138785317814292/1163963748583735338
<details><summary>Public announcement at October 18, 2023</summary>
<p>

> # Global Rate Limit added to `discordapp.com/*`
> ℹ️﻿ We have added a global rate limit for API requests made to `discordapp.com/*` and may further restrict requests in the future. 
> 
> To limit impact on your app, please make sure you are making calls to `discord.com/*`.
> 
> This does **not** apply for `cdn.discordapp.com`.
> 
> **🔍 Refer to the [API Reference](https://discord.com/developers/docs/reference)  for more info on which url(s) to use when building on the REST API**
> 
> - [February 14, 2022 Change Log](https://discord.com/developers/docs/change-log#feb-14-2022): Requests to v10 and higher will no longer be supported on discordapp.com (this does not affect cdn.discordapp.com)
> - May 4, 2020 Change Log https://discord.com/channels/613425648685547541/697138785317814292/706944540971630662

</p>
</details> 

https://discord.com/channels/613425648685547541/697138785317814292/706944540971630662
<details><summary>Previous announcement about deprecation from May 4, 2020</summary>
<p>

> 📣 API Updates 📣 
> 
> May the 4th be with you <a:BabyYodaSip:653329843332579359>  Discord has finally made the switch to `discord.com` 🎉
> 
> With this change also means that the API endpoint is moving too! Please start moving your libraries, webhooks, and integrations over to using `discord.com` in place of `discordapp.com`.
> 
> We currently plan to start requiring the new domain later this year for third party developers on November 7th, 2020. We will be > sending out more formal notices (system DMs and account emails) to announce this breaking change in the coming weeks.

</p>
</details> 


That's the public information, and some knowledge comes from internal places which I can't link

**Review by nickytonline — APPROVED** [review]
Thanks for the update @Lulalaby! 🚀

**Pull request merged**
