### PR TITLE
feat: add million.js

### PR DESCRIPTION
**Pull request by ayusham001**
Revolves [aidenybai/millon#554](https://github.com/aidenybai/million/issues/554)
/claim [aidenybai/millon#554](https://github.com/aidenybai/million/issues/554)

### CODE REVIEW

**Comment by ayusham001** [comment]
hello @aidenybai 
please review my PR

**Comment by bdougie** [comment]
@ayusham001 thanks for the PR. We are discussing it internally. Impressed with how quick this was able to be put together, we just need to evaluate the investment in adopting million in the project and what value it would provide.

**Comment by ayusham001** [comment]
@bdougie 
Thank you for your consideration.

**Comment by brandonroberts** [comment]
Thanks for the PR @ayusham001! 

While we did see some improvements in overall performance here, we think the million.js integration would be better suited added to our https://github.com/open-sauced/hot repo, where it would have more impact there, and we would have more time to evaluate integrating it into this codebase. 

Going to close this PR and [opened an issue](https://github.com/open-sauced/hot/issues/486) there. Then you can open another PR there so we don't lose track of the bounty.

**Comment by ayusham001** [comment]
Hi @brandonroberts Thank you for your feedback! 
I'll open a new one in the https://github.com/open-sauced/hot repo as suggested.

**Pull request closed without merging**
