### PR TITLE
fix: repos table in small screens does not show select

### LINKED ISSUE #1477: Bug: repos table in small screens does not show select.
### Describe the bug

Bug: repos table in small screens does not show select.
image

### Steps to reproduce

1. https://insights.opensauced.pizza/javascript/repositories/filter/recent
2. make screen small
3. see that we have no select 

I am expecting to see the select:
image

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by RitaDee**
## Description
Add a checkbox to the RepoRow component for selecting repositories. The checkbox is rendered based on the "selected" prop. When the checkbox is checked or unchecked, the "handleSelectCheckbox" function is called. The checkbox has a border colour of orange and a hover background colour of orange if the "user" prop is truthy.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1477

## Mobile & Desktop Screenshots/Recordings

Before:
Screenshot 2023-08-16 at 14 42 09

After:

Screenshot 2023-08-16 at 14 36 39

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by NsdHSO** [comment]
LGTM

**Review by babblebey — COMMENTED** [review]
LG 🍕

**Review by bdougie — APPROVED** [review]
We originally left the check boxes off mobile because we did not a great filtering experience (the original feature for checkboxes). But now we don't allow filtering for repos (which we should add back eventually).

https://github.com/open-sauced/insights/pull/693

**Review by OgDev-01 — APPROVED** [review]
🍕

**Pull request merged**
