### PR TITLE
refactor: update top users implementation to remove already followed users

### PR DESCRIPTION
**Pull request by OgDev-01**
## Description
This PR sends the logged in user id to the API to filter out already followed user's from the top users list

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
related to #1593 and https://github.com/open-sauced/api/pull/275

### Before
image

###After
image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by brandonroberts — APPROVED** [review]

**Comment by bdougie** [comment]
I am seeing the same that John sees. Is this waiting on an API release? 

Screen Shot 2023-08-24 at 12 51 30 PM

**Comment by OgDev-01** [comment]
Interesting 🤔 . @brandonroberts can you confirm that the build went successful for the API after https://github.com/open-sauced/api/pull/275 was merged? I was testing with my local instance when I worked on this and didn’t catch that the beta remote version isn’t working

**Comment by brandonroberts** [comment]
@OgDev-01 yes, there was an issue with the deployment I just merged a fix for https://github.com/open-sauced/api/pull/276. Should be available in a few minutes

**Comment by brandonroberts** [comment]
The Beta API is deployed now

image

**Review by jpmcb — APPROVED** [review]
👏🏼

**Pull request merged**
