### PR TITLE
fix: Issue #2324 Complete onboarding button flashes for a second or two on smaller screens

### LINKED ISSUE #2324: Bug: Complete onboarding button flashes for a second or two on smaller screens
### Describe the bug

Bug: Complete onboarding button flashes for a second or two on smaller screens

### Steps to reproduce

1. Navigate to any page on mobile or use the browser dev tools to select a smaller screen.
2. Log in to the app.
3. If you haven't completed the onboarding, go ahead and do that.
5. Once onboarding completes, notice that as the page loads, the Complete the onboarding button appears for a second or two.

CleanShot 2023-12-12 at 22 38 16

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by keltrycroft**
## Description
This PR adds a session check to the onboarding button 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2324

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by nickytonline** [comment]
Thanks for the pull request @keltrycroft. Can you add a description in the pull request as well as a before and after of the fix if possible? Thanks!

**Comment by nickytonline** [comment]
There are lint errors. If you run `npm run lint -- --fix`, it should correct the lint errors in question.

**Comment by NsdHSO** [comment]
@keltrycroft Could you provide us some details about the state of this PR?

**Comment by BekahHW** [comment]
@keltrycroft would you please provide a screen recording as well?

**Comment by takanome-dev** [comment]
Hey @keltrycroft, just wanted to check in and see how things are going. If you need any help, feel free to reach out. If there are any obstacles or if you're unable to continue with this, just let us know 😉

**Pull request closed without merging**
