### PR TITLE
fix: Unnecesary X-Scrollbar in tablist

### LINKED ISSUE #1874: Bug: Scrollbar appears in list header
### Describe the bug

A scrollbar appears in list header.

CleanShot 2023-10-11 at 16 26 54

### Steps to reproduce

1. Navigate to a list, e.g. https://app.opensauced.pizza/lists/04a518a0-87f7-47ad-89e9-784f4b376941/overview
2. As you start to resize a window and make it smaller, an unnecessary scrollbar appears that is not required as all the content is still viewable.

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by Satoshi-Sh**
## Description

The tab list had an unnecessary x-scrollbar. "md: px-16" gives an extra space to the right of the list, removing the class resolved the issue.
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1874 
## Mobile & Desktop Screenshots/Recordings

Before 
before-scrollbar

After
scrollbar-issue

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by RitaDee** [comment]
@Satoshi-Sh, well done. You need to edit the heading or title to look like this "fix: Unnecessary X-Scrollbar in tablist", Instead of "[Bug] Unnecesary X-Scrollbar in tablist"

**Comment by Satoshi-Sh** [comment]
> > > @Satoshi-Sh, well done. You need to edit the heading or title to look like this "fix: Unnecessary X-Scrollbar in tablist", Instead of "[Bug] Unnecesary X-Scrollbar in tablist".
> > > Also, add a demo of what the fix looks like now.
> > 
> > 
> > Thanks, Rita. Updated the title. The gif is not enough for the demo?
> 
> It would be super helpful to have a before and after screen record as the gif doesn’t provide enough context. Thanks once again for this fix 🍕

Added the gif from the issue. Thanks for your guidance!!

**Review by nickytonline — APPROVED** [review]
Thanks for this @Satoshi-Sh!

**Review by OgDev-01 — APPROVED** [review]
🍕

**Pull request merged**
