### PR TITLE
feat: add new insights card for upgraded users

### PR DESCRIPTION
**Pull request by OgDev-01**
## Description
This PR:

- Adds new insights card component to design system
- refactors dashboard analytics component structure for optimisation 
- Displays new dashboard analytics for paid users insights page

### TODO

- [x] move dashboard analytics section to a seperate component
- [x] fetch and display new insights data on new insights card

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
Closes https://github.com/open-sauced/ops-backend/issues/125

### pull requests
image

### Active contributors
image

### New contributors
image

### churned contributors
image

### All 
Screenshot 2023-09-06 at 19 45 38

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [x] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by brandonroberts** [comment]
Churned contributors should be updated to "Alumni Contributors"

**Comment by OgDev-01** [comment]
Current Data available on this Dashboard cards

- Total PR count for the last 30d
- Active contributors count 
- New contributors count
- Alumni contributors count

Unavailable data

- commits information for the graph
- percentage of increase/ decrease in activity in comparison to the previous 30d
- count  of increase/ decrease in activity in comparison to the previous 30d

cc: @brandonroberts @bdougie @jpmcb

**Comment by jpmcb** [comment]
> commits information for the graph

@OgDev-01 - for the commits data, I added `commits` as part of the information in each individual PR.

For example, using `/v1/prs/search` I can get back information that has `commits`:
```json5
{
  "data": [
    {
      "id": 1045024650,

      // truncated ...

      "commits": 4
    }
  ],
  "meta": {
    "page": 1,
    "limit": 10,
    "itemCount": 100,
    "pageCount": 10,
    "hasPreviousPage": false,
    "hasNextPage": true
  }
}
```

Will that work for aggregating commit data based on the time range for the dashboard?

**Comment by bdougie** [comment]
> Will that work for aggregating commit data based on the time range for the dashboard?

@OgDev-01 is this PR blocked?

**Comment by OgDev-01** [comment]
> > Will that work for aggregating commit data based on the time range for the dashboard?
> 
> @OgDev-01 is this PR blocked?

With the pr from @jpmcb on the api... I think I can add the commits chart... will pick this up tomorrow

**Comment by OgDev-01** [comment]
> @OgDev-01 is this still blocked?

Yes, we need more information about the time of the commit as the chart depends on it `commit_time`

**Comment by jpmcb** [comment]
This should probably be blocked until we have project pizza-time up and running: these line charts will be very hard to pull off _without_ time series data.

**Comment by nickytonline** [comment]
Closing this for now Sunday as it's from late August. Feel free to reopen this if it makes sense to once you've wrapped up other work.

**Pull request closed without merging**
