### PR TITLE
fix: broken URL when you are using Range filter

### PR DESCRIPTION
**Pull request by a0m0rajab**
## Description

This PR fixes the odd links in the app, by checking if the router is ready to push range based on that. 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

fix https://github.com/open-sauced/app/issues/2185

###  Before 

https://github.com/open-sauced/app/assets/18273833/d39040d9-efa0-414e-821f-c59ff22b1542

### After 

Note: you could jump to 50th second to see the rendering.

https://github.com/open-sauced/app/assets/18273833/6fea6677-541d-4758-a3fd-9910d735ed18 

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [x] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by nickytonline — APPROVED** [review]
I took this for a spin and things are working as expected now. Mind adding a screenshot and/or short video with demonstrating the fix?

Thanks! :shipit:

**Comment by a0m0rajab** [comment]
@nickytonline thanks for the review, I have added a video of the before and after in the PR description, is there anything I need to highlight in the video?

**Comment by brandonroberts** [comment]
@a0m0rajab does this handle https://github.com/open-sauced/app/issues/2211 also?

**Comment by a0m0rajab** [comment]
@brandonroberts nope, that's happening due to the inconsistency in the naming. Just changing the `range` keyword to `limit` would solve the other issue I think. I mentioned it in the issue comment itself: https://github.com/open-sauced/app/issues/2185#issuecomment-1826008397 but did not open an issue for that yet.

**Review by OgDev-01 — APPROVED** [review]
👍

**Pull request merged**
