### PR TITLE
feat: Remove title input field from HighlightInputForm

### LINKED ISSUE #1657: Feature: Remove title from highlights
### Type of feature

🍕 Feature

### Current behavior

Can we remove the title?

The design intentionally remove it because of the complexity and confusion the title causes

image

1. Title is not used in social cards
2. Title is not included in the character limit for posts, but has a hidden char limit
3. Title does not add value and only confusion for submissions

### Suggested solution

1. Remove the ability to add titles in the highlights form
2. Remove the title from being displayed in all highlight components.  

### Additional context

related https://github.com/open-sauced/app/pull/1646

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by RitaDee**
## Description
This PR removes the title input field from the `HighlightInputForm`.

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1657

## Mobile & Desktop Screenshots/Recordings

Before:
image

After:
image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by babblebey** [comment]
Hi @RitaDee,

Is this PR ready for review?

**Comment by RitaDee** [comment]
> Hi @RitaDee,
> 
> Is this PR ready for review?

It’s not ready.

**Comment by RitaDee** [comment]
@brandonroberts, I have done the fix.

**Comment by bdougie** [comment]
Ideally this PR merges after https://github.com/open-sauced/app/pull/1646

cc @diivi for awareness.

**Comment by diivi** [comment]
Yup

**Review by jpmcb — CHANGES_REQUESTED** [review]
> Ideally this PR merges after #1646

Blocking merge on 👍🏼

**Review by OgDev-01 — APPROVED** [review]
Good to go once  #1646 is merged 🍕

**Comment by isabensusan** [comment]
@OgDev-01  @RitaDee  lgtm! one minor comment is that I'd remoe the "Post a highlight to show your work" span and make it just a placeholder for the form, but I think Divii has done that on the PR that is going to be merged with this

**Review by isabensusan — APPROVED** [review]

**Review by jpmcb — APPROVED** [review]
Unblocking!! https://github.com/open-sauced/app/pull/1646 has merged

**Pull request merged**
