### PR TITLE
feat: add workspace layout to user page

### LINKED ISSUE #2780: Feature: Show sidebar everywhere in app
### Type of feature

🍕 Feature

### Current behavior

Sidebar shows up exclusively within the workspaces context.

### Suggested solution

Make the sidebar available in every other part of the platform as well, for easier access to workspaces and insights.

Namely:
- Highlights page
- Explore page
- User profiles

Excluding:
- User Settings
- Notifications

Design incoming for an empty state to show to non-logged in users

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### LINKED ISSUE #3520: Feature: add workspace sidebar to `/u/[username]`
### Suggested solution

Related to #2780

### LINKED ISSUE #3524: Bug: extra padding on top of user profile page
### Describe the bug

Very small bug, but there's a bit of extra padding on top of user profiles. The colored image should sit flush against the top of the page and it doesn't.

**What it looks like**
image

**What it should look like**
image

It looks like the `lg:pt-20` class in the page container is a bit too much
image

### Steps to reproduce

1. Go to https://app.opensauced.pizza/user/kenwheeler or any user profile
2. see extra padding on top of header image

### PR DESCRIPTION
**Pull request by zeucapua**
## Description

Implement `WorkspaceLayout` component and wrap it on the existing user page

## Related Tickets & Documents

Closes #3520 
Closes #2780 
Closes #3524 

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/app/assets/20603494/80180914-4e60-4c05-87ec-074061b84a98

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

## [optional] What gif best describes this PR or how it makes you feel?
case-closed-legal-gif

### CODE REVIEW

**Comment by bdougie** [comment]
What's with the space in the layout?
 
Screenshot 2024-06-07 at 11 35 32 AM

**Comment by nickytonline** [comment]
Was going to mention the same, but @bdougie beat me to it. Once that is sorted, this should be good to go as the sidebar works.

**Review by nickytonline — CHANGES_REQUESTED** [review]
Was going to mention the same, but @bdougie beat me to it. Once that is sorted, this should be good to go as the sidebar works. My quick guess is the old layout, `ContributorProfilePage ... />` in the worskpace layout is causing issues.

**Before**

CleanShot 2024-06-07 at 15 14 32

**After**

CleanShot 2024-06-07 at 15 14 24

**Comment by zeucapua** [comment]
Fixed! This will also close #3524! This required removing padding and margins from the `WorkspaceLayout`, causing layout shifts to every other page already using it. So if you see changes to other pages, that's me adding the padding back to avoid errors (see workspace home below).

cc. @bdougie @nickytonline 

image

image

**Review by jpmcb — CHANGES_REQUESTED** [review]
Padding now seems broken on the workspaces page?

### Deploy preview:

Screenshot 2024-06-07 at 2 35 02 PM

### Beta:

Screenshot 2024-06-07 at 2 35 27 PM

**Comment by nickytonline** [comment]
> Padding now seems broken on the workspaces page?
> 
> ### Deploy preview:
> Screenshot 2024-06-07 at 2 35 02 PM
> ### Beta:
> Screenshot 2024-06-07 at 2 35 27 PM

Just like we have a footer slot in the workspaces layout, maybe a header slot will help with the spacing issues while still preserving the layout of pages already using the workspaces layout.

https://github.com/open-sauced/app/blob/8eb580dd723f81ef169af26830e74f2ed2a1fa42/components/Workspaces/WorkspaceLayout.tsx#L84-L88

**Comment by zeucapua** [comment]
> Just like we have a footer slot in the workspaces layout, maybe a header slot will help with the spacing issues while still preserving the layout of pages already using the workspaces layout.
> 
> https://github.com/open-sauced/app/blob/8eb580dd723f81ef169af26830e74f2ed2a1fa42/components/Workspaces/WorkspaceLayout.tsx#L84-L88

I'll be adding the padding to each individual page, otherwise it would break the padding fix for the user page.

**Review by brandonroberts — APPROVED** [review]
LGTM 🍕

**Review by nickytonline — APPROVED** [review]
Works great! Thanks @zeucapua! 🚢 

CleanShot 2024-06-15 at 23 01 21

**Review by jpmcb — APPROVED** [review]

**Pull request merged**
