### PR TITLE
fix: make danger zone more dangerous

### LINKED ISSUE #2916: Suggestion: call to action / inform for "Danger zone"
### Describe the bug

This is just a suggestion, no action right now (cc @isabensusan), but the Danger Zone doesn't look _too_ dangerous:

Screenshot 2024-03-11 at 3 20 36 PM

(screenshot from https://github.com/open-sauced/app/pull/2912)

I wonder if we could do something / call to action that this 

### Steps to reproduce

N/a

### Browsers

Firefox

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by malezjaa**
## Description
This pr makes danger zone more "dangerous"

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Closes #2916

## Mobile & Desktop Screenshots/Recordings

screenzy-1710369148607

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by jpmcb — CHANGES_REQUESTED** [review]
The CSS breaks on screens of medium width. This was 1249x1300:

Screenshot 2024-03-25 at 9 58 11 AM

This also makes the experience between Repo Insights and Contirbutor insights inconsistent. If we're going to change this, we should change it consistently for all UIs.

cc @isabensusan for design.

**Comment by BekahHW** [comment]
@isabensusan can you verify what design you want to see here?

**Comment by bdougie** [comment]
> @isabensusan can you verify what design you want to see here?

FWIW the danger zone is modeled after GitHub's

image

What is represented currently in this PR could lean into our existing design system to create or something cohesive.

## my suggestion

Put items into grey box with distinct sections.

Make it make sense

**Comment by isabensusan** [comment]
@malezjaa thank you for your contribution! I see that you've based the design on GitHub's danger zone, but it'd be great if we could get it closer to what we have on our current design system. 

I threw this quick mock together, essentially:
- Move the "transfer to other workspace" section to the same gray box as the "delete" section
- Make the danger zone title `font-semibold text-lg text-red-600`

image

**Comment by malezjaa** [comment]
Hi I followed your comment. I also adjusted contributor insights page 

image

**Review by jpmcb — APPROVED** [review]
Looks solid to me! Thanks for the first time contribution!! 🚀🚀🚀

**Review by BekahHW — APPROVED** [review]

**Pull request merged**
