### PR TITLE
chore: Add OSCRs to upgrade modal

### LINKED ISSUE #3746: Feature: Add OSCR rating visibility to Pro Plan text in Modal
### Suggested solution

We're planning to put some of the OSCR visibility behind a paywall. Currently, when you need to upgrade, a modal pops up with the two pricing options. 

image

We need to add to that:

For Free Workspace: Up to 5 Contributor OSCRs per insight page

For Pro: Unlimited Contributor OSCRs per insight page

Depends on: https://github.com/open-sauced/app/issues/3744

### PR DESCRIPTION
**Pull request by BekahHW**
## Description

- Adds OSCR to Upgrade modal 

## Related Tickets & Documents

closes #3746 

## Mobile & Desktop Screenshots/Recordings

image

## Steps to QA

1. Go to a workspace and click or create a contributor insight page
2. Make sure there are more than 10 contributors
3. Click the upgrade warning
4. See the modal

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

**Review by jpmcb — COMMENTED** [review]
Copy looks great 👍🏼 

---

did we actually end up implementing this on the App? If you're logged in, on a repo page, you can see _all_ the oscrs across a contributors table.

If I remember correctly, last week we may have decided to punt on the pricing for this and just get it out there - cc @isabensusan

**Comment by nickytonline** [comment]
We don't have it at the moment, but we need to create these modals as drawers on mobile, probably with less text. cc: @isabensusan

**Comment by nickytonline** [comment]
> Copy looks great 👍🏼
> 
> did we actually end up implementing this on the App? If you're logged in, on a repo page, you can see _all_ the oscrs across a contributors table.
> 
> If I remember correctly, last week we may have decided to punt on the pricing for this and just get it out there - cc @isabensusan

I understood we punted as well.

**Comment by nickytonline** [comment]
Going to close this for now @BekahHW. Feel free to reopen it if we tackle this in the future.

**Pull request closed without merging**
