### PR TITLE
feat: Introduce v2 API and user PR Timescale integration

### PR DESCRIPTION
**Pull request by jpmcb**
## Description

This adds the new v2 API endpoint with Timescale integrations for `v2/users/{username}/prs`.

Refactors the base URL api fetcher to include a v2 api fetcher.

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Followup to:
- https://github.com/open-sauced/api/pull/442

## Mobile & Desktop Screenshots/Recordings

_Stay tuned ..._

## Steps to QA

_Stay tuned ..._

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

Will need to cordinate this going into prod with the new v2 endpoints in the API also going out beforehand.

### CODE REVIEW

**Comment by jpmcb** [comment]
Near live data flowing in:

Screenshot 2023-12-08 at 3 07 11 PM

A few notes here:
- we don't have much of a notion of "hours" for PRs that are newer than 1 day: you'll notice that it's just a "-" with really new PRs. This is probably fine for now, but we'll want to start re-thinking really new data.
- The graph breaks here ... looking into it!

@brandonroberts also showed me how to get around busting the app cache to get these to load. Otherwise, the app fails to load this page:

Screenshot 2023-12-08 at 3 08 40 PM

**Comment by jpmcb** [comment]
Force pushed to address the line graph using the wrong type:

Screenshot 2023-12-08 at 3 52 38 PM

**Comment by jpmcb** [comment]
I think this needs a few more changes on the API side to see this fully through: there is abit of intermixing of the the types for different functions I need changed.

So, this should really attempt to completely remove the `DbRepo` type in favor of the `DbRepoEvent` type.

**Comment by jpmcb** [comment]
Deploy preview is up with changes from https://github.com/open-sauced/api/pull/444

Although there's also `pr/insights` that needs to be updated in the API to _really_ round this out. But this could go in now if we want 🚀

**Comment by bdougie** [comment]
@jpmcb I don't see data on the deploy preview. Is that because we don't dev data for DbRepoEvent yet?

**Comment by jpmcb** [comment]
Yeah, good question: `users/{username}/prs` shows up primarily in the user profiles:

Screenshot 2023-12-20 at 10 11 00 PM

but you're right: `prs/search` seems abit more nuanced and I'm also not seeing it really pop up in the insight pages, I'll revisit this more tomorrow

**Comment by jpmcb** [comment]
I'm actually inclined to get this merged into a feature branch instead of `beta` (since there's alot more work to be done to get `prs/insights` integrated here.

How does a `pr-events` branch sound? I'd much rather tackle this in bit-sized chunks vs. one massive PR to `beta`

**Review by nickytonline — COMMENTED** [review]
Aside from introducing v2 stuff for the API, most of this is just updating property names from what I can tell?

**Review by nickytonline — APPROVED** [review]
:shipit: 

image

**Comment by jpmcb** [comment]
> Aside from introducing v2 stuff for the API, most of this is just updating property names from what I can tell?

More or less: it introduces a different type which aligns with what is returned by the v2 PR endpoints. This type drifts slightly from the existing type (for example, the event types don't have labels right now) so it made more sense to just refactor the type all together.

Also introduces a `v2PublicApiFetcher` API fetcher which can be used alongside the normal v1 API fetcher

**Review by brandonroberts — APPROVED** [review]
🚀

**Pull request merged**
