### PR TITLE
fix: now the repository insights pages header looks good on smaller screens

### LINKED ISSUE #3669: Bug: Repository insight page and Repository Insight new/edit pages spill out on mobile
Pages related to contributor insights do not work well on mobile.

New/Edit Repository Insight Page

CleanShot 2024-07-04 at 10 23 52

Repository insight page

CleanShot 2024-07-04 at 10 23 13

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Now the repository insights pages look good on smaller screens. Note that the Add Repositories wizard modal is still not responsive. It will be addressed in a separate PR as the wizard modal is used in a for contributor insights as well as tracked repositories for a workspace.

## Related Tickets & Documents

Fixes #3669

## Mobile & Desktop Screenshots/Recordings

**Before**

CleanShot 2024-07-04 at 15 33 48

CleanShot 2024-07-04 at 15 29 35

**After**

CleanShot 2024-07-04 at 15 34 46

CleanShot 2024-07-04 at 15 28 54

## Steps to QA

1. Go to a repository insight page from any workspace on your phone
2. Notice the dashboard, contributors and activity pages when navigated to, all look good on mobile.
3. Edit or create a new repository insight.
4. Notice it looks good on smaller screens.

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

**Review by isabensusan — CHANGES_REQUESTED** [review]
Looking much better! Can we add a tiny bit of padding to alerts and modals too?

ie. when successfully editing an insight I get this success alert
image

Or when adding more repositories I see this modal
image


and they both could use some very small padding to the sides, like so:
image

**Comment by nickytonline** [comment]
> Looking much better! Can we add a tiny bit of padding to alerts and modals too?
> 
> ie. when successfully editing an insight I get this success alert image
> 
> Or when adding more repositories I see this modal image
> 
> and they both could use some very small padding to the sides, like so: image

For the modals, they're going to be reworked into drawers in another PR, but I'll make the suggested changes.

**Comment by nickytonline** [comment]
Made the updates @isabensusan.

Before

CleanShot 2024-07-04 at 19 43 46

CleanShot 2024-07-04 at 19 46 04

After

CleanShot 2024-07-04 at 19 44 37

CleanShot 2024-07-04 at 19 44 56

**Review by brandonroberts — APPROVED** [review]

**Review by isabensusan — APPROVED** [review]
Thanks for this!! LGTM

**Review by jpmcb — APPROVED** [review]

**Pull request merged**
