### PR TITLE
fix: show highlights tab without highlights

### LINKED ISSUE #1628: Feature: User with not highlights have a blank screen
### Type of feature

🍕 Feature

### Current behavior

Screen Shot 2023-08-28 at 2 23 39 PM

### Suggested solution

1. View explore page
2. Click a user that has not create a highlight - https://insights.opensauced.pizza/user/andarist
3. Not the blank screen

### Additional context

related https://github.com/open-sauced/app/issues/1166

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by OgDev-01**
## Description
This pull request fixes the issue of returning a 404 error for not-found users, skips the e2e profile test temporarily, and resolves the problem of an empty user profile display. Additionally, it fixes the unknown tab redirect issue.

### TODO

- [x] set default tab to contributions when user have no highlight
- [x] show highlight tab with a call to action to create new highlight for logged in user profile

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
Fixes #1628

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

https://github.com/open-sauced/app/assets/62995161/7c8e366a-854a-467a-939c-0cc50a19de20

### CODE REVIEW

**Comment by OgDev-01** [comment]
#1613 needs to be merged before this implementation is concluded to avoid conflicts

**Review by babblebey — COMMENTED** [review]
Hi @OgDev-01, is this PR still WIP!?

I ask because the users who don't have github connected still redirects to 404 in the deployment.

https://deploy-preview-1631--oss-insights.netlify.app/user/githubuser

______
### Update

I didn't ready correctly... It was the intention!

LG 🍕

I will leave this comment here as a note to update the e2e test once the PR merges. 

https://github.com/open-sauced/app/blob/64aa404e30b0cdbe832136f3044f4e7126386b81/e2e-tests/OpenUserProfile.spec.ts

**Comment by jpmcb** [comment]
> I ask because the users who don't have github connected still redirects to 404 in the deployment.
> I didn't ready correctly... It was the intention!

_Is_ that what we want? This may lead to some gnarly UI/UX edges. For example, if I click on someone's profile in the explore tab and they aren't a user, it redirects to 404. I'd expect clicking on someone's user profile that seems to have data from the explore view that i would be able to see some sort of data from it.

1. Click user in explore view: https://deploy-preview-1631--oss-insights.netlify.app/user/acristoffers

Screenshot 2023-08-29 at 12 49 53 PM

2. Redirected to 404:

Screenshot 2023-08-29 at 12 50 11 PM

**Comment by babblebey** [comment]
> I'd expect clicking on someone's user profile that seems to have data from the explore view that i would be able to see some sort of data from it.

True @jpmcb, getting the contribution tab for an un-authed user as is in the current set-up, is very much insights about the user and that just about open-sauced/app generally.

There so many un-authed users with more insights to display that authed one too.

**Comment by bdougie** [comment]
> Is that what we want? 

This is a confusing part of our data a user is someone we indexed, but a connected user is someone that connected their github. 

We still need to show profiles for indexed users we have a github handle for in the users table, it should not 404.

If we search for anadarist it should 404. _Correct spelling is andarist_

**Comment by brandonroberts** [comment]
@jpmcb is correct. We still want to show contributors who haven't connected there account and show the orange circle and the blank background.

Current/Dev example: https://beta.insights.opensauced.pizza/user/mojombo?tab=contributions

image

**Comment by OgDev-01** [comment]
I had this thoughts in mind while working on this... the current implementation redirects to 404 if the user is not in the opensauced database, but the reality is to show the profile with  `contributions` tab for any GitHub user and only redirect to 404 when the user is not a github user.

### Example implementation
image

But this is will hit GitHubs rate limit without a token provided.

**Comment by OgDev-01** [comment]
Update: I have reverted the 404 redirect until to move this on until we decide the best approach to supporting all indexed users
I've opened a discussion for that [here](https://github.com/open-sauced/ops-backend/issues/128)

cc: @bdougie @brandonroberts @jpmcb

**Review by bdougie — APPROVED** [review]
updated the title, since this does not address the 404. I'd love to see get addressed in a follow up PR.

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
