### PR TITLE
feat: add button to copy DevCard image to clipboard

### PR DESCRIPTION
**Pull request by brandonroberts**
## Description

- Adds a "Copy To Clipboard" button to the Dev Card share button to copy the dev-card image to the clipboard for easy sharing
- Added a `children` prop to the `SocialButtons` to avoid refactoring the new button in.
- Should land after https://github.com/open-sauced/app/pull/3941 is merged

## Mobile & Desktop Screenshots/Recordings

https://github.com/user-attachments/assets/5be944c9-c8b6-4d17-9970-d89c740aa307

## Steps to QA

1. Go to a DevCard
2. Click on copy button
3. Paste image into a chat or social media platform

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

**Review by isabensusan — CHANGES_REQUESTED** [review]
Can we make the copy button match the other buttons? Using open-sauced orange as the background

image

**Comment by isabensusan** [comment]
Also -- can we add a loading state? replace the copy icon in the button with a loading icon? It took a bit for mine to load and I wasn't sure if it was working or not.

Image is looking good! Is there a chance to make it slightly higher-res though? If I paste it in a tweet, it looks grainy when enlarged
image

**Review by nickytonline — CHANGES_REQUESTED** [review]
This works well in a Chromium browser and Firefox, but on Safari mobile, nothing happens. I'm guessing browser security issues, kind of like we had with copy text a while back.

I couldn't test on Safari on macOS because the buttons don't appear, but that is probably related to #3941

**Comment by brandonroberts** [comment]
> Also -- can we add a loading state? replace the copy icon in the button with a loading icon? It took a bit for mine to load and I wasn't sure if it was working or not.
> 
> Image is looking good! Is there a chance to make it slightly higher-res though? If I paste it in a tweet, it looks grainy when enlarged image

The image is downloaded as-is, so maybe we need a higher-res image template? @nickytonline 

@isabensusan do we have a loading state for buttons elsewhere?

**Comment by brandonroberts** [comment]
@isabensusan Updated styles and loading spinner added 

https://github.com/user-attachments/assets/5be944c9-c8b6-4d17-9970-d89c740aa307

**Comment by brandonroberts** [comment]
> This works well in a Chromium browser and Firefox, but on Safari mobile, nothing happens. I'm guessing browser security issues, kind of like we had with copy text a while back.
> 
> I couldn't test on Safari on macOS because the buttons don't appear, but that is probably related to [#3941 (review)](https://github.com/open-sauced/app/pull/3941#pullrequestreview-2236426441)

I moved the copy call inside the `onClick` callback. That should resolve it

**Comment by nickytonline** [comment]
> > Also -- can we add a loading state? replace the copy icon in the button with a loading icon? It took a bit for mine to load and I wasn't sure if it was working or not.
> 
> > 
> 
> > Image is looking good! Is there a chance to make it slightly higher-res though? If I paste it in a tweet, it looks grainy when enlarged image
> 
> 
> 
> The image is downloaded as-is, so maybe we need a higher-res image template? @nickytonline 
> 
> 
> 
> @isabensusan do we have a loading state for buttons elsewhere?

The image is high res if taking the OG image.

**Comment by nickytonline** [comment]
> > This works well in a Chromium browser and Firefox, but on Safari mobile, nothing happens. I'm guessing browser security issues, kind of like we had with copy text a while back.
> > I couldn't test on Safari on macOS because the buttons don't appear, but that is probably related to [#3941 (review)](https://github.com/open-sauced/app/pull/3941#pullrequestreview-2236426441)
> 
> I moved the copy call inside the `onClick` callback. That should resolve it

Looks like the copy attempts now, but fails. I'm going to have to connect my phone and debug it. 🫠 

image

**Comment by nickytonline** [comment]
This should be helpful @brandonroberts, https://web.dev/articles/async-clipboard#write

From the web.dev docs

> Warning: Safari (WebKit) treats user activation differently than Chromium (Blink) (see [WebKit bug #222262](https://bugs.webkit.org/show_bug.cgi?id=222262)). For Safari, run all asynchronous operations in a promise whose result you assign to the ClipboardItem: js new ClipboardItem({ 'foo/bar': new Promise(async (resolve) => { // Prepare `blobValue` of type `foo/bar` resolve(new Blob([blobValue], { type: 'foo/bar' })); }), })

**Comment by brandonroberts** [comment]
Thanks @nickytonline. I adjusted the clipboard copy process and tested on Safari and it works correctly.

**Review by nickytonline — APPROVED** [review]
Tested it agan on iOS Safari and all good. Thanks @brandonroberts! 🚢 

IMG_30E18CC648BE-1

**Comment by nickytonline** [comment]
> Also -- can we add a loading state? replace the copy icon in the button with a loading icon? It took a bit for mine to load and I wasn't sure if it was working or not.
> 
> Image is looking good! Is there a chance to make it slightly higher-res though? If I paste it in a tweet, it looks grainy when enlarged image

We can probably just add our spinner loader. Take a peek at the share menu in StarSearch. Also, @isabensusan, thoughts on adding the same border on the copy button?

**Comment by brandonroberts** [comment]
The loading spinner on the copy button is added also

**Comment by brandonroberts** [comment]
I haven't seen that. I tested on Desktop and mobile with Android

**Comment by bdougie** [comment]
> I haven't seen that. I tested on Desktop Chrome and Safari, and mobile with Android

This mobile safari. Worth opening an issue for this. Seems to also happen when navigating.

But copy and pasting works on iOS.

**Review by bdougie — APPROVED** [review]

**Pull request merged**
