### PR TITLE
fix: workspaces sidebar opens over content now

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Now the workspaces sidebar opens over content instead of expanding/collapsing. **Post-workspaces MVP, we'll have it expanding/collpasing for larger breakpoints.**

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Mobile & Desktop Screenshots/Recordings

**Before**

CleanShot 2024-02-22 at 09 47 24

**After**

CleanShot 2024-02-22 at 09 46 04

## Steps to QA

1. Ensure you're logged in
2. Go to any workspace
3. Notice the side bar pops over content when opened.

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by bdougie** [comment]
I understand this a WIP. Just leaving a note to make sure the sidebar starts closed on mobile.

**Comment by nickytonline** [comment]
> I understand this a WIP. Just leaving a note to make sure the sidebar starts closed on mobile.

Will do.

**Review by jpmcb — APPROVED** [review]
When I open up the deploy preview:

Screenshot 2024-02-22 at 8 46 11 AM

it's abit jarring that the content is hidden behind the sidebar when it first opens. But looks like this will get some love post MVP, so happy to move this forward

**Comment by nickytonline** [comment]
> A bit of a nit, but can we make the sidebar close when clicking outside of its area?

Great suggestion. Will do.

**Comment by nickytonline** [comment]
> When I open up the deploy preview:
> 
> Screenshot 2024-02-22 at 8 46 11 AM
> 
> it's abit jarring that the content is hidden behind the sidebar when it first opens. But looks like this will get some love post MVP, so happy to move this forward

There's a flash which causes the jarring effect. We're using a hook that uses local storage and that's what causes the flash. I'm going to use local storage directly so it doesn't flash.

**Comment by nickytonline** [comment]
> I understand this a WIP. Just leaving a note to make sure the sidebar starts closed on mobile. 

Done

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
