### PR TITLE
feat: make app sidebar collapsible

### LINKED ISSUE #2527: Feature: Make the app sidebar collapsible
As a a user, I want a collapsible side bar so that I can have the most page real estate possible.

CleanShot 2024-01-25 at 11 57 19

Use this icon from [HeroIcons](https://heroicons.com/) to open and close the side bar.

CleanShot 2024-01-25 at 11 58 46

### PR DESCRIPTION
**Pull request by zeucapua**
## Description

Implements a button in `WorkspaceLayout` that shows/hides the sidebar. Currently put next to the logo. Placement is temporary until we have a design. By default, the sidebar is visible. Will implement a way to make sidebar state carry between pages.

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Closes #2527 

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/app/assets/20603494/c6875065-dc69-4d46-a273-619f986957d0

## Steps to QA

1. Go to any `/workspace` page
2. Press the button on the left of the logo in the top nav bar
3. See if the sidebar shows and collapses correctly

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

awkward-season-4-gif-by-the-office

### CODE REVIEW

**Comment by zeucapua** [comment]
@isabensusan I would love your review and a design in terms of placement for the sidebar button.

**Comment by nickytonline** [comment]
> @isabensusan I would love your review and a design in terms of placement for the sidebar button.

This is the icon we want to use. If it's not in the project, you can grab it from https://heroicons.com/

image

The icon is too far away from our logo. I believe the collapse button goes in the sidebar are as opposed to the top nav, but I'll let Isa chime in.

**Comment by zeucapua** [comment]
@isabensusan gave me a few mockups! I will be adding the button beside the workspace select and add a lapel button when collapsed.
image
image

Also trying out this icon:
image

**Comment by bdougie** [comment]
I was messing with this and had two thoughts.

This would feel better if there was an ease-in animation or similar.

Kind of jarring to collapse.

Also realize no mobile considerations have been made for workspaces, but it be nice to have the sidebars collapse on mobile by default.

**Comment by nickytonline** [comment]
> I was messing with this and had two thoughts.
> 
> This would feel better if there was an ease-in animation or similar.
> 
> Kind of jarring to collapse.
> 
> Also realize no mobile considerations have been made for workspaces, but it be nice to have the sidebars collapse on mobile by default.

We'll be doing polish for the mobile experience including sidebar work which will be done next week, probably early week.

**Review by jpmcb — COMMENTED** [review]
Screenshot 2024-02-14 at 2 20 04 PM

Obligatory "i'm not a designer (lol)" - This spacing seems cramped to me. Collapsing the sidebar makes this spacing (with the arrow) feel very tight.

I liked the initial design / implementation where the collapse button was static in the header:

Screenshot 2024-02-14 at 2 26 15 PM

But I'll defer to others!

**Review by bdougie — APPROVED** [review]
I'd love to see this get merged and polished next week in a separate pr

**Review by jpmcb — APPROVED** [review]

**Pull request merged**
