### PR TITLE
fix: use custom text-area component for bio

### LINKED ISSUE #2046: Bug: style of bio section is not uniform like other input fields
### Describe the bug

<b>Problem</b>
In the user's settings page i.e., <code>/user/settings</code> all input fileds have uniform styles except the <b>Bio</b> section.

<b>Expected</b>
after

<b>Observed</b>
before

<b>Note</b>
The above screenshots is shown only for border property of the component. But the whole bio section has different styling.

<b>Solution</b>
The input field in the settings page is created using a component called <b>TextInput</b>. Similarly, in for the bio field Textarea component must be used. [Textarea](https://github.com/open-sauced/app/blob/beta/components/atoms/Textarea/text-area.tsx)

If the suggested solution is fine then I can work on this.
Thank you.

### Steps to reproduce

1. Go to settings page after logging in.
2. check the styling of Bio section.

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by itskish0re**
## Description
Fixed design of bio section. Replaced in-built textarea with Textarea component.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [X] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [X] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
Fixes #2046

#### Before
image

#### After
image

#### Before
image
#### After
image

#### Before
image
#### After
image

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [X] 🙅 no documentation needed

### CODE REVIEW

**Comment by nickytonline** [comment]
@itskish0re, thanks for the PR!

This relates to work we have around setting some base styling for all elements in the app, e.g. focus states for form elements. For this current issue, let's avoid updates to the custom textarea component. For now, replicate the focus styles directly on the bio textarea. We'll have some near future work that will render focus styles uniform in the app. See https://github.com/open-sauced/app/issues/2149#issuecomment-1811762611

**Review by nickytonline — CHANGES_REQUESTED** [review]
@itskish0re, thanks for the PR!

This relates to work we have around setting some base styling for all elements in the app, e.g. focus states for form elements. For this current issue, let's avoid updates to the custom textarea component. For now, replicate the focus styles directly on the bio textarea. We'll have some near future work that will render focus styles uniform in the app. See https://github.com/open-sauced/app/issues/2149#issuecomment-1811762611

**Comment by itskish0re** [comment]
@nickytonline, I have made the changes.

**Review by nickytonline — APPROVED** [review]
Works great! Thanks @itskish0re!

**Review by BekahHW — APPROVED** [review]

**Pull request merged**
