### PR TITLE
fix: add mobile drawer for `InsightUpgradeModal`

### LINKED ISSUE #3391: Bug: Modal for upgrading should use a drawer instead on smaller screens
This will be a similar implementation to #3368.

image

From @bdougie:
              > This is a good solution. Can we do the same for the upgrade banner in a new PR?!
> 
> [image](https://github.com/open-sauced/app/assets/5713670/c421758b-c4ae-41df-a75d-2a9444179345)

🫡

_Originally posted by @nickytonline in https://github.com/open-sauced/app/issues/3386#issuecomment-2112408812_

### PR DESCRIPTION
**Pull request by zeucapua**
## Description

Implement drawer for `InsightUpgradeModal` that shows if user is on mobile.

## Related Tickets & Documents

Closes #3391 

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/app/assets/20603494/79df895e-5021-4f0c-8946-6d808dde5073

## Steps to QA

1. Go to a non-PRO workspace
2. Click the upgrade banner
3. Ensure you see a drawer, not a modal

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

## [optional] What gif best describes this PR or how it makes you feel?

snack-time-pull-drawer-gif

### CODE REVIEW

**Review by brandonroberts — APPROVED** [review]
Works great! 🍕 

Tested with switching between mobile/desktop while the modal is open

**Review by jpmcb — COMMENTED** [review]
Tried it out - looks great, works great.

Noticed the popup gets cut off at certain sizes, somewhere between the collapsed mobile view and the smaller stacked view: maybe the drawer needs to be abit more aggressive on when it pops up?

drawer

**Comment by zeucapua** [comment]
Should go to drawer wider now:

https://github.com/open-sauced/app/assets/20603494/b616939a-0378-459f-90a4-d0b6a3d5189e

**Review by jpmcb — APPROVED** [review]
👍🏼 😎 👍🏼

**Pull request merged**
