### PR TITLE
feat: fixing - feedback - Default view for Stars and Forks graph should be time-series

### LINKED ISSUE #3862: Feature: feedback - Default view for Stars and Forks graph should be time-series
### Suggested solution

We've gotten feedback that the default view for the stars and forks graph should be the time-series. Right now, when you go to a repo page, you'll see the histograms view:

Screenshot 2024-08-05 at 5 09 22 PM

This is valuable data. But it seems that people generally want to see "number go up" vs. trend / bucket data over a histogram. Here's that same repo page but with the time-series which shows a steady growth:

Screenshot 2024-08-05 at 5 10 28 PM

---

We'll want to decide if this is what we want to do or if we want to distinguish our platform with being opinionated for the histograms.

### PR DESCRIPTION
**Pull request by SURAJ-SHARMA27**
## Description

Fixes  #3862 
I have replaced the previous bar charts with area charts in the star graphs. I have submitted this as a draft PR. If it works well, I will implement this change throughout.

## Related Tickets & Documents

Fixes #3862 

## Mobile & Desktop Screenshots/Recordings

image

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [ ] Tier 4

### CODE REVIEW

**Comment by SURAJ-SHARMA27** [comment]
Should I proceed with creating an area graph under the time series for each plot on the repo page (Stars and forks)? @jpmcb @BekahHW

**Comment by jpmcb** [comment]
cc @isabensusan - any thoughts on the design here?

**Comment by SURAJ-SHARMA27** [comment]
Hey everyone,

Should I proceed with the proposed idea?

**Comment by brandonroberts** [comment]
@SURAJ-SHARMA27 I believe the original issue to be resolved was just changing the default. We can revisit changing the style of the chart separately.

**Comment by isabensusan** [comment]
@SURAJ-SHARMA27 thanks for your contribution! But like @brandonroberts mentioned, if you take a close look at the original issue [#3862](https://github.com/open-sauced/app/issues/3862) the goal was to just change the default view for the stars and forks charts from Daily to History. 

We are not currently looking to update the design of these charts, so I'll be closing this PR, but if you want to tackle changing the default view in a different PR you are welcome to do so!

**Comment by SURAJ-SHARMA27** [comment]
Okay, I understand. Should I just convert the stars and forks graph into a time-series graph as mentioned in the original issue?

**Comment by nickytonline** [comment]
I'm not sure where we landed on this @open-sauced/design @open-sauced/engineering.

**Comment by nickytonline** [comment]
I'm going to go ahead and close this for now. Feel free to reopen it if you want to continue working on this @SURAJ-SHARMA27.

**Pull request closed without merging**
