### PR TITLE
fix: fixed scrolling issues with StarSearch

### LINKED ISSUE #3403: Bug: buggy scrolling on starsearch
### Describe the bug

Right now, both the chat and the wrapper scroll, making for a strange scrolling behaviour

Rewatch GIF Recording - 2024-05-16 at 1 36 05 PM

### Steps to reproduce

1. Go to '/starsearch'
2. Ask a question
3. Get response and try to scroll to the bottom

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Fixes the scrolling issues in StarSearch, now only the prompt/response area scrolls. To accomodate the changes, there have been some modifications to the smaller screen experience.

* The title and description are now centered on the screen for smaller screens
* The initial suggestions are no longger boxes on the initial load of the page. The need inpspiration button opens the drawer if they need a suggestion

For larger screens:
* Sizing of the scroll area has been modified to accomodate when the clear chat history and feedback buttons are present.
* when the suggestions are open, the scroll area height adjust accordingly.

## Related Tickets & Documents

Fixes #3403

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/app/assets/833231/cf2746f9-4a9d-44ba-920c-73c9113a7933

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

**Comment by BekahHW** [comment]
@nickytonline the tests are failing.

**Comment by nickytonline** [comment]
@isabensusan, note that this does not fix the gradient at the top. It's related to this PR and sorting this one took out a little longer than expected. I'll have a small follow up PR for that tomorrow.

**Comment by nickytonline** [comment]
> @nickytonline the tests are failing.

Yeah, looks like an E2E test timed out. It's not related to the PR so I restarted them. I'll see shortly if it's still failing.

**Review by BekahHW — APPROVED** [review]
Works for me on mobile.

**Review by jpmcb — APPROVED** [review]

**Review by isabensusan — APPROVED** [review]
scrolling is much better!! but now the container seems even shorter. PR is good to merge, let's sync about other changes tomorrow :)

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
