### PR TITLE
feat: use GitHub API for user search box

### PR DESCRIPTION
**Pull request by brandonroberts**
## Description

- Updates the user searchbox in the top bar to use the GitHub search API for users
- Uses the available GitHub token for authenticated users
- Allows GitHub search options to be used  like `user:name`, `location:state
## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Related to: https://github.com/open-sauced/engineering/issues/206

## Mobile & Desktop Screenshots/Recordings

BEFORE:

image

AFTER:

image

## Steps to QA

1. Click on "Search for users"
2. Enter a `user:{username}` search term, for example: `user:bdougie`
3. See search results
4. Click on user to navigate to their profile

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by jpmcb — APPROVED** [review]
Huge!! 🕵️

**Review by bdougie — APPROVED** [review]
LGTM

**Review by nickytonline — APPROVED** [review]
image

**Review by bdougie — APPROVED** [review]
This is a good change and opens us up to do similar things like repo:reponame in the future.

No need to re train GitHub users

**Pull request merged**
