### PR TITLE
fix: TopNav highlight if in Insight pages

### LINKED ISSUE #2595: Bug: Wrong Tab is Highlighted in the Nav Bar
### Describe the bug

While on one of my insight pages, I realized that the "active" tab was Explore.

image

### Steps to reproduce

1. Go to an insight page (this isn't replicated on lists)
2. See Explore in orange

### Browsers

Chrome

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by zeucapua**
## Description

The top navigation bar incorrectly highlights the `Explore` tab while in an Insight page. This PR fixes that with a check against the router.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [X] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2595 

## Steps to QA

1. Go to any Insight page
2. Confirm that the top nav has `Insights` is highlighted

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [X] 🙅 no documentation needed

### CODE REVIEW

**Comment by isabensusan** [comment]
congrats on your first PR!!!

A small detail, but when I'm on the Insights hub, the 'Insights' link in the navbar is highlighted
image


But on the Highlights feed or the Explore page the link is missing the active state
image

image

can we make it so all the navbar links get an active state when the user is on their respective pages?

**Comment by zeucapua** [comment]
> congrats on your first PR!!!
> 
> A small detail, but when I'm on the Insights hub, the 'Insights' link in the navbar is highlighted image
> 
> But on the Highlights feed or the Explore page the link is missing the active state image
> 
> image
> can we make it so all the navbar links get an active state when the user is on their respective pages?

weird since I didn't touch those conditionals, I'll look into it!

**Comment by isabensusan** [comment]
🎨

**Review by nickytonline — APPROVED** [review]
Thanks @zeucapua! 🚢

**Pull request merged**
