### PR TITLE
fix: chart tooltip cut in contributors card

### LINKED ISSUE #1912: Bug: User Activity Data is Cut Off During Mouse Over Contributors Page
### Describe the bug

https://github.com/open-sauced/app/assets/48575398/a5337526-3034-44bf-be58-d871979892b5

User data is being cut off when hovering mouse over their activity's box.

### Steps to reproduce

1. Go to Contributors tab
2. Hover mouse over user data

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by OgDev-01**
## Description
This PR fixes the chart tooltip cut issue with the contributors card

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
fixes #1912 

### Before

https://github.com/open-sauced/app/assets/62995161/f2188f4b-6ce4-4a2e-8c5d-ee70becccd4c

### After
https://github.com/open-sauced/app/assets/62995161/120661e8-b638-4ec1-84fb-53bff87d62be

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by nickytonline** [comment]
Looking at the graphs on https://deploy-preview-2032--oss-insights.netlify.app/hacktoberfest/contributors/filter/recent, somw graphs are still being cut off.

CleanShot 2023-11-01 at 09 31 24

**Review by brandonroberts — APPROVED** [review]

**Comment by OgDev-01** [comment]
> Looking at the graphs on [deploy-preview-2032--oss-insights.netlify.app/hacktoberfest/contributors/filter/recent](https://deploy-preview-2032--oss-insights.netlify.app/hacktoberfest/contributors/filter/recent), somw graphs are still being cut off.
> 
> CleanShot 2023-11-01 at 09 31 24

Here is the right link https://deploy-preview-2029--oss-insights.netlify.app/hacktoberfest/contributors/filter/recent

**Comment by nickytonline** [comment]
> Here is the right link [deploy-preview-2029--oss-insights.netlify.app/hacktoberfest/contributors/filter/recent](https://deploy-preview-2029--oss-insights.netlify.app/hacktoberfest/contributors/filter/recent)

Even that link results in cut off graphs still. 🤔 

CleanShot 2023-11-01 at 10 42 46

**Comment by OgDev-01** [comment]
This PR solves the hover cut-off as stated in https://github.com/open-sauced/app/issues/1912. We have a seperate issue for the graph top cut-off here https://github.com/open-sauced/app/issues/1285.

**Review by nickytonline — APPROVED** [review]

**Pull request merged**
