### PR TITLE
fix: added missing page numbers

### LINKED ISSUE #2362: Bug: Missing page numbers for pagination
### Describe the bug

Missing page number and page size for pagination in 
1. Contributors organism

### Steps to reproduce

1. Go to Explore page 
2. Check the Contributors list footer

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by sourabpramanik**
added missing page numbers for pagination

## Description

This PR fixes the missing page numbers in the Contribution table.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [X] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2362

## Mobile & Desktop Screenshots/Recordings

Before fix
image

After fix
fix

## Steps to QA
1. Go to Explore page
2. Go to Contributors tab
3. Scroll down to the bottom of the table
4. Check the pagination area

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [X] 🙅 no documentation needed

### CODE REVIEW

**Comment by nickytonline** [comment]
I'm not sure if we want the page numbers links for these views. I believe @open-sauced/design had it set that way, so just checking in with them @sourabpramanik. I'm going to close this PR temporarily until we get confirmation from them that this is what they want. I've noted this in the issue as well.

**Comment by sourabpramanik** [comment]
> I'm not sure if we want the page numbers links for these views. I believe @open-sauced/design had it set that way, so just checking in with them @sourabpramanik. I'm going to close this PR temporarily until we get confirmation from them that this is what they want. I've noted this in the issue as well.

Not a problem thank you @nickytonline

**Comment by sourabpramanik** [comment]
Yes @isabensusan we can update the state of the pagination after the table loading has finished.

**Comment by OgDev-01** [comment]
Re-opened this as approved... @sourabpramanik feel free to add the additional enhancement requested if you have the bandwidth 👍. Also mention if you can't so we can ship as is and revisit in another PR

**Comment by sourabpramanik** [comment]
Thanks @OgDev-01 
I will make the requested changes in this.

**Comment by sourabpramanik** [comment]
Hey @isabensusan I have added the fix like you mentioned, now we can persist the pagination data while we are fetching the new records and update the active page number once we have got the new records and loading has finished. I have also added the loading animation for grid view which was not there when we paginate.
fix

**Comment by sourabpramanik** [comment]
Hey @isabensusan the changes that you requested are done and also I have added couple of condition checks to show skeleton loading while data is being fetched when we paginate for grid view.

**Review by nickytonline — APPROVED** [review]
Thanks for this @sourabpramanik!

:shipit:

**Review by jpmcb — APPROVED** [review]
Super solid from the engineering side! 🥇

**Comment by sourabpramanik** [comment]
Thank you so much @jpmcb means a lot 🙏

**Pull request merged**
