### PR TITLE
fix: Adding new repos to insights on edit page will trigger another API call

### LINKED ISSUE #2475: Bug: PRs display 0 when you're adding a repo to an insight page
### Describe the bug

When you're adding to an existing insight page, any additions show up as 0 PRs. 

Screenshot 2024-01-16 at 10 42 29 AM

### Steps to reproduce

1. Either edit or create a new insight page
2. Add a repo
3. See the 0

Note: Once you save the repo, the numbers are updated.

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by aryanas159**
## Description
fixes #2475
This PR fixes the issue, which was caused because when adding new repositories on the insights page, the response for each API call didn't return the number of PRs, so I used the useRepositories hook which reinitiates the API call every time the repos are added or removed. I did my best to solve this problem, but it might not be the best solution, I am willing to make any further changes required to fix this issue.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/app/assets/114330931/b8dfae50-53a6-4e7a-ad6d-026e8ddc246a

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by jpmcb — APPROVED** [review]
Approved the Netlify build request: looks solid 👍🏼

**Comment by brandonroberts** [comment]
Thanks @aryanas159. My reservation is that we're using the same `useRepositories` hook twice to do a similar thing. Can we not use the `pageRepos` mapped to the initial set of `repoIds` for the hook?

We can also refresh the insight repositories using the `mutate` function returned with the hook.

**Comment by aryanas159** [comment]
@brandonroberts I have made the change that uses mutate to reinitiate API calls, could you please review it?

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
@aryanas159 will you take a look at the build failure?

**Comment by aryanas159** [comment]
@brandonroberts it looks good now.

**Comment by jpmcb** [comment]
@aryanas159 - this is failing in netlify:

```
10:27:38 AM: Failed to compile.
10:27:38 AM: 
10:27:38 AM: ./pages/hub/insights/new.tsx:9:11
10:27:38 AM: Type error: Type "{}" is missing the following properties from type "InsightPageProps": pageReposMeta, mutate, setCurrentRepoIds
10:27:38 AM:    7 | const NewInsightPage: WithPageLayout = () => {
10:27:38 AM:    8 |   useSession(true);
10:27:38 AM: >  9 |   return <InsightPage />;
10:27:38 AM:      |           ^
10:27:38 AM:   10 | };
10:27:38 AM:   11 | 
10:27:38 AM:   12 | NewInsightPage.PageLayout = HubLayout;
10:27:38 AM: ​
10:27:38 AM: "build.command" failed                                        
```

likely because we just did a huge fast forward on beta from abunch of alpha changes: #2532. You'll want to rebase your changes onto what's currently in `beta`.

**Comment by aryanas159** [comment]
@jpmcb Is the build ok now?

**Pull request merged**
