### PR TITLE
refactor: remove `/hub` and `/pages` subfolder routing

### PR DESCRIPTION
**Pull request by zeucapua**
## Description

Remove `/hub` and `/pages` routing.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by jpmcb — COMMENTED** [review]
Sounds solid to me, although, I'll punt to others since I don't have great context on how the page routing was originally set up 🏈

**Comment by brandonroberts** [comment]
Removing the pages/[pageId]/* routes breaks the explore page and associated filter pages

/javascript - topic
/javascript/(dashboard/contributors/activity) - topic tabs
/javascript/dashboard/filter/(recent/top100/etc) - filters
/javascript/dashboard/filter/open-sauced/app - specific repo

The pages/pages/* and hub/* routes can be removed safely

**Comment by brandonroberts** [comment]
We should revisit whether we want to redirect those and put them under a /topic path or put repo pages under a /repo path

**Comment by nickytonline** [comment]
> Removing the pages/[pageId]/* routes breaks the explore page and associated filter pages
> 
> /javascript - topic /javascript/(dashboard/contributors/activity) - topic tabs /javascript/dashboard/filter/(recent/top100/etc) - filters /javascript/dashboard/filter/open-sauced/app - specific repo
> 
> The pages/pages/* and hub/* routes can be removed safely

What @brandonroberts  mentioned. I thought it was a different route being removed. We can also maybe just revise how the `explore` route works as it's the only affected route? It relates to https://github.com/open-sauced/app/issues/2600

**Comment by bdougie** [comment]
I am all for whatever is decided as long as we setup a 301 to the new place. But sounds like a quick chat around what the new explore page could like @isabensusan

**Comment by zeucapua** [comment]
Talked with @isabensusan and @nickytonline, current plan related to #2600 is to remove `/hub` and `/pages` as @brandonroberts said while we move the `/[pageId]` under a **new** `/explore` route in a separate PR.

That way we can eventually add a dedicated Explore page  that will have a search and featured repos/workspaces in the future (a la https://hot.opensauced.pizza), and clear the catchall to pave way for the repo pages being under the `/[org]/[repo]` route.

**Review by brandonroberts — APPROVED** [review]

**Review by jpmcb — APPROVED** [review]

**Pull request merged**
