### PR TITLE
feat: MVP `OssfChart` component

### LINKED ISSUE #3765: Feature: MVP `OssfChart` component
### Suggested solution

Implement an MVP of component and storybook for #3742 with mock data. This will be added to the repository pages once it is [integrated in the API](https://github.com/open-sauced/api/issues/962). 

Design from #3742 
image

### PR DESCRIPTION
**Pull request by zeucapua**
## Description

Creates `OssfChart` component, with Storybook testing. To be implemented into repo pages once the score is [implemented in the API](https://github.com/open-sauced/api/issues/962) in a future PR.

## Related Tickets & Documents

Closes #3765 

## Mobile & Desktop Screenshots/Recordings
Area

**Error state changes:**

image

## Steps to QA

1. Go to storybook deploy and open `OssfChart` under 'Repository'
2. Change the `totalScore` to a number from 0 to 10 or `null`
3. Toggle the `isLoading` and `isError` booleans
4. See the different states

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [x] Tier 3
- [ ] Tier 4

### CODE REVIEW

**Review by jpmcb — COMMENTED** [review]
Great work!

I think we'll also want to include a "not yet calculated" state. The default for the metadata from the API for repo entities is:

```json5
{
  "id": 585402612,

  // etc. etc. other metadata

  "ossf_scorecard_total_score": null,
  "ossf_scorecard_dependency_update_score": null,
  "ossf_scorecard_fuzzing_score": null,
  "ossf_scorecard_maintained_score": null,
  "ossf_scorecard_updated_at": "1970-01-01T00:00:00.000Z",
}
```

Which indicates that the `scorecard-k8s-scheduler` hasn't yet gotten to it yet. This will happen for new repo that get add to the app database from GitHub. But eventually, once the scheduler catches up, it should pick up those that have null data pretty quickly.

Worth noting for a future iteration, a "Last Calculated" indicator might be interesting. The `scorecard-k8s-scheduler` will try its best to update repos on a bi-weekly basis. Any faster and we'd have to scale that operation up but would maybe be worth letting user's know when the scorecard was last calculated.

Curious what you think @isabensusan?

**Comment by zeucapua** [comment]
New error state design. Thoughts? @jpmcb @isabensusan @BekahHW 

image

**Comment by isabensusan** [comment]
> New error state design. Thoughts? @jpmcb @isabensusan @BekahHW
> 
> image

LGTM! Some small comments:
- Let's make the gauge color gray instead of red
- Replace the "X" with a "-"
- There's a small typo in the copy

**Comment by zeucapua** [comment]
Error state changes! @isabensusan 

image

**Review by isabensusan — APPROVED** [review]
LGTM!

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
