### PR TITLE
fix: repo logo overlaps search bar in mobile view on repo pages fixed

### LINKED ISSUE #3986: Bug: repo logo overlaps search bar in mobile view on repo pages
### Describe the bug

On mobile view, within repo pages, when searching, notice how the repo logo overlaps the search bar:

Screenshot 2024-08-19 at 11 46 20 AM

Probably a z index problem: the search bar should be the most forefront thing on the repo page when searching.

### Steps to reproduce

1. Go to a repo page using mobile view (use browser dev tools): https://app.opensauced.pizza/s/kubernetes/kubernetes
2. Hit the search icon
3. Notice the icon overlaps the search results / search bar

### PR DESCRIPTION
**Pull request by SURAJ-SHARMA27**
## Description

Fixes issue #3986: The repository logo appeared in front of the backdrop when the search bar was opened. I resolved this by setting a lower zIndex.

## Related Tickets & Documents

Fixes #3986

## Mobile & Desktop Screenshots/Recordings

[screen-capture (30).webm](https://github.com/user-attachments/assets/26793e4e-c496-4ef9-9de5-444d956a09c4)

## Steps to QA

1. Go to a repo page using mobile view (use browser dev tools): https://app.opensauced.pizza/s/kubernetes/kubernetes
2. Hit the search icon
3. Notice the icon doesn't overlaps the search results / search bar

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [ ] Tier 4

### CODE REVIEW

**Comment by jpmcb** [comment]
Approved workflow runs & requested engineering review: thanks for the contribution!!

**Comment by brandonroberts** [comment]
Thanks @SURAJ-SHARMA27. I don't think use the z-index as a that broadly on the Avatar.  We want to generally avoid using `z-index` as there will always be conflicting settings.

**Comment by SURAJ-SHARMA27** [comment]
> Thanks @SURAJ-SHARMA27. I don't think use the z-index as a that broadly on the Avatar. We want to generally avoid using `z-index` as there will always be conflicting settings.

Okay @brandonroberts, I noticed that backdrop-blur-sm has a z-index of 50, so I thought that on smaller screens, the avatar's z-index might be overridden. Therefore, I explicitly set a low z-index value for the avatar.

**Comment by nickytonline** [comment]
Looking at this closer @SURAJ-SHARMA27, it's a little deeper. The SearchDialog needs to be reimplemented a bit to leverage an actual dialog component.

Thanks for the pull request, but the core team will need to dig into this more.

**Pull request closed without merging**
