### PR TITLE
feat: show OSSF Score in Repo Pages

### LINKED ISSUE #3787: Feature: Add the OSSF Scorecard to repo pages layout
### Suggested solution

Related to: #3767 

Now that we have the UI component ready for the OSSF card, we want to add it to repo pages.

### Proposed layout
Notice that we are breaking the page into different "sections"  (this is a step before actually making them separate tabs).

image

### PR DESCRIPTION
**Pull request by zeucapua**
## Description

Implements `OssfChart` to the repo pages to show the repository's OpenSSF score with a gauge and related documentation. Adding this chart will coincide with the front page layout change, creating two new sections 'Activity' and 'Engagement', moving the `IssueChart` and `PRChart` under 'Activity', with the Stars and Forks under Engagement.

## Related Tickets & Documents

Closes #3787 

## Mobile & Desktop Screenshots/Recordings
image

## Tier (staff will fill in)

- [ ] Tier 1
- [x] Tier 2
- [ ] Tier 3
- [ ] Tier 4

## [optional] What gif best describes this PR or how it makes you feel?

star-wars-vhs-gif

### CODE REVIEW

**Comment by BekahHW** [comment]
Looks good on my end.  Do we need docs to link to in Learn more?

**Comment by zeucapua** [comment]
> Looks good on my end.  Do we need docs to link to in Learn more?

Yes I forgot to ping you about that! Let me know when the docs are ready, thank you! @BekahHW

**Comment by zeucapua** [comment]
Marking as draft since it's blocked:

1. Needs a link to docs for the 'Learn More' button
2. Waiting for OSSF scoring for more repos: https://github.com/open-sauced/app/issues/3787#issuecomment-2256395219

**Comment by BekahHW** [comment]
@zeucapua here's the docs PR: https://github.com/open-sauced/docs/pull/356

**Review by jpmcb — APPROVED** [review]

**Review by brandonroberts — APPROVED** [review]
🍕

**Review by isabensusan — APPROVED** [review]
Ship it 🚀 
pizza-rolls-love-gif

**Pull request merged**
