### PR TITLE
feat: copy `LotteryFactorChart` as image

### LINKED ISSUE #3502: Feature: share `LotteryFactorChart` as image
### Suggested solution

Instead of users having to screenshot each individual card on the site, they can press a "share chart" button to have an image copied to the clipboard. This should be made by an edge function so it is copiable, as well as fetchable via URL.

### PR DESCRIPTION
**Pull request by zeucapua**
## Description

- [x] switch to `html2canvas-pro` fork (maintained over `html2canvas`)
- [x] wrap and copy `LotteryFactorChart` as image via `CopyContainer`
- [x] implement design from issue

## Related Tickets & Documents

Closes #3502 

## Mobile & Desktop Screenshots/Recordings
image
image

## Steps to QA

1. Go to a repo page
2. Hover over the `LotteryFactorChart` and click the copy button on the top right corner
3. On successful toast, paste as an image anywhere (like as a comment on this PR or Twitter)

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [x] Tier 3
- [ ] Tier 4

## [optional] What gif best describes this PR or how it makes you feel?
billie-joe-armstrong-poster-gif-by-green-day

### CODE REVIEW

**Comment by bdougie** [comment]
Looking good. Weird width for the white background. https://dub.sh/kubernetes/kubernetes

image

**Comment by zeucapua** [comment]
> Looking good. Weird width for the white background. https://dub.sh/kubernetes/kubernetes

I can't recreate this, what device did you copy from?

image

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
Works great on mobile on Android

**Comment by bdougie** [comment]
> 
> I can't recreate this, what device did you copy from?
> 
Chrome browser. I did confirm Kubernetes works find on. safari mobile. But seeing it consistent when uploading here and slack.

image

Copied from Safari

image

Slack. Top is mobile, bottom is from chrome. 

Screenshot 2024-08-19 at 4 42 53 PM


If I am the only one, I can try and triage this on my end.

**Review by jpmcb — CHANGES_REQUESTED** [review]
Screenshot 2024-08-20 at 11 06 46 AM

Breaks for me on Firefox: on version 130.0b3

---

Screenshot 2024-08-20 at 11 08 52 AM

And breaks on Chrome: version 127.0.6533.120

Screenshot 2024-08-20 at 11 09 53 AM

Looks to be broken when pasted into twitter as well

---

Both ^ screenshots are from pasting into slack.

**Comment by zeucapua** [comment]
Just tested on Firefox 130.0b7, Chrome 127.0.6533.120; they work fine for me. I don't know how ya'll are getting the errors 😭 I'll keep investigating

**Comment by bdougie** [comment]
> Just tested on Firefox 130.0b7, Chrome 127.0.6533.120; they work fine for me. I don't know how ya'll are getting the errors 😭 I'll keep investigating

I've tried different screen sizes thinking maybe there is a weird background width thing, but it is always showing half the white background.

**Comment by zeucapua** [comment]
Updated to remove the orange background. 
image

**Review by jpmcb — APPROVED** [review]
Lookin good!!! 👏🏼 

Screenshot 2024-08-20 at 3 12 42 PM

**Pull request merged**
