### PR TITLE
fix: unlock Scroll when the Dropdown Menu is opened 

### LINKED ISSUE #1705: Bug: Scrollbar Locks when the Dropdown Menu is Clicked
### Describe the bug

https://github.com/open-sauced/app/assets/106407013/e948141b-8f45-4b9f-8cd9-e0bea77f4335

When a user interacts with the dropdown menu, it results in the scrollbar becoming disabled or locked. This behaviour prevents users from scrolling the page as expected.

Clicking on the dropdown menu should not interfere with the ability to scroll the page. The scrollbar should remain functional.

### Steps to reproduce

1. Go to "https://insights.opensauced.pizza/feed"
2. Click on the (...) dropdown menu after the Twitter icon
3. Observe that the scrollbar becomes locked or disabled.

### Browsers

Chrome

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by RitaDee**
## Description

This PR updates the `ContributorHighlightCard` component. It replaces the `DropdownMenu` component with the `Popover` component for better accessibility and user experience. The dropdown menu options are now displayed in a popover content. The code also includes some minor styling changes and updates to the button elements. These changes improve the overall functionality and visual appeal of the `ContributorHighlightCard` component.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1705

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/app/assets/106407013/0e225e19-83b2-4c37-9a90-db2c7318d2ec

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by brandonroberts — APPROVED** [review]
LGTM

**Comment by ThePiyushAggarwal** [comment]
Hi @RitaDee !

The dropdown doesn't seem to be accessible using keyboard. Please look into this if it is possible.

[dropdown-accessibility.webm](https://github.com/open-sauced/app/assets/27003616/7a00fa8d-c8d9-482d-acd5-fcad8ca0e363)

**Comment by brandonroberts** [comment]
> Hi @RitaDee !
> 
> The dropdown doesn't seem to be accessible using keyboard. Please look into this if it is possible.
> 
>  dropdown-accessibility.webm

Thanks @ThePiyushAggarwal. Unless this broke something that was there, this is out of scope for this PR

**Comment by ThePiyushAggarwal** [comment]
Hey!

So, I tried to find a better solution for this in the radix-ui docs but couldn't. Thanks to @firxworx !. See [this](https://github.com/radix-ui/primitives/discussions/1586#discussioncomment-7049274)

This line of code is what is needed to solve the scrolling issue.
```tsx
<DropdownMenu modal={false}>
```

This locked scrollbar is default behaviour by [Radix UI](https://www.radix-ui.com/primitives/docs/components/dropdown-menu#root). 
image

**Comment by RitaDee** [comment]
> Hey!
> 
> So, I tried to find a better solution for this in the radix-ui docs but couldn't. Thanks to @firxworx !. See [this](https://github.com/radix-ui/primitives/discussions/1586#discussioncomment-7049274)
> 
> This line of code is what is needed to solve the scrolling issue.
> 
> ```tsx
> <DropdownMenu modal={false}>
> ```
> 
> This locked scrollbar is default behaviour by [Radix UI](https://www.radix-ui.com/primitives/docs/components/dropdown-menu#root). image

Thank you @ThePiyushAggarwal, this magically did the fix.

**Comment by RitaDee** [comment]
> Nice research @ThePiyushAggarwal. It was really hard to identify that prop from the Radix docs though😄.
> 
> > So, I tried to find a better solution for this in the radix-ui docs but couldn't. Thanks to @firxworx !. See [radix-ui/primitives#1586 (reply in thread)](https://github.com/radix-ui/primitives/discussions/1586#discussioncomment-7049274)
> 
> `<DropdownMenu modal={false}>` @RitaDee can you take a closer look at this? I understand this might mean undoing what has been done and sincerely apologize 🙏.
> 
> Also applicable to #1704

It’s okay @OgDev-01, I have reverted the changes and added the missing sauce 😄

**Review by OgDev-01 — APPROVED** [review]
LGTM 🍕🍕🍕🍕

**Pull request merged**
