### PR TITLE
refactor: add ESLint deps for code cleanup

### LINKED ISSUE #1768: Feature:
### Type of feature

🧑‍💻 Refactor

### Current behavior

When `next build` runs it currently outputs a lot eslint warning in regards to dependency arrays for `useEffect` calls. It should be fine to literally do what the warnings say to do to fix them.

```
- info Linting and checking validity of types .DeprecationWarning: 'originalKeywordKind' has been deprecated since v5.0.0 and will no longer be usable after v5.2.0. Use 'identifierToKeywordKind(identifier)' instead.

./pages/_app.tsx
80:6  Warning: React Hook useEffect has missing dependencies: 'isMobile' and 'router.asPath'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
106:6  Warning: React Hook useEffect has a missing dependency: 'router.events'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./pages/feed/index.tsx
133:6  Warning: React Hook useEffect has a missing dependency: 'signIn'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
141:6  Warning: React Hook useEffect has a missing dependency: 'followersRepo'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
147:6  Warning: React Hook useEffect has a missing dependency: 'openSingleHighlight'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./pages/hub/index.tsx
9:6  Warning: React Hook useEffect has a missing dependency: 'router'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./pages/start.tsx
60:6  Warning: React Hook useEffect has a missing dependency: 'router'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./pages/user/notifications.tsx
63:6  Warning: React Hook useEffect has missing dependencies: 'fetchNotifications' and 'router'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps

./components/molecules/AuthSection/auth-section.tsx
49:6  Warning: React Hook useEffect has a missing dependency: 'userInfo'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./components/molecules/ContributorHighlight/contributor-highlight-card.tsx
157:6  Warning: React Hook useEffect has a missing dependency: 'taggedRepoList'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
429:6  Warning: React Hook useEffect has a missing dependency: 'updateSuggestionsDebounced'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./components/molecules/HighlightInput/highlight-input-form.tsx
287:6  Warning: React Hook useEffect has a missing dependency: 'fetchAllUserHighlights'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
305:6  Warning: React Hook useEffect has missing dependencies: 'handleGenerateHighlightSummary' and 'taggedRepoList'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
480:6  Warning: React Hook useEffect has a missing dependency: 'updateSuggestionsDebounced'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./components/molecules/TableHeader/table-header.tsx
75:6  Warning: React Hook React.useEffect has a missing dependency: 'updateSuggestionsDebounced'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./components/organisms/ContributorProfileTab/contributor-profile-tab.tsx
101:6  Warning: React Hook useEffect has missing dependencies: 'login', 'receive_collaboration', and 'user_name'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps

./components/organisms/InsightPage/InsightPage.tsx
150:6  Warning: React Hook useEffect has a missing dependency: 'insight'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
431:6  Warning: React Hook useEffect has a missing dependency: 'updateSuggestionsDebounced'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./components/organisms/SearchDialog/search-dialog.tsx
36:6  Warning: React Hook useEffect has a missing dependency: 'setOpenSearch'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
68:6  Warning: React Hook useEffect has missing dependencies: 'cursor' and 'searchTerm.length'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
128:6  Warning: React Hook useEffect has a missing dependency: 'setOpenSearch'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./components/organisms/UserRepositoryRecommendations/user-repository-recommendations.tsx
74:6  Warning: React Hook useEffect has a missing dependency: 'getRepoFullNameByInterests'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
78:6  Warning: React Hook useEffect has a missing dependency: 'refreshUserRecommendedRepos'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./components/organisms/UserSettingsPage/user-settings-page.tsx
80:6  Warning: React Hook useEffect has a missing dependency: 'userInfo'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

./lib/hooks/useFilterPrefetch.ts
43:6  Warning: React Hook useEffect has missing dependencies: 'filterOptions' and 'mutate'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps

./lib/hooks/useSession.ts
53:6  Warning: React Hook useEffect has missing dependencies: 'getSession', 'loadSession', and 'setStoreData'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps

./lib/hooks/useSupabaseAuth.ts
39:6  Warning: React Hook useEffect has missing dependencies: 'loadSession' and 'store'. Either include them or remove the dependency array.  react-hooks/exhaustive-deps
```

It'd be good to clean these up at some point.

### Suggested solution

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by RitaDee**
## Description
Add ESLint dependencies for code cleanup

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1768
## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by nickytonline** [comment]
We'll need to test all the places these fixes were made. I know @babblebey had mentioned potential issues with debouncing for search I think?

**Comment by OgDev-01** [comment]
Hey @RitaDee, I am checking in to see if you are blocked on this. feel free to mention @open-sauced/engineering if help is needed anytime 👍

**Comment by RitaDee** [comment]
> Hey @RitaDee, I am checking in to see if you are blocked on this. feel free to mention @open-sauced/engineering if help is needed anytime 👍

Yes, I am blocked. Thanks

**Comment by OgDev-01** [comment]
> Yes, I am blocked. Thanks

Do you want to share what the blocker is? 

Also, to prevent PRs from going stale, we can always mention when we are blocked so other folks can provide help to get unblocked 👍 .

**Comment by RitaDee** [comment]
> > Yes, I am blocked. Thanks
> 
> Do you want to share what the blocker is?
> 
> Also, to prevent PRs from going stale, we can always mention when we are blocked so other folks can provide help to get unblocked 👍 .

I will give this a try again (maybe it is not a blocker, I will try to utilize the useCallback() hook). Thank you.

**Comment by RitaDee** [comment]
> > Hey @RitaDee, I am checking in to see if you are blocked on this. feel free to mention @open-sauced/engineering if help is needed anytime 👍
> 
> Yes, I am blocked. Thanks

Hey @OgDev-01 and @nickytonline , please is it okay I do this fix in bits?

**Comment by brandonroberts** [comment]
Hey @RitaDee, I think it would be good to fix this is smaller bits as you suggested. Going to close this one for now. Feel free to reopen or open a new one when you're ready

**Pull request closed without merging**
