### PR TITLE
fix: add Posthog events for user profile share and update

### PR DESCRIPTION
**Pull request by brandonroberts**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Closes https://github.com/open-sauced/engineering/issues/231

## Steps to QA

User profile share
1. Open up browser console
2. Navigate to a user profile whether logged in or logged out
3. Click the `Share` button
4. Note the posthog event with `clicked: profile copied` in the console log

User profile update
1. Open up browser console
2. Navigate to your profile settings `/user/settings`
3. Update your profile and save
4. Note the posthog event with `Updated user profile` in the console log

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by nickytonline — COMMENTED** [review]
I followed the steps for the share, but I didn't see anything get logged. I know that my browser blocks some stuff, so maybe it's blocking the Posthog action?

CleanShot 2024-01-30 at 13 57 24

**Review by jpmcb — COMMENTED** [review]
Also not seeing the logging happening on Firefox with the deploy preview, just alot of CORS errors:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://app.posthog.com/e/?compression=gzip-js&ip=1&_=1706642349989&ver=1.83.0. (Reason: CORS request did not succeed). Status code: (null).
```

maybe it won't work in a deploy preview ... ?

**Comment by brandonroberts** [comment]
@nickytonline @jpmcb ahh good call. It only logs when run on localhost

**Comment by jpmcb** [comment]
Hmmm I'm still not seeing it running this PR locally. I get a posthog json parse error:

```
PostHog error: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
```

**Comment by brandonroberts** [comment]
@jpmcb are you getting any events logged when running locally?

**Comment by jpmcb** [comment]
I do see it locally in Chrome:

```
{
    "uuid": "018d5be7-bc80-7b6a-ba39-2016c9c11a13",
    "event": "clicked: profile copied",
    "properties": {
        "$os": "Mac OS X",
        "$os_version": "10.15.7",
        "$browser": "Chrome",
        "$device_type": "Desktop",
        "$current_url": "http://localhost:3000/user/OgDev-01",
        "$host": "localhost:3000",
        "$pathname": "/user/OgDev-01",
        "$browser_version": 121,
        "$browser_language": "en-US",
        "$screen_height": 1440,
        "$screen_width": 3440,
        "$viewport_height": 547,
        "$viewport_width": 2392,
        "$lib": "web",
        "$lib_version": "1.83.0",
        "$insert_id": "e8ribrbaglhhpf09",
        "$time": 1706643930.24,
        "distinct_id": "23109390",
        "$device_id": "018c4abf-862e-74b3-9622-44327f62527b",
        "$autocapture_disabled_server_side": false,
        "$active_feature_flags": [
            "workspaces",
            "most_used_languages_graph",
            "contributions_evolution_by_type"
        ],
        "$feature/workspaces": true,
        "$feature/most_used_languages_graph": true,
        "$feature/contributions_evolution_by_type": true,
        "$feature_flag_payloads": {},
        "$user_id": "23109390",
        "$referrer": "$direct",
        "$referring_domain": "$direct",
        "profile": "OgDev-01",
        "token": "phc_Y0xz6nK55MEwWjobJsI2P8rsiomZJ6eZLoXehmMy9tt",
        "$session_id": "018d5be6-954d-7025-84a3-1931d177680f",
        "$window_id": "018d5be6-954d-7025-84a3-1932a7d0a60c"
    },
    "offset": 1590
}
```

with no errors. But in Firefox, I see some pretty gnarly looking errors that were burrying the `clicked: profile copied` event:

Screenshot 2024-01-30 at 12 47 26 PM

Maybe those errors are unrelated? Or bubbling up from the posthog library? I'm ok sending this since I do see the event logged, it was just getting burried

**Comment by brandonroberts** [comment]
Yea, those are unrelated to these changes

**Review by jpmcb — APPROVED** [review]

**Review by nickytonline — APPROVED** [review]
:shipit:

**Pull request merged**
