### PR TITLE
fix: added missing key prop to skeleton component

### LINKED ISSUE #2442: Bug:  Each child in a list should have a unique "key" prop
### Describe the bug

After running the app locally, if you open the console, you will notice an issue related to the missing 'key' prop.

we have to fix the issue 

image

### Steps to reproduce

- run the app locally 
- open the console 
- you will see the issue

### Browsers

Other (add additional context)

### Additional context (Is this in dev or production?)

dev

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by Nikhilh26**
Removed warnings which were logged on console due to missing key in skeleton-wrapper.tsx

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2442

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by BekahHW** [comment]
Hey @Nikhilh26 Can you please fill out all the fields in the PR template and follow the instructions that we've included [here](https://github.com/open-sauced/app/pull/2504#pullrequestreview-1834676145)? Also, I notice the build is failing. I'm going to put this in draft mode for now. Once you've updated the PR template and title and addressed the build issues, feel free to take it out of draft mode.

**Comment by Nikhilh26** [comment]
can you explain the issue? why is it failing

**Comment by BekahHW** [comment]
> * fix: correct remove button behavior

Hey @Nikhilh26, it's linked in the message I sent. But you have to follow Conventional Commit Title format for the PR.

For example, you have:

`Fixing issue 2442`, but to follow the directions, it needs to be something like 

`fix: correct remove button behavior`, the "fix:" is required for the format.

You also need to fill out the PR Template. You skipped these sections:

Related Tickets & Documents
Mobile & Desktop Screenshots/Recordings
Steps to QA
Added to documentation?

And also did not utilize conventional commits for the description section--refer to the previously mentioned Issue Reference section.

We ask that you read the contributing section of our section of the docs before submitting a PR. If you need more information, you can read it [here](https://docs.opensauced.pizza/contributing/introduction-to-contributing/).

**Comment by Nikhilh26** [comment]
why are rest of the checks are failing?

**Comment by Nikhilh26** [comment]
1:01:54 AM: 29:32  Error: Insert `⏎`  prettier/prettier
1:01:54 AM: ./components/molecules/AuthSection/auth-section.tsx
i have not changed anything in auth.js

**Comment by jpmcb** [comment]
@Nikhilh26 - we just did a big merge from our `alpha` branch into `beta`: there were probably some conflicts along the way but looks like Brandon updated this PR for you!

Now there's just this linting error you'll need fixing up:
```
./components/atoms/SkeletonLoader/skeleton-wrapper.tsx
29:32  Error: Insert `⏎`  prettier/prettier
```

**Comment by Nikhilh26** [comment]
@jpmcb Is it possible to make change here directly or do i need to make a new PR?

**Comment by nickytonline** [comment]
> @jpmcb Is it possible to make change here directly or do i need to make a new PR?And how to remove Lint Error

No need to make a new PR @Nikhilh26.

**Comment by Nikhilh26** [comment]
How do I resolve the linting error?

**Comment by nickytonline** [comment]
> How do I resolve the linting error?

You can run from the root of the project.

```bash
npm run lint -- --fix
```

**Comment by Nikhilh26** [comment]
I hope its correct now 😅

**Review by nickytonline — APPROVED** [review]
Thanks for the fix @Nikhilh26!

:shipit:

**Comment by Nikhilh26** [comment]
Are there any other issues open that you have in mind . I went through a lot of issues most of them were assigned or Not assignable

**Comment by nickytonline** [comment]
> Are there any other issues open that you have in mind . I went through a lot of issues most of them were assigned or Not assignable

This will show you issues that are no longer being triage or are not core team work, https://github.com/open-sauced/app/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+no%3Aassignee+-label%3A%22core+team+work%22+-label%3A%22%F0%9F%91%80+needs+triage%22+

**Review by jpmcb — APPROVED** [review]

**Pull request merged**
