### PR TITLE
feat: Use insight repos already on insights

### PR DESCRIPTION
**Pull request by jpmcb**
## Description

Allows for public workspaces with repo insight pages to be public and prevents an additional call to "v2/insights/{id}/repos" (since repos are returned on the insight within the server side props - I don't anticipate this being an issues on the server side since repos are returned really quickly in a left join from the `repos` table. But maybe someone will have an astronomical number of repos in an insight page at some point, then we may reconsider).

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Related to and followup for: https://github.com/open-sauced/api/pull/602

## Steps to QA

Run through the following in 3 scenerios:

1. Run locally
2. Go to a public workspace
3. Go to a insight page in that workspace

Logged in, not logged in, and private workspace

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by jpmcb** [comment]
Hmmm this was working locally, but the deploy preview doesn't want to send me to . I'll pull the latest on beta and make sure things are 👍🏼

**Comment by jpmcb** [comment]
Ah duh, this needs https://github.com/open-sauced/api/pull/602 to land in beta before this will work 👀

**Comment by jpmcb** [comment]
This is working: but there's some rough edges, like this "private" card that i'm assuming is denoted by the `is_public` field on the insight

Screenshot 2024-02-26 at 7 01 15 PM

**Review by brandonroberts — APPROVED** [review]

**Review by nickytonline — APPROVED** [review]
🚢

**Comment by brandonroberts** [comment]
Removing the pills in https://github.com/open-sauced/app/pull/2779

**Pull request merged**
