### PR TITLE
feat: add contributions filter to contributor profile

### LINKED ISSUE #3549: Feature: Add issue comments to contributor profile
### Suggested solution

On the contributor profile, we display the most recent pull requests. We want to add issues to be displayed here also and toggle which ones are included in the total list.

### PR DESCRIPTION
**Pull request by brandonroberts**
## Description

- Adds issue comments to the contributor profile, and a multi-select to toggle PRs and Issue Comments
- Came out of a request to see the issue comments from `JiaT75` in the recent xz vulnerability research

## Related Tickets & Documents

Closes #3549 

## Mobile & Desktop Screenshots/Recordings

image

https://opensauced.rewatch.com/video/v1iko1l6kyco79o0-demo-contributor-profile-issue-comments

## Steps to QA

1. Go to deploy preview
2. Go to a contributor profile
3. Click on Contributions and select Issue Comments
4. See the issue comments table below
5. Change the range of days to see more if less than 15 are shown

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

**Review by nickytonline — DISMISSED** [review]
There's some page shifting happening when you change the contribution filter.

I can take a look at this @brandonroberts.

CleanShot 2024-06-12 at 17 37 30

**Comment by brandonroberts** [comment]
@nickytonline 🤝

**Comment by isabensusan** [comment]
Thank you for this!! Some UI comments:
1. Instead of using the multiselect toggle (it hides other contribution options behind the dropdown), can we use [this tab component](https://design-insights.netlify.app/?path=/docs/components-shared-subtabslist--docs)? 
image

Like so:
image


2. Can we replace the "Loading" text with the skeleton animation?
image

Kind of like this -- give it a min height of aprox 400px as well so that when it populates, the layout shift isn't as harrowing
image

3. Give it an empty state:
image

image

Empty state image:
image

**Review by bdougie — APPROVED** [review]

**Review by bdougie — COMMENTED** [review]
Clicked the wrong button on mobile. Features looks great and will be even better with Isa's feedback.

**Comment by bdougie** [comment]
I now see no comments for JiaT75 

Screenshot 2024-06-14 at 7 25 35 PM

**Comment by brandonroberts** [comment]
The data is still in the API. Could be a caching issue

https://beta.api.opensauced.pizza/v2/users/jiat75/issue-comments?limit=15&range=360

**Comment by jpmcb** [comment]
> I now see no comments for JiaT75. I previously saw some.

@bdougie / @brandonroberts - here's a fix for the case-insensitivity for usernames like `JiaT75` (which should get lowercased down to `jiat75`)

https://github.com/open-sauced/api/pull/882

**Review by jpmcb — CHANGES_REQUESTED** [review]
Seems the whole table breaks out of the div to the right and words get cut off:

Screenshot 2024-06-17 at 4 15 34 PM

**Comment by nickytonline** [comment]
> Seems the whole table breaks out of the div to the right and words get cut off:
> 
> 
> 
> Screenshot 2024-06-17 at 4 15 34 PM

I can take a peek at this in the AM if you want @brandonroberts

**Comment by brandonroberts** [comment]
@nickytonline @jpmcb the issue comments table is responsive now


https://github.com/open-sauced/app/assets/42211/53bf5363-e266-4625-a44b-b4b33c737566

**Review by jpmcb — APPROVED** [review]
🚀 🚀

**Pull request merged**
