### PR TITLE
fix: Updated Twitter Icon To X

### LINKED ISSUE #1681: Bug: Request to Update Twitter Icon to X
### Describe the bug

The Twitter logo has been updated recently and hasn't been updated on the site. I didn't find any issue related to this.

Screenshot
Screenshot 2023-09-07 192207

Additional Context
Won't change anything in the code as such would replace the twitter-logo with a new file. No code will be touched.

@bdougie , @isabensusan 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

### Steps to reproduce

Scroll to footer section and see twitter old logo

### Browsers

Chrome

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by lalitkumawat1m**
## Description

Removed Twitter's old bird Icon and added a New X icon In the Footer, Contributor Highlight card, and Contributor Profile info.

This PR fixes the bug #1681. 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

 Fixes #1681

## Mobile & Desktop Screenshots/Recordings
Screenshot 2023-09-08 084313

Screenshot 2023-09-08 084242

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by CBID2 — APPROVED** [review]
Looks great! 😊

**Comment by OgDev-01** [comment]
Nice job @lalitkumawat1m 👏 . 

The size looks a bit big to me, but l'll leave this to @isabensusan and the @open-sauced/engineering to decide 😁

**Review by bdougie — APPROVED** [review]
Thanks for jumping on this @lalitkumawat1m 

@OgDev-01 I didn't find the X to big and it complements the DEV logo. Since this is a drop in 1 to 1 replacements let's leave it as is.

**Comment by bdougie** [comment]
@lalitkumawat1m are you able to look into the failing test? Looks related to the change but needs some triaging. 

run this and report back on thoughts
```
npm test
```

**Review by jpmcb — CHANGES_REQUESTED** [review]
```
- info Loaded env from /Users/jpmcb/workspace/opensauced/insights/.env
 FAIL  components/organisms/DevCardCarousel/dev-card-carousel.test.tsx
  ● Test suite failed to run

    Cannot find module '@heroicons/react/24/solid/esm/ArrowTrendingUpIcon' from 'components/molecules/DevCard/dev-card.tsx'

    Require stack:
      components/molecules/DevCard/dev-card.tsx
      components/organisms/DevCardCarousel/dev-card-carousel.tsx
      components/organisms/DevCardCarousel/dev-card-carousel.test.tsx

      13 | import CardSauceBGSVG from "img/card-sauce-bg.svg";
      14 | import openSaucedImg from "img/openSauced-icon.png";
    > 15 | import PRIcon from "img/icons/pr-icon.svg";
         |                                                                     ^
      16 | import { getRelativeDays } from "lib/utils/date-utils";
      17 |
      18 | export interface DevCardProps {

      at Resolver._throwModNotFoundError (node_modules/jest-resolve/build/resolver.js:491:11)
      at Object.<anonymous> (components/molecules/DevCard/dev-card.tsx:15:69)
```

I'm not sure why this change would affect heroicons but ideally this wouldn't bork out the test

---

Screenshot 2023-09-08 at 3 06 08 PM

This looks like a huge change to the shrinkwrap. Maybe it has to do with this? I believe only the `react-icons` should be changed in the shrinkwrap

**Review by OgDev-01 — APPROVED** [review]

**Comment by brandonroberts** [comment]
The changes look good but the CI checks need to be resolved.

**Comment by nickytonline** [comment]
Looks like some stuff is out of sync which is why some of the CI checks are failing.

```
npm ci can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with npm install before continuing.
```

**Comment by takanome-dev** [comment]
>  Invalid: lock file's react-icons@4.7.1 does not satisfy react-icons@4.11.0

@lalitkumawat1m you need to `npm i` because the lock file does not contain v4.11.0 but rather v4.7.1 of react icons

**Comment by bdougie** [comment]
Perhaps we can cherry this pr on a new one. This is a nice to have, but perhaps the author got busy.

cc @open-sauced/engineering

**Pull request closed without merging**
