### PR TITLE
feat: contributions treemap filtered by owners now

### LINKED ISSUE #2175: Feature: group lists tree map by organization
### Type of feature

🍕 Feature

- [x] #2402

### Current behavior

Current hierarchy for the tree map drill downs is Repos > Contributors
image

### Suggested solution

Can we add a higher dimension for organizations? Something like this where we have organizations on the top-level, and the user can drill down to get to repositories -> then contributors.
image

We would also want repositories belonging to the same organization to have the same color.

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Now the contributions treemap has three levels: owners (orgs and users), repositories, and contributors.

@open-sauced/design, feel free to slice and dice on the design and UX.

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Closed #2175

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/app/assets/833231/2b820829-68d9-4135-85ad-526a44b5f4c4

CleanShot 2023-12-21 at 14 28 40

CleanShot 2023-12-21 at 14 29 26

CleanShot 2023-12-21 at 14 29 44

## Steps to QA

1. Visit a list activity page
2. Drill down or up in the All Contributions treemap

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [x] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by nickytonline** [comment]
@open-sauced/design, feel free to slice and dice on the design and UX.

**Comment by nickytonline** [comment]
I can add a context menu which could make it easier to go back as @BekahHW mentioned in Slack. Radix has one, so it shouldn't be too difficult to implement. This could also be a small follow up PR. And since it's Radix, it's supports keyboard navigation.

https://www.radix-ui.com/primitives/docs/components/context-menu

**Comment by nickytonline** [comment]
I know we have an issue for expanding graphs to full screen, but I think for this graph it makes sense to be all alone in a grid row taking up the space of two graphs as it will definitely need a lot of real estate in general. Let me know if you're cool with that @isabensusan.

**Comment by nickytonline** [comment]
Please don't hesitate to tweak this while I'm off and merge it if you think it's in a good state. If not, I'll get to it in the new year.

**Review by brandonroberts — APPROVED** [review]

**Review by jpmcb — APPROVED** [review]

**Pull request merged**
