### PR TITLE
feat: Issues and PR charts for Repo pages

### LINKED ISSUE #3294: Feature: Pull Requests / Issues chart component for repo pages
### Current behavior

N/A

### Suggested solution

⚠️  This issue is ONLY FOR THE UI COMPONENT ⚠️ 

We want to build the following charts for repo pages:

image

image

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by zeucapua**
## Description

Adds `IssuesChart` and `PRChart` for repo pages, line charts that have two lines showing opened and merged/closed. `RepositoryStatCards` for both have been removed and stats are in the chart cards now.

## Related Tickets & Documents

Closes #3294 

## Mobile & Desktop Screenshots/Recordings
image

## Tier (staff will fill in)

- [ ] Tier 1
- [x] Tier 2
- [ ] Tier 3
- [ ] Tier 4

### CODE REVIEW

**Comment by bdougie** [comment]
Curious how issue velocity is calculated. react-router is 2 days velocity which seems low. 

Screenshot 2024-05-07 at 10 17 16 AM

**Review by isabensusan — APPROVED** [review]
LGTM!!

**Review by nickytonline — CHANGES_REQUESTED** [review]
Looking at all the screen sizes and everything looks good except for the large breakpoint for the forks graph, the bottom doesn't line up with the other graph.

CleanShot 2024-05-07 at 14 14 59

**Comment by nickytonline** [comment]
It also looks like for the Storybook stories for forks and stars, the 7 and 30 day day ranges have no data. Not critical per se, but it'd be nice to show some data there.

https://github.com/open-sauced/app/assets/833231/ec67e2e1-af3f-4fbd-b18d-f0ffa153cd28

**Review by nickytonline — APPROVED** [review]
@zeucapua  will do a follow up PR for what I mentioned as it’s actually not part of the changes in this PR.

:shipit:

**Pull request merged**
