### PR TITLE
fix: quick fix StarSearch response

### PR DESCRIPTION
**Pull request by zeucapua**
## Description

Better parsing for StarSearch response.

## Mobile & Desktop Screenshots/Recordings

BEFORE
image

AFTER
image

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

**Review by nickytonline — APPROVED** [review]
Giving the LGTM because we just paired on this.

🚢

**Comment by bdougie** [comment]
We talked about this but it would be ideal to format order lists and add hyperlinks in a follow up or tomorrow

**Comment by isabensusan** [comment]
This is definitely closer to what we want to achieve, no more white spaces!

On a follow up PR, it'd be great to add even more formatting so that bolded words actually render as bold, and we add some line breaks and lists format. The prompt reply seems to be coming in in markdown format (see screenshot), so rendering that would be great.

image

**Review by jpmcb — APPROVED** [review]
👍🏼

**Review by bdougie — APPROVED** [review]
🚀🚀🚀

**Pull request merged**
