### PR TITLE
fix: highlights page endless flicker on tab change (1576)

### LINKED ISSUE #1576: Bug: Non stop flickering on Highlights page after using filters
### Describe the bug

Endless flickering issue on highlights page

[highlights-issue.webm](https://github.com/open-sauced/insights/assets/27003616/aea650fc-0de3-4723-a012-dabb8732ab99)

### Steps to reproduce

1. This happens only when you are following zero people.
1. Go to Highlights/Feed page.
1. Click on a Repository filter on the right hand side.
1. Click on Following tab.
1. Go back to the Home tab.
1. Now you should be able to see endless flickering screen.

### Browsers

Chrome

### Additional context (Is this in dev or production?)

dev and production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by ThePiyushAggarwal**
## Description

- There was unnecessary use of `useEffect` in `components\molecules\HighlightsFeedCard\highlights-filter-card.tsx` file. The variable was being set with its own value. It was actually doing nothing so I removed it (0fc3156).
- There was a comment on it which was to reset the `selectedRepo` state variable. I made sure it was done. I shifted it to a `onTabChange` function which is also given the functionality of clearing the filter from URL as well (0e93f69).

fixes #1576 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

fixes #1576 
## Mobile & Desktop Screenshots/Recordings

| Before | After |
| ------ | ------ |
| [highlights-issue.webm](https://github.com/open-sauced/insights/assets/27003616/aea650fc-0de3-4723-a012-dabb8732ab99) | [highlights-flicker-fix.webm](https://github.com/open-sauced/insights/assets/27003616/649eada3-c4ca-4b42-ba58-de5c26009d2a) |
| And | And |
| image | image |

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [x] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by brandonroberts** [comment]
@ThePiyushAggarwal the deploy preview failed. Looks like the storybook stories need to be updated. You can run `npm run build` to see the error. Will you take a look?

**Comment by ThePiyushAggarwal** [comment]
> 

Yeah! Let me check

**Comment by ThePiyushAggarwal** [comment]
@brandonroberts I have fixed the issue happening with storybook tests. 

I have remove the unnecessary prop and added some sample data so that the story looks good.

Updated PR Description as well

image

**Comment by ThePiyushAggarwal** [comment]
I see the E2E tests are failing. Checking those now.

**Comment by ThePiyushAggarwal** [comment]
😀 All tests pass

**Review by brandonroberts — APPROVED** [review]
🍕

**Pull request merged**
