### PR TITLE
fix: changed delete button color to match the ui

### LINKED ISSUE #2134: feature: Delete account should be danger zone button color
## Currently 
In the user settings we have a "Delete Account" button that does not follow existing UI and design patterns. 

Screen Shot 2023-11-14 at 8 48 34 AM

## Request 

Match the UI to the danger zone found on the insight edit page

- [ ] Button color should be lighter red option

Screen Shot 2023-11-14 at 8 48 50 AM

### PR DESCRIPTION
**Pull request by sital002**
## Description
changed the delete button color to match the UI 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

fixes #2134 

## Mobile & Desktop Screenshots/Recordings
Edit:
Before changes:
image
image

After changes:
image
image
image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by OgDev-01** [comment]
Thanks for taking this on @sital002, can you add a before/after screenshot to your PR description for a quicker review?

**Comment by sital002** [comment]
> Thanks for taking this on @sital002, can you add a before/after screenshot to your PR description for a quicker review?

I have updated the PR description.

**Review by OgDev-01 — APPROVED** [review]
🍕

**Comment by nickytonline** [comment]
The other button styling was used as it has better colour contrast. I'm going to go ahead and merge this for now to keep things uniform, but @isabensusan, I'd love to have a more accessible danger button in terms of colour contrast. We can chat about it on Monday.

**Review by nickytonline — APPROVED** [review]
Thanks for the update @sital002!

**Review by bdougie — APPROVED** [review]

**Pull request merged**
