### PR TITLE
fix: make list overview stats accurate

### LINKED ISSUE #2216: Bug: Active, new and alumni contributors add up incorrectlu on list overview page
### Describe the bug

Active, new and alumni contributors add up incorrectlu on list overview page

### Steps to reproduce

1. Navigate to http://localhost:3000/lists/8b371419-6219-4448-9de1-f6293a25f98e/overview

Notice the cards don't add up to 18.

CleanShot 2023-11-27 at 19 49 06

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by OgDev-01**
## Description
This PR corrects the stats display data in list overview dashboard cards

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
fixes #2216 

### Before
image

### After
image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by nickytonline** [comment]
Hmmm, not sure what's up, but the numbers for my list don't add up for https://deploy-preview-2218--oss-insights.netlify.app/lists/8b371419-6219-4448-9de1-f6293a25f98e/overview

CleanShot 2023-11-28 at 07 50 40

**Comment by OgDev-01** [comment]
Re-testing this today and it looks weird what the results are
image

From what i understand, alumni and new contributors should total to the number in active. is this currect? cc: @nickytonline 

if that is the case, then somehow i think the api data is not fully accurate and might need revisiting

**Comment by nickytonline** [comment]
> Re-testing this today and it looks weird what the results are
> 
> image
> 
> 
> 
> From what i understand, alumni and new contributors should total to the number in active. is this currect? cc: @nickytonline 
> 
> 
> 
> if that is the case, then somehow i think the api data is not fully accurate and might need revisiting

active, alumni, and new contributors should add up to the total number of contributors in the list.

**Review by jpmcb — APPROVED** [review]
This looks right to me: the API returns the `itemCount` which is the total number of contributors in that certain list. So this seems to be doing the right think 👍🏼

**Comment by nickytonline** [comment]
@jpmcb @OgDev-01, I'm still confused, because here's a brand new list I created and the numbers don't add up to 10. https://deploy-preview-2218--oss-insights.netlify.app/lists/5b3b9388-a1bd-4f3a-a66c-c962d18fd549/overview. Are there two other people in the list categorized as something else?

CleanShot 2023-12-04 at 19 24 44

**Comment by jpmcb** [comment]
@nickytonline - hmmmm good question: I'm not sure what's going on with these numbers in the API. I honestly want to refactor these endpoints to use Timescale after getting our initial integration in for PRs since I had to write some custom software to generate the "time buckets" stuff we get for free with Timescale.

From the frontend perspective, this seems to be ok since it's just pulling the `itemCount` off the page. We could put a hold on this until we have better data or move this through and integrate latter?

**Comment by isabensusan** [comment]
@jpmcb now that we have the new Timescale data and the V2 endpoints, could we look into updating these endpoints as well?

**Comment by jpmcb** [comment]
@isabensusan - yes, next up for me after tackling the workspaces API endpoints is to refocus on getting these in!

**Comment by brandonroberts** [comment]
Closing as we'll update these with the V2 API changes

**Pull request closed without merging**
