### PR TITLE
fix(create-insight): highlight added repos

### LINKED ISSUE #2247: Bug: After adding the repository, the "Add to page" button remains visible in the suggested bar.
### Describe the bug

When a user creates a new Insight on the Insight page, a suggested repo bar is displayed. When the user adds the repo to their page using the "add to page" button, the repo is properly added to their page. However, the problem arises when the repo is added to the page, as the "add to page" button still remains visible. It should either be removed or replaced with a check mark or some other indication to help the user understand that the repo has already been added to their page.

https://github.com/open-sauced/app/assets/94627200/00acd812-4351-483b-b298-a2029f43c7ef

### Steps to reproduce

1. Goto to the "Insights page"
2. Click on "New Insight"
3. Scroll down.......
4. Click on the "Add to page" button.

### Browsers

Edge

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by sourabpramanik**
## Description

In create insight page the suggested repositories now can be removed from the page/cart and the button label changes from "Add to page" to "Remove" which highlights that particular repository is already added to the page/cart

## What type of PR is this? (check all applicable)

- [X] 🍕 Feature
- [X] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

fixes #2247 
## Mobile & Desktop Screenshots/Recordings
298115773-54e19231-df86-4cd9-9899-8a03763f8b3d

## Steps to QA
1. Go to Create Insight page
2. Scroll down to the suggested repositories
3. Add any repo

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [X] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

NO

### CODE REVIEW

**Comment by BekahHW** [comment]
@sourabpramanik would you please add a recording to the PR template?

**Comment by sourabpramanik** [comment]
@BekahHW done!

**Comment by BekahHW** [comment]
@isabensusan is this what you think should happen when one of the suggested repos is selected? Or should it suggest a different repo?

**Comment by sourabpramanik** [comment]
Do you mean to update the suggested repo list by removing the added one from the list and adding a new suggested repo to the list?

**Comment by brandonroberts** [comment]
@sourabpramanik will you fix the failed build for the PR preview?

**Comment by BekahHW** [comment]
@sourabpramanik I'm no longer able to reproduce the bug in production. I think it may be resolved already.

**Comment by sourabpramanik** [comment]
@BekahHW I checked production, alpha, and beta and I can reproduce this issue. When you add the repo to your page the button still says "Add to page".

**Comment by takanome-dev** [comment]
@sourabpramanik can you please try checking again?

Looks like this is solved as right now  when you add a repo, it disappears and you get new suggestions

**Comment by sourabpramanik** [comment]
@takanome-dev I have tested on all three environments

Production
test-prod

Alpha
test-alpha

Beta
test-beta

**Comment by takanome-dev** [comment]
> I can still reproduce that issue @takanome-dev

that's weird 😅 @open-sauced/triage can you please try to reproduce this issue? Would really appreciate it 😊

**Comment by BekahHW** [comment]
@sourabpramanik It looks like the repos are totally removed once you've added them now, so I'm going to close this. But if you find that you're still having issue, feel free to reopen this PR.

**Pull request closed without merging**
