### PR TITLE
fix(search): pressing enter when focused on search input routes the page

### LINKED ISSUE #988: Bug: Pressing enter in Search bar of repo tab scrolls to top and may refresh repos without doing any functionality
### Describe the bug

image
Clicking enter isn't supposed to work, yet it scrolls the page to top and may occasionally reload the repos.

This behavior should be removed.

### Steps to reproduce

Open Search bar in Explore's Repository Tab, write anything and click enter.

### Affected services

insights.opensauced.pizza

### Platforms

_No response_

### Browsers

_No response_

### Environment

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by sourabpramanik**
## Description

In repositories table when searching for a repo, without selecting any repo from the search results and pressing enter while focused on the search input will route to current page without any change

This PR fixes  #988

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [X] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Mobile & Desktop Screenshots/Recordings

fix

## Steps to QA
1. Search any repo name
2. Hit enter, nothing should happen because no repo selected from the results below
3. Now select any result
4. Hit enter and it will route to the repo page

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [X] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

NO

### CODE REVIEW

**Comment by brandonroberts** [comment]
@sourabpramanik what's the status of this PR?

**Comment by sourabpramanik** [comment]
@brandonroberts moving for review now!

**Comment by brandonroberts** [comment]
@sourabpramanik Thanks! Does this handle the case where they enter a search, select a result, and then clear out the search? Logic issue aside, I believe that's why it worked that way previously

**Comment by sourabpramanik** [comment]
@brandonroberts  It will go back to previous state in that case. This is what expected right?

**Comment by brandonroberts** [comment]
Yes, if you clear the repository in the search and press enter, it should go back to the unfiltered list of repositories.

**Comment by sourabpramanik** [comment]
> Yes, if you clear the repository in the search and press enter, it should go back to the unfiltered list of repositories.

@brandonroberts  Yes it works as expected 
fix

**Review by brandonroberts — APPROVED** [review]

**Pull request merged**
