### PR TITLE
feat: updated `/explore` page

### LINKED ISSUE #4045: Feature: Explore Page
### Suggested solution

image

## Update
We have a cleaner design @zeucapua !

[Link to header image (slightly different from mock but that's ok!)](https://drive.google.com/drive/folders/1ZjP7E9a3Ms7GENvLZHBnJtDXLxXwlkB5?usp=sharing)

image

A new Workspace tile component needs to be created as well

image

### PR DESCRIPTION
**Pull request by zeucapua**
## Description

Implements a new design for the Explore page. Also changes redirects from `/` and the nav bar URL to `/explore` instead of adding a topic and tool afterwards.

Includes the following sections:
- **Trending Repositories**: uses the `/histogram/top/stars` endpoint 
- **Recommended For You**: uses the `/user/recommendations/repos` endpoint, will show a login CTA if there's no logged in user
- **Discover Workspaces**: hardcoded production workspaces _(will error on beta)_ from the OpenSauced staff for showcases

## Related Tickets & Documents

Closes #4045

## Mobile & Desktop Screenshots/Recordings

https://github.com/user-attachments/assets/5022489c-b93d-4428-83d1-f286db4f0a3a

## Steps to QA
1. Go to the deploy preview and ensure that it redirects to the `/explore` page
2. If not logged in, check that the Recommended section includes a login CTA
3. If logged in, see that there are repos under the Recommended section
4. Scroll through to make sure the carousels works per section
5. Do `Ctrl+K` or `Cmd+K` OR click on the big search bar at the top of the page and make sure the search dialog pops up
6. Check mobile view for any UX issues

## Tier (staff will fill in)

- [ ] Tier 1
- [x] Tier 2
- [ ] Tier 3
- [ ] Tier 4

## [optional] What gif best describes this PR or how it makes you feel?
abc-yes-gif-by-the-bachelorette

### CODE REVIEW

**Review by jpmcb — APPROVED** [review]
Played around on the deploy preview with mobile view and desktop view: looks really great! Nice work!

**Review by bdougie — COMMENTED** [review]
Looking good 🚀

**Review by bdougie — APPROVED** [review]

**Review by nickytonline — APPROVED** [review]
Great stuff @zeucapua!

**Review by brandonroberts — APPROVED** [review]
🫡

**Pull request merged**
