### PR TITLE
fix: now interests are not fallbacks for most used languages

### LINKED ISSUE #2281: Bug: contributor list "Most used languages" is innacurate
### Describe the bug

I've seen a few instances where "Most used langauages" in the contributor lists is inaccurate.

This screenshot is off of beta:

Screenshot 2023-12-07 at 10 07 09 AM

For example, I haven't written CSS in forever. And "Docker" isn't really a language. I'd expect this to more closely reflect what's in my user profile (TS, and Go):

Screenshot 2023-12-07 at 10 09 33 AM

---

Another thing you'll notice: @OgDev-01 has "golang, hacktoberfest" as languages. "hacktoberfest" isn't a programming language so there's something not quite right in there.

---

This, to me, looks like an ordering problem when we get `contributor.languages`. From the API against my own user, this is what's returned:

```
  "languages": {
    "Go": 601455,
    "CSS": 1391,
    "Lua": 5058,
    "Zig": 4320,
    "HTML": 4769,
    "Just": 24,
    "Rust": 7989,
    "Shell": 5566,
    "Python": 616,
    "Makefile": 2520,
    "Dockerfile": 701,
    "JavaScript": 24295,
    "TypeScript": 1393265
  },
```

which is _not_ ordered by the weights when returned from the API. We probably need to apply ordering in this chunk to ensure we get the actual top languages, not just the random first 2:

https://github.com/open-sauced/app/blob/ae560f8b51db10e2cf7ef277538a8df40f1dd616/lib/utils/contributor-utils.ts#L1-L10

But this is just a hunch, there's something that's not quite right when getting these languages.

### Steps to reproduce

1. Go to a big user list of contributors
2. Notice the most used languages
3. Go to profiles for those users
4. Notice the difference

### Browsers

Firefox

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Interests are no longer fallbacks for a user's most languages as interests aren't necessarily languages, e.g. Hacktoberfest. As well aside from Hacktoberfest, the other interests are languages, but it's not reflective of someone's most used languages.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2281

## Steps to QA

1. You need to be logged in
2. Ensure you have no interests set in your user settings, https://deploy-preview-2373--oss-insights.netlify.app/user/settings

CleanShot 2023-12-18 at 20 09 11
3. Go to a grid that you're in like a list's contributor tab. If you're not in the grid, add yourself in a test list.

This is actually hard to test as most people will have languages already, so the fallback will not kick in. 🤔 Maybe the unit tests are enough for this. 

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by OgDev-01 — COMMENTED** [review]
Curious if we have a fallback of `-` displayed on the table when a user has no language to prevent an empty column.

**Comment by nickytonline** [comment]
> Curious if we have a fallback of `-` displayed on the table when a user has no language to prevent an empty column.

I can add that if there are no languages or do our tables handle that out of the box?

**Comment by OgDev-01** [comment]
> I can add that if there are no languages or do our tables handle that out of the box?

The table does not handle that out of the box... You can add that as a fallback 👍

**Comment by nickytonline** [comment]
> > I can add that if there are no languages or do our tables handle that out of the box?
> 
> The table does not handle that out of the box... You can add that as a fallback 👍

I've added a fallback.

**Review by brandonroberts — APPROVED** [review]

**Review by jpmcb — APPROVED** [review]

**Pull request merged**
