### PR TITLE
feat: implement CSV bulk adding

### PR DESCRIPTION
**Pull request by zeucapua**
## Description

Allow users to add repositories in bulk using CSV (comma separated values) pasted in the text area. This PR detects whether a comma is in the input, and splits the repositories with a comma as the delimiter.

## What type of PR is this? (check all applicable)

- [X] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Relates to #2608

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/app/assets/20603494/7193c43b-ab61-42cf-b252-4972b4670d9f

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by nickytonline — APPROVED** [review]
Took it for a spin. Works great! 🚢

**Comment by bdougie** [comment]
This is great and will be really useful. A few things I captured in this video. 

1. Testing spaces without a return and the form thinks it is all the same name. Are we able to catch that edge case? 
2. When hitting back, you do not see the previously added repos, but that works when using the search option. Can we still show the repos selected as comma or return seprated?

https://github.com/open-sauced/app/assets/5713670/d4a1a708-1f00-4942-953f-b52e70a521c6

**Comment by nickytonline** [comment]
> This is great and will be really useful. A few things I captured in this video. 
> 
> 
> 
> 1. Testing spaces without a return and the form thinks it is all the same name. Are we able to catch that edge case? 
> 
> 2. When hitting back, you do not see the previously added repos, but that works when using the search option. Can we still show the repos selected as comma or return seprated?
> 
> 
> 
> https://github.com/open-sauced/app/assets/5713670/d4a1a708-1f00-4942-953f-b52e70a521c6
> 
> 
> 
> 
> 
> 

We can definitely keep it if you go back. We just currently don't. We can have some React state to keep the last text that was in the import textarea @zeucapua .

**Comment by bdougie** [comment]
> The assumption for pasting or typing was new lines and spaces get trimmed. If we're expecting just space delimited, we can handle that, it just wasn't what we were expecting.
> 

I was just being an annoying QA engineer. My expectation most design partners will copy from a spreadsheet. Maybe punt on this and add a cool prettier like feature in the future. 

> The other thing to mention is that this bulk import is tightly scoped with no import validation as that's a bigger lift. Something we can definitely do, but not for the MVP.
> 

That's fair

> We can write some unit tests for the expected formats. We can pair on that tomorrow if you'd like when we sync @zeucapua.

🙏🏾

**Review by brandonroberts — APPROVED** [review]
LGTM 🍕

**Review by jpmcb — APPROVED** [review]

**Pull request merged**
