### PR TITLE
fix: add check for listId to hooks

### PR DESCRIPTION
**Pull request by brandonroberts**
## Description

- Adds checks for listId to hooks to prevent requests with an undefined value

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Review by OgDev-01 — APPROVED** [review]
🍕

**Comment by nickytonline** [comment]
Do the views consuming those hooks still work with this change?

**Comment by brandonroberts** [comment]
> Do the views consuming those hooks still work with this change?

Yes, they do. SWR won't make the request until the `listId` is there, but they have the initial data until then.

**Review by nickytonline — APPROVED** [review]
🚢

**Comment by nickytonline** [comment]
> > Do the views consuming those hooks still work with this change?
> 
> Yes, they do. SWR won't make the request until the `listId` is there, but they have the initial data until then.

I'm still new to SWR. 😅

**Pull request merged**
